window.English = [
  { front: 'ensure', back: 'Make sure something actually happens, no ifs ands or buts.' },
  { front: 'attend', back: 'Show up to a meeting, class, or event. Just be there.' },
  { front: 'recession', back: 'When the economy takes a hit — people lose jobs, things get tight.' },
  { front: 'deficit', back: 'When your spending outpaces your income. You are in the red.' },
  { front: 'surplus', back: 'Having more than you need. Like a surplus of free time or cash.' },
  { front: 'revenue', back: 'The total cash a business brings in from sales, before expenses.' },
  { front: 'monopoly', back: 'When one company has total control over a market — no competition.' },
  { front: 'recruit', back: 'Hiring new people to join the team.' },
  { front: 'dismiss', back: 'Firing someone. Telling them they are done here.' },
  { front: 'resign', back: 'Quitting your job voluntarily. You decided to walk away.' },
  { front: 'freight', back: 'Big cargo shipped by truck, train, or ship.' },
  { front: 'dispatch', back: 'Sending something or someone out to do a job.' },
  { front: 'conservation', back: 'Protecting nature and resources so they don’t run out.' },
  { front: 'regulation', back: 'Rules the government sets that businesses have to follow.' },
  { front: 'clause', back: 'A specific section or rule inside a contract.' },
  { front: 'obligation', back: 'Something you are stuck doing because of a duty or promise.' },
  { front: 'liability', back: 'Legal responsibility — if things go wrong, it’s on your head.' },
  { front: 'compensation', back: 'Money paid to make up for work done or harm suffered.' },
  { front: 'dispute', back: 'A serious disagreement or argument between parties.' },
  { front: 'arbitration', back: 'Letting a neutral third party make a binding decision to settle it.' },
  { front: 'settlement', back: 'Agreeing to end a fight or lawsuit, usually for money.' },
  { front: 'mediation', back: 'Having a neutral helper talk both sides into working it out.' },
  { front: 'breach', back: 'Breaking a contract or failing to keep a promise.' },
  { front: 'minutes', back: 'The official notes from a meeting. What was said and decided.' },
  { front: 'objective', back: 'The specific goal you are shooting for.' },
  { front: 'outcome', back: 'The final result after everything plays out.' },
  { front: 'itinerary', back: 'Your travel plan — where you are going and when.' },
  { front: 'diagnosis', back: 'The doctor figuring out what is wrong with you.' },
  { front: 'prescription', back: 'The doctor’s order for medicine or treatment.' },
  { front: 'thesis', back: 'A long research paper you write to finish your degree.' },
  { front: 'compromise', back: 'Both sides giving up a little so everyone can agree.' },
  { front: 'discrimination', back: 'Unfair treatment of someone based on race, gender, age, etc.' },
  { front: 'permanent', back: 'Lasting forever, not temporary.' },
  { front: 'voucher', back: 'A coupon that acts like cash for specific things.' },
  { front: 'complaint', back: 'A formal way of saying something is wrong and needs fixing.' },
  { front: 'projection', back: 'A guess or estimate about future numbers.' },
  { front: 'warranty', back: 'A guarantee that the seller will fix or replace it if it breaks.' },
  { front: 'coverage', back: 'What your insurance actually pays for.' },
  { front: 'deductible', back: 'The amount you pay out of pocket before insurance kicks in.' },
  { front: 'invoice', back: 'A bill you send to a client asking to be paid.' },
  { front: 'provision', back: 'A specific condition or rule inside a larger agreement.' },
  { front: 'CFO', back: 'Chief Financial Officer — the boss of all company money.' },
  { front: 'COO', back: 'Chief Operating Officer — the boss of daily operations.' },
  { front: 'CTO', back: 'Chief Technology Officer — the boss of tech and engineering.' },
  { front: 'CIO', back: 'Chief Information Officer — the boss of data and IT systems.' },
  { front: 'CMO', back: 'Chief Marketing Officer — the boss of advertising and branding.' },
  { front: 'CHRO', back: 'Chief Human Resources Officer — the boss of people and culture.' },
  { front: 'auditor', back: 'Someone who checks company books to make sure everything is legit.' },
  { front: 'income statement', back: 'A report showing how much money a company made and spent over time.' },
  { front: 'equity', back: 'The actual value of ownership in a company or property.' },
  { front: 'capital', back: 'The money you use to start or grow a business.' },
  { front: 'yield', back: 'The profit or income an investment generates over time.' },
  { front: 'dividend', back: 'A share of company profits paid out to shareholders.' },
  { front: 'diversification', back: 'Not putting all your eggs in one basket. Spreading risk.' },
  { front: 'allocation', back: 'Deciding how to distribute your money or resources.' },
  { front: 'benchmark', back: 'A standard or point of reference to measure against.' },
  { front: 'distribution', back: 'The process of getting products to customers.' },
  { front: 'perception', back: 'How people see or understand something, whether true or not.' },
  { front: 'authenticity', back: 'Being genuine and real. Not fake or scripted.' },
  { front: 'SEO', back: 'Search Engine Optimization — making your site rank higher on Google.' },
  { front: 'PPC', back: 'Pay-Per-Click — you only pay when someone clicks your ad.' },
  { front: 'CPM', back: 'Cost Per Mille — you pay for every 1,000 times your ad is shown.' },
  { front: 'CPC', back: 'Cost Per Click — same as PPC. Pay per click.' },
  { front: 'CPA', back: 'Cost Per Acquisition — you pay when someone actually buys or signs up.' },
  { front: 'ROI', back: 'Return on Investment — how much profit you made compared to what you spent.' },
  { front: 'KPI', back: 'Key Performance Indicator — the main metric that shows if you are winning.' },
  { front: 'metric', back: 'A number used to track and measure performance.' },
  { front: 'bounce', back: 'When someone visits your site and leaves immediately without clicking anything.' },
  { front: 'opt-in', back: 'Giving permission to receive emails or messages.' },
  { front: 'opt-out', back: 'Withdrawing permission to stop receiving emails or messages.' },
  { front: 'quota', back: 'A target number you have to hit, usually for sales.' },
  { front: 'margin', back: 'The profit left over after paying the cost of goods.' },
  { front: 'commission', back: 'A percentage of sales paid to you as a bonus.' },
  { front: 'incentive', back: 'A reward or perk to motivate people to work harder.' },
  { front: 'hypothesis', back: 'An educated guess you test to see if it is true.' },
  { front: 'median', back: 'The middle number in a sorted list of data.' },
  { front: 'standard deviation', back: 'How spread out your data is from the average.' },
  { front: 'correlation', back: 'When two things move together. If one goes up, the other does too.' },
  { front: 'regression', back: 'A statistical method to predict future values based on past data.' },
  { front: 'probability', back: 'The chance that something will happen, from 0 to 100 percent.' },
  { front: 'reasoning', back: 'The process of thinking logically to reach a conclusion.' },
  { front: 'induction', back: 'Making a general rule based on specific examples you have seen.' },
  { front: 'premise', back: 'The underlying assumption or starting point of an argument.' }
];