window.Spanish = [
  // --- 動物・生き物 ---
  { front: '🐺', back: 'lobo' },
  { front: '🦊', back: 'zorro' },
  { front:'🐱', back:'gato' },
  { front: '🐯', back: 'tigre' },
  { front: '🦁', back: 'león' },
  { front: '🦇', back: 'murciélago' },
  { front: '🐵', back: 'mono' },
  { front: '🦉', back: 'búho' },
  { front: '🐢', back: 'tortuga' },
  { front: '🐻‍❄️', back: 'oso polar' },
  { front: '🐨', back: 'koala' },
  { front: '🐴', back: 'caballo' },
  { front: '🐹', back: 'hámster' },
  { front: '🦓', back: 'cebra' },
  { front: '🐑', back: 'oveja' },
  { front: '🐖', back: 'cerdo' },
  { front: '🐄', back: 'vaca' },
  { front: '🦒', back: 'jirafa' },
  { front: '🐘', back: 'elefante' },
  { front: '🐫', back: 'camello' },
  { front: '🐣', back: 'pollito' },
  { front: '🐓', back: 'gallo' },
  { front: '🕊️', back: 'paloma' },
  { front: '🦚', back: 'pavo real' },
  { front: '🐬', back: 'delfín' },
  { front: '🦈', back: 'tiburón' },
  { front: '🦀', back: 'cangrejo' },
  { front: '🪼', back: 'medusa' },
  { front: '🐛', back: 'oruga' },
  
  // --- 食べ物 ---
  { front: '🍎', back: 'manzana' },
  { front: '🍓', back: 'fresa' },
  { front: '🍉', back: 'sandía' },
  { front: '🍒', back: 'cereza' },
  { front: '🍍', back: 'piña' },
  { front: '🍊', back: 'naranja' },
  { front: '🍑', back: 'durazno' },
  { front: '🥕', back: 'zanahoria' },
  { front: '🥦', back: 'brócoli' },
  { front: '🥑', back: 'aguacate' },
  { front: '🫑', back: 'pimiento' },
  { front: '🍆', back: 'berenjena' },
  { front: '🍇', back: 'uva' },
  { front: '🥒', back: 'pepino' },
  { front: '🍄‍🟫', back: 'seta' },
  { front: '🧄', back: 'ajo' },
  { front: '🍺', back: 'cerveza' },
  
  // --- 自然・天気・その他 ---
  { front: '💎', back: 'diamante' },
  { front: '🌸', back: 'flor de cerezo' },
  { front: '☔', back: 'paraguas' },
  { front: '☀️', back: 'sol' },
  { front: '🌙', back: 'luna' },
  { front: '🌏', back: 'tierra' },
  { front: '🌕', back: 'luna llena' },
  { front: '⚡', back: 'rayo' },
  { front: '🎉', back: 'confeti' },
  { front: '🧭', back: 'brújula' },
  { front: '🎡', back: 'noria' },
  { front: '💍', back: 'anillo' },
  { front: '🛡️', back: 'escudo' },
  { front: '🗡️', back: 'espada' },
  { front: '⚰️', back: 'ataúd' },
  { front: '🪦', back: 'lápida' },
  { front: '🗝️', back: 'llave vieja' },
  
  // --- 感情・顔 ---
  { front: '😄', back: 'sonrisa' },
  { front: '🥲', back: 'sonrisa con lágrima' },
  { front: '😱', back: 'miedo' },
  { front: '👻', back: 'fantasma' },
  { front: '💀', back: 'calavera' },
  
  // --- 職業 (女性) ---
  { front: '👩🏻‍🎨', back: 'artista' },
  { front: '👩🏻‍🍳', back: 'cocinera' },
  { front: '👩🏻‍🚒', back: 'bombero' },
  { front: '👩🏻‍🌾', back: 'agricultora' },
  { front: '👩🏻‍✈️', back: 'piloto' },
  { front: '👩🏻‍🎓', back: 'estudiante' },
  { front: '👩🏻‍🎤', back: 'cantante' },
  { front: '👩🏻‍⚖️', back: 'jueza' }
];
