window.English = [
// --- 動物・生き物 (Animals) ---
  { front: '🐺', back: 'wolf' },
  { front: '🦊', back: 'fox' },
  { front: '🐱', back: 'cat' },
  { front: '🐯', back: 'tiger' },
  { front: '🦁', back: 'lion' },
  { front: '🦇', back: 'bat' },
  { front: '🐵', back: 'monkey' },
  { front: '🦉', back: 'owl' },
  { front: '🐢', back: 'turtle' },
  { front: '🐻‍❄️', back: 'polar bear' },
  { front: '🐨', back: 'koala' },
  { front: '🐴', back: 'horse' },
  { front: '🐹', back: 'hamster' },
  { front: '🦓', back: 'zebra' },
  { front: '🐑', back: 'sheep' },
  { front: '🐖', back: 'pig' },
  { front: '🐄', back: 'cow' },
  { front: '🦒', back: 'giraffe' },
  { front: '🐘', back: 'elephant' },
  { front: '🐫', back: 'camel' },
  { front: '🐣', back: 'chick' },
  { front: '🐓', back: 'rooster' },
  { front: '🕊️', back: 'dove' },
  { front: '🦚', back: 'peacock' },
  { front: '🐬', back: 'dolphin' },
  { front: '🦈', back: 'shark' },
  { front: '🦀', back: 'crab' },
  { front: '🪼', back: 'jellyfish' },
  { front: '🐛', back: 'caterpillar' },
  { front: '🦖', back: 'tyrannosaurus' },
  { front: '🦕', back: 'dinosaur' },
  { front: '🦘', back: 'kangaroo' },
  { front: '🦥', back: 'sloth' },
  { front: '🦦', back: 'otter' },
  { front: '🦩', back: 'flamingo' },
  { front: '🐈', back: 'cat' },
  { front: '🐕', back: 'dog' },
  { front: '🐇', back: 'rabbit' },
  { front: '🦡', back: 'badger' },
  { front: '🦨', back: 'skunk' },
  { front: '🦝', back: 'raccoon' },
  { front: '🦭', back: 'seal' },
  { front: '🦶', back: 'sled' },
  { front: '🪶', back: 'feather' },
  { front: '🥚', back: 'egg' },
  { front: '🦴', back: 'bone' },
  { front: '🦧', back: 'orangutan' },
  { front: '🐀', back: 'rat' },
  { front: '🐁', back: 'mouse' },
  { front: '🐂', back: 'ox' },
  { front: '🐋', back: 'whale' },
  { front: '🐌', back: 'snail' },
  { front: '🐃', back: 'water buffalo' },
  { front: '🐆', back: 'leopard' },
  { front: '🐉', back: 'dragon' },
  { front: '🐊', back: 'crocodile' },
  { front: '🐗', back: 'boar' },
  { front: '🐙', back: 'octopus' },
  { front: '🐚', back: 'seashell' },
  { front: '🐟', back: 'fish' },
  { front: '🐐', back: 'goat' },
  { front: '🐍', back: 'snake' },
  { front: '🐩', back: 'poodle' },
  { front: '🐪', back: 'camel' },
  { front: '🐮', back: 'cow' },
  { front: '🐻', back: 'bear' },
  { front: '🐼', back: 'panda' },
  { front: '🐾', back: 'paw print' },
  { front: '🐿️', back: 'squirrel' },
  { front: '🦆', back: 'duck' },
  { front: '🦅', back: 'eagle' },
  { front: '🦄', back: 'unicorn' },
  { front: '🦃', back: 'turkey' },
  { front: '🦂', back: 'scorpion' },
  { front: '🦌', back: 'deer' },
  { front: '🦍', back: 'gorilla' },
  { front: '🦎', back: 'lizard' },
  { front: '🦏', back: 'rhino' },
  { front: '🦐', back: 'shrimp' },
  { front: '🦑', back: 'squid' },
  { front: '🦣', back: 'mammoth' },
  { front: '🦛', back: 'hippo' },
  { front: '🦙', back: 'llama' },
  { front: '🦔', back: 'hedgehog' },
  { front: '🦫', back: 'beaver' },
  { front: '🦬', back: 'bison' },
  { front: '🫎', back: 'moose' },
  { front: '🫏', back: 'donkey' },
  { front: '🙈', back: 'monkey' },
  { front: '🙉', back: 'monkey' },
  { front: '🙊', back: 'monkey' },
  { front: '🐸', back: 'frog' },
  { front: '🦮', back: 'guide dog' },
  { front: '🐕‍🦺', back: 'service dog' },
  { front: '🐏', back: 'ram' },
  { front: '🐦', back: 'bird' },
  { front: '🐦‍⬛', back: 'crow' },
  { front: '🦜', back: 'parrot' },
  { front: '🦤', back: 'dodo' },
  { front: '🦢', back: 'swan' },
  { front: '🪿', back: 'goose' },
  { front: '🐦‍🔥', back: 'phoenix' },
  { front: '🐧', back: 'penguin' },
  { front: '🫍', back: 'orca / killer whale' },
  { front: '🐠', back: 'tropical fish' },
  { front: '🐡', back: 'blowfish' },
  { front: '🦪', back: 'oyster' },
  { front: '🪸', back: 'coral' },
  { front: '🫧', back: 'bubbles' },
  { front: '🕷️', back: 'spider' },
  { front: '🕸️', back: 'spiderweb' },
  { front: '🐜', back: 'ant' },
  { front: '🦗', back: 'cricket' },
  { front: '🪲', back: 'June bug/June beetle' },
  { front: '🦟', back: 'mosquito' },
  { front: '🪳', back: 'roach' },
  { front: '🪰', back: 'fly' },
  { front: '🐝', back: 'bee' },
  { front: '🐞', back: 'ladybug' },
  { front: '🦋', back: 'butterfly' },
  { front: '🪱', back: 'earthworm' },
  { front: '🦠', back: 'microbe' },

  // --- 食べ物・飲み物 (Food & Drink) ---
  { front: '🍎', back: 'apple' },
  { front: '🍓', back: 'strawberry' },
  { front: '🍉', back: 'watermelon' },
  { front: '🍒', back: 'cherries' },
  { front: '🍍', back: 'pineapple' },
  { front: '🍊', back: 'mandarin' },
  { front: '🍑', back: 'peach' },
  { front: '🥕', back: 'carrot' },
  { front: '🥦', back: 'broccoli' },
  { front: '🥑', back: 'avocado' },
  { front: '🫑', back: 'bell pepper' },
  { front: '🍆', back: 'eggplant' },
  { front: '🍇', back: 'grapes' },
  { front: '🥒', back: 'cucumber' },
  { front: '🍄‍🟫', back: 'mushroom' },
  { front: '🧄', back: 'garlic' },
  { front: '🥬', back: 'leafy greens' },
  { front: '🧅', back: 'onion' },
  { front: '🥔', back: 'potato' },
  { front: '🌽', back: 'corn' },
  { front: '🍅', back: 'tomato' },
  { front: '🍋', back: 'lemon' },
  { front: '🍌', back: 'banana' },
  { front: '🍐', back: 'pear' },
  { front: '🥝', back: 'kiwi' },
  { front: '🥭', back: 'mango' },
  { front: '🥥', back: 'coconut' },
  { front: '🥐', back: 'croissant' },
  { front: '🥖', back: 'baguette' },
  { front: '🍞', back: 'bread' },
  { front: '🧀', back: 'cheese' },
  { front: '🥩', back: 'steak' },
  { front: '🍗', back: 'chicken leg' },
  { front: '🍔', back: 'burger' },
  { front: '🍕', back: 'pizza' },
  { front: '🍜', back: 'ramen' },
  { front: '🍣', back: 'sushi' },
  { front: '🍩', back: 'donut' },
  { front: '🍰', back: 'shortcake' },
  { front: '🍫', back: 'chocolate bar' },
  { front: '☕', back: 'coffee' },
  { front: '🍵', back: 'matcha' },
  { front: '🍺', back: 'beer' },
  { front: '🍷', back: 'wine' },
  { front: '🌶️', back: 'chili pepper' },
  { front: '🍋‍🟩', back: 'lime' },
  { front: '🍈', back: 'melon' },
  { front: '🫛', back: 'peas' },
  { front: '🍏', back: 'green apple' },
  { front: '🫒', back: 'olive' },
  { front: '🫐', back: 'blueberries' },
  { front: '🍠', back: 'sweet potato' },
  { front: '🫜', back: 'red raddish' },
  { front: '🫚', back: 'ginger' },
  { front: '🫘', back: 'beans' },
  { front: '🌰', back: 'chestnut' },
  { front: '🥜', back: 'peanuts' },
  { front: '🫓', back: 'flatbread' },
  { front: '🥯', back: 'bagel' },
  { front: '🧇', back: 'waffle' },
  { front: '🥞', back: 'pancakes' },
  { front: '🍳', back: 'fried egg' },
  { front: '🥓', back: 'bacon' },
  { front: '🍖', back: 'ribs' },
  { front: '🌭', back: 'hot dog' },
  { front: '🥪', back: 'sandwich' },
  { front: '🥨', back: 'pretzel' },
  { front: '🍟', back: 'fries' },
  { front: '🫔', back: 'tamale' },
  { front: '🌮', back: 'taco' },
  { front: '🌯', back: 'burrito' },
  { front: '🥙', back: 'pita' },
  { front: '🧆', back: 'falafel' },
  { front: '🥘', back: 'paella' },
  { front: '🍝', back: 'spaghetti' },
  { front: '🥫', back: 'canned food' },
  { front: '🫕', back: 'fondue' },
  { front: '🥣', back: 'cereal' },
  { front: '🥗', back: 'salad' },
  { front: '🍲', back: 'stew' },
  { front: '🍛', back: 'curry' },
  { front: '🦞', back: 'lobster' },
  { front: '🍤', back: 'tempura' },
  { front: '🥡', back: 'takeout box' },
  { front: '🍚', back: 'rice' },
  { front: '🍱', back: 'bento' },
  { front: '🥟', back: 'dumpling' },
  { front: '🍢', back: 'oden' },
  { front: '🍙', back: 'rice ball' },
  { front: '🍘', back: 'rice cracker' },
  { front: '🍥', back: 'fish cake' },
  { front: '🍡', back: 'dango' },
  { front: '🥠', back: 'fortune cookie' },
  { front: '🥮', back: 'mooncake' },
  { front: '🍧', back: 'shaved ice' },
  { front: '🍨', back: 'ice cream' },
  { front: '🍦', back: 'soft serve' },
  { front: '🥧', back: 'pie' },
  { front: '🍮', back: 'custard (pudding)/crème caramel/flan' },
  { front: '🎂', back: 'birthday cake' },
  { front: '🧁', back: 'cupcake' },
  { front: '🍭', back: 'lollipop' },
  { front: '🍬', back: 'candy' },
  { front: '🍪', back: 'cookie' },
  { front: '🍯', back: 'honey' },
  { front: '🧂', back: 'salt' },
  { front: '🧈', back: 'butter' },
  { front: '🍿', back: 'popcorn' },
  { front: '🧊', back: 'ice cube' },
  { front: '🫙', back: 'jar' },
  { front: '🥤', back: 'soft drink' },
  { front: '🧋', back: 'bubble tea/boba tea' },
  { front: '🧃', back: 'juice box' },
  { front: '🥛', back: 'milk' },
  { front: '🍼', back: 'baby bottle' },
  { front: '🫖', back: 'teapot' },
  { front: '🧉', back: 'Yerba mate' },
  { front: '🍻', back: 'beers' },
  { front: '🥂', back: 'cheers' },
  { front: '🍾', back: 'champagne' },
  { front: '🥃', back: 'whiskey glass' },
  { front: '🫗', back: 'pouring' },
  { front: '🍸', back: 'cocktail' },
  { front: '🍹', back: 'tropical drink' },
  { front: '🍶', back: 'sake' },
  { front: '🥢', back: 'chopsticks' },
  { front: '🍴', back: 'cutlery' },
  { front: '🥄', back: 'spoon' },
  { front: '🔪', back: 'knife' },
  { front: '🍽️', back: 'plate and cutlery' },

  // --- 植物・自然・天気 (Nature & Weather) ---
  { front: '💎', back: 'gem' },
  { front: '🌸', back: 'cherry blossom' },
  { front: '🪻', back: 'hyacinth' },
  { front: '🌷', back: 'tulip' },
  { front: '🌹', back: 'rose' },
  { front: '🌻', back: 'sunflower' },
  { front: '🌼', back: 'blossom' },
  { front: '🌵', back: 'cactus' },
  { front: '🌲', back: 'pine tree' },
  { front: '🌳', back: 'tree' },
  { front: '🍀', back: 'four-leaf clover' },
  { front: '🍁', back: 'maple leaf' },
  { front: '☔', back: 'umbrella' },
  { front: '☀️', back: 'sun' },
  { front: '🌙', back: 'crescent moon' },
  { front: '🌏', back: 'globe' },
  { front: '🌕', back: 'full moon' },
  { front: '⚡', back: 'lightning' },
  { front: '🌈', back: 'rainbow' },
  { front: '🔥', back: 'fire' },
  { front: '💧', back: 'droplet' },
  { front: '🌊', back: 'wave' },
  { front: '❄️', back: 'snowflake' },
  { front: '⭐', back: 'star' },
  { front: '💐', back: 'bouquet' },
  { front: '🥀', back: 'wilted flower' },
  { front: '🌺', back: 'hibiscus' },
  { front: '🪷', back: 'lotus' },
  { front: '💮', back: 'flower stamp' },
  { front: '🏵️', back: 'rosette' },
  { front: '🍂', back: 'fallen leaf' },
  { front: '🍄', back: 'mushroom' },
  { front: '🌾', back: 'sheaf of rice' },
  { front: '🌿', back: 'herb' },
  { front: '🌱', back: 'seedling' },
  { front: '🍃', back: 'leaves in wind' },
  { front: '☘️', back: 'shamrock' },
  { front: '🪴', back: 'houseplant' },
  { front: '🌴', back: 'palm tree' },
  { front: '🪾', back: 'dead tree' },
  { front: '🪵', back: 'wood' },
  { front: '🪹', back: 'empty nest' },
  { front: '🪺', back: 'bird nest' },
  { front: '🪨', back: 'rock' },
  { front: '🛘', back: 'rockfall / rockslide' },
  { front: '⛰️', back: 'mountain' },
  { front: '🏔️', back: 'snowy mountain / snow-capped mountain' },
  { front: '⛄', back: 'snowman' },
  { front: '🌡️', back: 'thermometer' },
  { front: '🌋', back: 'volcano' },
  { front: '🏜️', back: 'desert' },
  { front: '🏞️', back: 'national park' },
  { front: '🌅', back: 'sunrise over the sea' },
  { front: '🌄', back: 'sunrise over mountains' },
  { front: '🏝️', back: 'island' },
  { front: '🏖️', back: 'beach' },
  { front: '🌬️', back: 'wind' },
  { front: '🌀', back: 'cyclone' },
  { front: '🌪️️', back: 'tornado' },
  { front: '☁️', back: 'cloud' },
  { front: '🌨️', back: 'snow' },
  { front: '🌧️', back: 'rain' },
  { front: '🌩️', back: 'thunderstorm' },
  { front: '⛈️', back: 'storm' },
  { front: '🌦️', back: 'sun showers' },
  { front: '🌥️', back: 'partly cloudy' },
  { front: '⛅', back: 'partly sunny' },
  { front: '🌤️', back: 'mostly sunny' },
  { front: '🌞', back: 'sun' },
  { front: '🌝', back: 'full moon' },
  { front: '🌚', back: 'new moon' },
  { front: '🌜', back: 'moon' },
  { front: '🌛', back: 'moon' },
  { front: '🌟', back: 'glowing star' },
  { front: '✨', back: 'sparkles' },
  { front: '🕳️', back: 'hole' },
  { front: '🪐', back: 'planet / Saturn' },
  { front: '🌍', back: 'globe showing Europe-Africa' },
  { front: '🌎', back: 'globe showing Americas' },
  { front: '🌫️', back: 'fog' },
  { front: '🌠', back: 'shooting star' },
  { front: '🌌', back: 'galaxy' },
  { front: '☄️', back: 'comet' },
  { front: '🌑', back: 'new moon' },
  { front: '🌒', back: 'waxing crescent' },
  { front: '🌓', back: 'first quarter moon' },
  { front: '🌔', back: 'waxing gibbous' },
  { front: '🌖', back: 'waning gibbous' },
  { front: '🌗', back: 'last quarter moon' },
  { front: '🌘', back: 'waning crescent' },

  // --- 感情・顔 (Emotions & Faces) ---
  { front: '😄', back: 'grin' },
  { front: '🥲', back: 'tear of joy' },
  { front: '🤤', back: 'drooling' },
  { front: '🥹', back: 'holding back tears' },
  { front: '😱', back: 'screaming' },
  { front: '👻', back: 'ghost' },
  { front: '💀', back: 'skull' },
  { front: '😍', back: 'heart eyes' },
  { front: '😎', back: 'sunglasses' },
  { front: '😢', back: 'crying' },
  { front: '😡', back: 'angry' },
  { front: '🥳', back: 'partying' },
  { front: '😴', back: 'sleeping' },
  { front: '🤖', back: 'robot' },
  { front: '👽', back: 'alien' },
  { front: '💩', back: 'poop' },
  { front: '😀', back: 'grinning' },
  { front: '😃', back: 'smiley' },
  { front: '😁', back: 'beaming' },
  { front: '😆', back: 'laughing' },
  { front: '😅', back: 'sweat smile' },
  { front: '😂', back: 'laugh crying' },
  { front: '🤣', back: 'rofl' },
  { front: '😭', back: 'sobbing' },
  { front: '😉', back: 'wink' },
  { front: '😗', back: 'kiss' },
  { front: '😙', back: 'kiss smiling' },
  { front: '😚', back: 'kiss eyes closed' },
  { front: '😘', back: 'blow kiss' },
  { front: '🥰', back: 'loving' },
  { front: '🤩', back: 'star struck' },
  { front: '🫠', back: 'melting' },
  { front: '🙃', back: 'upside down' },
  { front: '🙂', back: 'slight smile' },
  { front: '😊', back: 'blushing' },
  { front: '☺️', back: 'smile' },
  { front: '😌', back: 'relieved' },
  { front: '🙂‍↕️', back: 'nodding' },
  { front: '🙂‍↔️', back: 'shaking head' },
  { front: '😏', back: 'smirk' },
  { front: '😋', back: 'yum' },
  { front: '😛', back: 'tongue out' },
  { front: '😝', back: 'squint tongue' },
  { front: '😜', back: 'wink tongue' },
  { front: '🤪', back: 'zany' },
  { front: '🫪', back: 'distorted' },
  { front: '😔', back: 'pensive' },
  { front: '🥺', back: 'pleading' },
  { front: '😬', back: 'grimacing' },
  { front: '😑', back: 'expressionless' },
  { front: '😐', back: 'neutral' },
  { front: '😶', back: 'speechless' },
  { front: '😶‍🌫️', back: 'in the clouds' },
  { front: '🫥', back: 'invisible' },
  { front: '🤐', back: 'zipped lips' },
  { front: '🫡', back: 'salute' },
  { front: '🤔', back: 'thinking' },
  { front: '🤫', back: 'shushing' },
  { front: '🫢', back: 'gasps' },
  { front: '🤭', back: 'giggling' },
  { front: '🥱', back: 'yawning' },
  { front: '🤗', back: 'hugging' },
  { front: '🫣', back: 'peeking' },
  { front: '🤨', back: 'skeptical' },
  { front: '🧐', back: 'monocle' },
  { front: '😒', back: 'unamused' },
  { front: '🙄', back: 'eye roll' },
  { front: '😮‍💨', back: 'exhaling' },
  { front: '😤', back: 'triumph' },
  { front: '🤬', back: 'cursing' },
  { front: '😞', back: 'disappointed' },
  { front: '😓', back: 'sweating' },
  { front: '😟', back: 'worried' },
  { front: '😥', back: 'relieved sad' },
  { front: '☹️', back: 'frowning' },
  { front: '🙁', back: 'slight frown' },
  { front: '🫤', back: 'skeptical' },
  { front: '😕', back: 'confused' },
  { front: '😰', back: 'anxious' },
  { front: '😨', back: 'fearful' },
  { front: '😧', back: 'anguished' },
  { front: '😦', back: 'frowning open mouth' },
  { front: '😮', back: 'open mouth' },
  { front: '😯', back: 'hushed' },
  { front: '😲', back: 'astonished' },
  { front: '😳', back: 'flushed' },
  { front: '🤯', back: 'mind blown' },
  { front: '😖', back: 'confounded' },
  { front: '😣', back: 'persevering' },
  { front: '😩', back: 'weary' },
  { front: '😫', back: 'tired' },
  { front: '😵', back: 'dizzy' },
  { front: '😵‍💫', back: 'spiral eyes' },
  { front: '🫨', back: 'shaking' },
  { front: '🥴', back: 'woozy' },
  { front: '🥵', back: 'hot' },
  { front: '🥶', back: 'cold' },
  { front: '🤢', back: 'nauseous' },
  { front: '🤮', back: 'vomiting' },
  { front: '🫩', back: 'holding tears' },
  { front: '😪', back: 'sleepy' },
  { front: '🤧', back: 'sneezing' },
  { front: '🤒', back: 'sick' },
  { front: '🤕', back: 'injured' },
  { front: '😷', back: 'masked' },
  { front: '🤥', back: 'lying' },
  { front: '😇', back: 'angel' },
  { front: '🤠', back: 'cowboy' },
  { front: '🤑', back: 'rich' },
  { front: '🤓', back: 'nerd' },
  { front: '🥸', back: 'disguised' },
  { front: '🤡', back: 'clown' },
  { front: '😈', back: 'devil' },
  { front: '👿', back: 'angry devil' },
  { front: '☠️', back: 'skull and crossbones' },
  { front: '👹', back: 'ogre' },
  { front: '👺', back: 'goblin' },
  { front: '👾', back: 'space invader' },
  { front: '😺', back: 'grinning cat' },
  { front: '😸', back: 'happy cat' },
  { front: '😹', back: 'laughing cat' },
  { front: '😻', back: 'heart cat' },
  { front: '😼', back: 'smirking cat' },
  { front: '😽', back: 'kissing cat' },
  { front: '🙀', back: 'scared cat' },
  { front: '😿', back: 'crying cat' },
  { front: '😾', back: 'pouting cat' },
  { front: '💫', back: 'dizzy' },
  { front: '💥', back: 'boom' },
  { front: '🫯', back: 'fingerprint' },
  { front: '💢', back: 'anger' },
  { front: '💨', back: 'dash' },
  { front: '💤', back: 'zzz' },
  { front: '💯', back: 'hundred' },
  { front: '🎊', back: 'confetti' },
  { front: '❤️', back: 'red heart' },
  { front: '🧡', back: 'orange heart' },
  { front: '💛', back: 'yellow heart' },
  { front: '💚', back: 'green heart' },
  { front: '🩵', back: 'light blue heart' },
  { front: '💙', back: 'blue heart' },
  { front: '💜', back: 'purple heart' },
  { front: '🤎', back: 'brown heart' },
  { front: '🖤', back: 'black heart' },
  { front: '🩶', back: 'grey heart' },
  { front: '🤍', back: 'white heart' },
  { front: '🩷', back: 'pink heart' },
  { front: '💘', back: 'heart with arrow' },
  { front: '💝', back: 'gift heart' },
  { front: '💖', back: 'sparkling heart' },
  { front: '💗', back: 'growing heart' },
  { front: '💓', back: 'beating heart' },
  { front: '💞', back: 'revolving hearts' },
  { front: '💕', back: 'two hearts' },
  { front: '💌', back: 'love letter' },
  { front: '💟', back: 'heart decoration' },
  { front: '♥️', back: 'heart suit' },
  { front: '❣️', back: 'heart exclamation' },
  { front: '❤️‍🩹', back: 'mending heart' },
  { front: '💔', back: 'broken heart' },
  { front: '❤️‍🔥', back: 'heart on fire' },
  { front: '💋', back: 'kiss mark' },
  { front: '🫂', back: 'hug' },
  { front: '👥', back: 'silhouettes' },
  { front: '👤', back: 'silhouette' },
  { front: '🗣️', back: 'speaking head' },
  { front: '👣', back: 'footprints' },
  { front: '🫆', back: 'fingerprint' },
  { front: '💦', back: 'sweat drops' },
  { front: '🧠', back: 'brain' },
  { front: '🫀', back: 'heart' },
  { front: '🫁', back: 'lungs' },
  { front: '🩸', back: 'blood' },
  { front: '🦷', back: 'tooth' },
  { front: '👀', back: 'eyes' },
  { front: '👁️', back: 'eye' },
  { front: '👄', back: 'mouth' },
  { front: '🫦', back: 'biting lip' },
  { front: '👅', back: 'tongue' },
  { front: '👃🏻', back: 'nose' },
  { front: '👂🏻', back: 'ear' },
  { front: '🦻🏻', back: 'ear with hearing aid' },
  { front: '🦶🏻', back: 'foot' },
  { front: '🦵🏻', back: 'leg' },
  { front: '🦿', back: 'prosthetic leg' },
  { front: '🦾', back: 'prosthetic arm' },
  { front: '💪🏻', back: 'biceps' },
  { front: '👏🏻', back: 'clapping' },
  { front: '👍🏻', back: 'thumbs up' },
  { front: '🫶🏻', back: 'heart hands' },
  { front: '🙌🏻', back: 'raising hands' },
  { front: '👐🏻', back: 'open hands' },
  { front: '🤲🏻', back: 'cupped hands' },
  { front: '🤜🏻', back: 'right fist' },
  { front: '🤛🏻', back: 'left fist' },
  { front: '✊🏻', back: 'raised fist' },
  { front: '👊🏻', back: 'fist bump' },
  { front: '🫳🏻', back: 'palm down' },
  { front: '🫴🏻', back: 'palm up' },
  { front: '🫱🏻', back: 'right hand' },
  { front: '🫲🏻', back: 'left hand' },
  { front: '🫸🏻', back: 'pushing hand' },
  { front: '🫷🏻', back: 'pushing hand' },
  { front: '👋🏻', back: 'wave' },
  { front: '🤚🏻', back: 'back of hand' },
  { front: '🖐🏻', back: 'spread hand' },
  { front: '✋🏻', back: 'raised hand' },
  { front: '🖖🏻', back: 'vulcan salute' },
  { front: '🤟🏻', back: 'love you' },
  { front: '🤘🏻', back: 'rock on' },
  { front: '✌🏻', back: 'peace' },
  { front: '🤞🏻', back: 'fingers crossed' },
  { front: '🫰🏻', back: 'finger heart' },
  { front: '🤙🏻', back: 'call me' },
  { front: '🤌🏻', back: 'italian hand' },
  { front: '🤏🏻', back: 'pinched' },
  { front: '👌🏻', back: 'ok' },
  { front: '🫵🏻', back: 'pointing at you' },
  { front: '👉🏻', back: 'pointing right' },
  { front: '👈🏻', back: 'pointing left' },
  { front: '☝🏻', back: 'pointing up' },
  { front: '👆🏻', back: 'pointing up' },
  { front: '👇🏻', back: 'pointing down' },
  { front: '✍🏻', back: 'writing' },
  { front: '🤳🏻', back: 'selfie' },
  { front: '🙏🏻', back: 'prayer' },
  { front: '💅🏻', back: 'nails' },
  { front: '🤝🏻', back: 'handshake' },

  // --- 乗り物・旅行 (Vehicles & Travel) ---
  { front: '🛑', back: 'stop sign' },
  { front: '🚧', back: 'barricade / Type III barricade / road barrier' },
  { front: '🚨', back: 'emergency light / strobe light / siren / emergency vehicle light' },
  { front: '⛽', back: 'gas pump / fuel pump' },
  { front: '🛢️', back: 'oil drum / steel drum / barrel' },
  { front: '🧭', back: 'compass' },
  { front: '🛞', back: 'wheel' },
  { front: '🛟', back: 'life ring / life preserver / lifebuoy ' },
  { front: '⚓', back: 'anchor' },
  { front: '🚏', back: 'bus stop' },
  { front: '🚇', back: 'subway / metro' },
  { front: '🚥', back: 'horizontal traffic light' },
  { front: '🚦', back: 'vertical traffic light' },
  { front: '🛴', back: 'scooter' },
  { front: '🦽', back: 'wheelchair / push wheelchair' },
  { front: '🦼', back: 'electric wheelchair / power chair' },
  { front: '🩼', back: 'crutch' },
  { front: '🚲', back: 'bike' },
  { front: '🛵', back: 'moped / motor scooter' },
  { front: '🏍️️', back: 'motorcycle' },
  { front: '🚙', back: 'SUV(sport utility vehicle)' },
  { front: '🚗', back: 'car' },
  { front: '🛻', back: 'pickup truck' },
  { front: '🚐', back: 'van' },
  { front: '🚚', back: 'box truck / delivery truck' },
  { front: '🚛', back: 'artic / articulated lorry / Semi-truck / Semi / Tractor-trailer' },
  { front: '🚜', back: 'tractor' },
  { front: '🏎️', back: 'race car' },
  { front: '🚒', back: 'firetruck' },
  { front: '🚑', back: 'ambulance' },
  { front: '🚓', back: 'police car' },
  { front: '🚕', back: 'taxi' },
  { front: '🛺', back: 'tuk-tuk / auto rickshaw' },
  { front: '🚌', back: 'bus' },
  { front: '🚈', back: 'tram / light rail / streetcar' },
  { front: '🚝', back: 'monorail' },
  { front: '🚅', back: 'bullet train' },
  { front: '🚄', back: 'high speed train' },
  { front: '🚂', back: 'steam locomotive' }, { front: '🚃', back: 'train car / railway car' },
  { front: '🚋', back: 'tram / streetcar(side view)' },
  { front: '🚎', back: 'trolleybus' },
  { front: '🚞', back: 'mountain railway' },
  { front: '🚊', back: 'tram / streetcar' },
  { front: '🚉', back: 'train station' },
  { front: '🚍', back: 'bus' },
  { front: '🚔', back: 'police car' },
  { front: '🚘', back: 'car' },
  { front: '🚖', back: 'taxi' },
  { front: '🚆', back: 'train' },
  { front: '🚢', back: 'cargo ship / freighter' },
  { front: '🛳️', back: 'cruise ship / ocean liner' },
  { front: '🛥️', back: 'motorboat' },
  { front: '🚤', back: 'speedboat' },
  { front: '⛴️', back: 'ferry' },
  { front: '⛵', back: 'sailboat' },
  { front: '🛶', back: 'canoe' },
  { front: '🚟', back: 'suspended monorail' },
  { front: '🚠', back: 'gondola lift / ski lift' },
  { front: '🚡', back: 'cable car / aerial tramway' },
  { front: '🚁', back: 'helicopter' },
  { front: '🛸', back: 'UFO / flying saucer' },
  { front: '🚀', back: 'rocket' },
  { front: '✈️', back: 'airplane' },
  { front: '🛫', back: 'takeoff / departure' },
  { front: '🛬', back: 'landing / arrival' },
  { front: '🛩️', back: 'propeller plane' },
  { front: '🛝', back: 'playgroundslide' },
  { front: '🎢', back: 'roller coaster' },
  { front: '🎡', back: 'ferris wheel' },
  { front: '🎠', back: 'carousel' },
  { front: '🎪', back: 'circus tent' },
  { front: '🗼', back: 'Tokyo Tower' },
  { front: '🗽', back: 'Statue of Liberty' },
  { front: '🗿', back: 'moai' },
  { front: '🗻', back: 'Mount Fuji' },
  { front: '🏛️', back: 'museum' },
  { front: '💈', back: 'barber shop' },
  { front: '⛲', back: 'fountain' },
  { front: '⛩️', back: 'shinto Shrine' },
  { front: '🕍', back: 'synagogue' },
  { front: '🕌', back: 'mosque' },
  { front: '🕋', back: 'Kaaba' },
  { front: '🛕', back: 'Hindu temple' },
  { front: '⛪', back: 'church' },
  { front: '💒', back: 'wedding chapel' },
  { front: '🏯', back: 'Japanese castle' },
  { front: '🏰', back: 'castle' },
  { front: '🏗️', back: 'construction site' },
  { front: '🏢', back: 'office building' },
  { front: '🏭', back: 'factory' },
  { front: '🏬', back: 'department store' },
  { front: '🏪', back: 'convenience store' },
  { front: '🏟️', back: 'stadium' },
  { front: '🏦', back: 'bank' },
  { front: '🏫', back: 'school' },
  { front: '🏨', back: 'hotel' },
  { front: '🏣', back: 'Japanese post office' },
  { front: '🏤', back: 'post office' },
  { front: '🏥', back: 'hospital' },
  { front: '🏚️', back: 'abandoned house / derelict house' },
  { front: '🏠', back: 'house' },
  { front: '🏡', back: 'home / house with garden' },
  { front: '🏘️', back: 'houses' },
  { front: '🛖', back: 'hut' },
  { front: '⛺', back: 'tent' },
  { front: '🏕️', back: 'camping' },
  { front: '⛱️', back: 'beach umbrella' },
  { front: '🏙️', back: 'city skyline' },
  { front: '🌆', back: 'cityscape at dusk' },
  { front: '🌇', back: 'sunset' },
  { front: '🌃', back: 'night city' },
  { front: '🌉', back: 'bridge' },
  { front: '🌁', back: 'foggy city' },
  { front: '🛤️', back: 'train tracks / railway track' }, { front: '🛣️', back: 'highway / motorway / freeway' },
  { front: '🗾', back: 'map of japan' },
  { front: '🗺️', back: 'world map' },
  { front: '🌐', back: 'globe' },
  { front: '💺', back: 'seat' },
  { front: '🧳', back: 'suitcase / luggage / carry-on(small) / checked bag(big) / rolling suitcase/ trolley case' },

  // --- 道具・小物・その他 (Objects & Misc) ---
  { front: '🎉', back: 'party popper with confetti' },
  { front: '💍', back: 'ring' },
  { front: '🛡️', back: 'shield' },
  { front: '🗡️', back: 'dagger' },
  { front: '⚰️', back: 'coffin' },
  { front: '🪦', back: 'tombstone / headstone'
}, { front: '🗝️', back: 'antique key' },
  { front: '💻', back: 'laptop' },
  { front: '📱', back: 'cell phone / mobile phone' },
  { front: '📷', back: 'camera' },
  { front: '📚', back: 'books' },
  { front: '✏️', back: 'pencil' },
  { front: '🎨', back: 'palette / art set' },
  { front: '🎸', back: 'electric guitar' },
  { front: '⚽', back: 'soccer ball' },
  { front: '⏰', back: 'alarm clock' },
  { front: '🎁', back: 'gift' },
  { front: '🎈', back: 'balloon' },
  { front: '💡', back: 'lightbulb' },
  { front: '🔑', back: 'key' },
  { front: '🔒', back: 'padlock / lock' },
  { front: '🎀', back: 'ribbon' },
  { front: '🎇', back: 'sparkler' },
  { front: '🎆', back: 'fireworks' },
  { front: '🧨', back: 'firecracker' },
  { front: '🧧', back: 'hongbao / ang pao / lucky money ' }, { front: '🪔', back: 'diya / clay oil lamp' },
  { front: '🪅', back: 'piñata' },
  { front: '🪩', back: 'disco ball' },
  { front: '🎐', back: 'wind chime' },
  { front: '🎏', back: 'koinobori / carp flag' },
  { front: '🎎', back: 'hina dolls' },
  { front: '🎑', back: 'tsukimi / moon viewing' },
  { front: '🎍', back: 'kadomatsu' },
  { front: '🎋', back: 'tanabata tree / bamboo decoration' },
  { front: '🎄', back: 'Christmas tree' },
  { front: '🎃', back: 'jack-o'-lantern' },
  { front: '🎗️', back: 'awareness ribbon' },
  { front: '🥇', back: 'gold medal' },
  { front: '🥈', back: 'silver medal' },
  { front: '🥉', back: 'bronze medal' },
  { front: '🏅', back: 'medal' },
  { front: '🎖️', back: 'military medal' },
  { front: '🏆', back: 'trophy' },
  { front: '📢', back: 'megaphone' },
  { front: '⚾', back: 'baseball' },
  { front: '🥎', back: 'softball' },
  { front: '🏀', back: 'basketball' },
  { front: '🏐', back: 'volleyball' },
  { front: '🏈', back: '🇺🇸football / 🇬🇧American football' },
  { front: '🏉', back: 'rugby' },
  { front: '🥅', back: 'goal / net' },
  { front: '🎾', back: 'tennis' },
  { front: '🏸', back: 'badminton' },
  { front: '🥍', back: 'lacrosse' },
  { front: '🏏', back: 'cricket' },
  { front: '🏑', back: 'field hockey' },
  { front: '🏒', back: 'hockey' },
  { front: '🥌', back: 'curling stone' },
  { front: '🛷', back: '🇺🇸sled / 🇬🇧sledge' },
  { front: '🎿', back: 'skis' },
  { front: '⛸️', back: 'ice skates' },
  { front: '🛼', back: 'roller skates' },
  { front: '🩰', back: 'ballet slippers / pointe shoes' },
  { front: '🛹', back: 'skateboard' },
  { front: '⛳', back: 'golf hole' },
  { front: '🎯', back: 'target / bullseye' },
  { front: '🏹', back: 'bow and arrow' },
  { front: '🥏', back: 'frisbee' },
  { front: '🪃', back: 'boomerang' },
  { front: '🪁', back: 'kite' },
  { front: '🎣', back: 'fishing pole' },
  { front: '🤿', back: 'snorkel mask / snorkeling gear' },
  { front: '🩱', back: 'swimsuit' },
  { front: '🎽', back: '🇬🇧singlet  / 🇺🇸tank top' },
  { front: '🥋', back: 'martial arts uniform' },
  { front: '🥊', back: 'boxing gloves' },
  { front: '🎱', back: '8 ball / 🇺🇸pool / 🇬🇧billiards' },
  { front: '🏓', back: 'ping pong' },
  { front: '🎳', back: 'bowling' },
  { front: '♟️️', back: 'chess piece' },
  { front: '🪀', back: 'yo-yo' },
  { front: '🧩', back: 'puzzle piece' },
  { front: '🎮', back: 'game controller / video game' },
  { front: '🕹️', back: 'joystick' },
  { front: '🔫', back: 'water gun / water pistol' },
  { front: '🎲', back: 'dice' },
  { front: '🎰', back: 'slot machine' },
  { front: '🎴', back: 'hanafuda' },
  { front: '🀄', back: 'mahjong tile' },
  { front: '🃏', back: 'joker' },
  { front: '🪄', back: 'magic wand' },
  { front: '🎩', back: 'top hat' },
  { front: '📸', back: 'camera with flash / photo / snapshot' },
  { front: '🖼️', back: 'painting / framed picture' },
  { front: '🫟', back: 'paint tube' },
  { front: '🖌️', back: 'paintbrush' },
  { front: '🖍️', back: 'crayon' },
  { front: '🪡', back: 'sewing needle' },
  { front: '🧵', back: 'thread' },
  { front: '🧶', back: 'yarn' },
  { front: '🎹', back: 'keyboard' },
  { front: '🎷', back: 'saxophone' },
  { front: '🎺', back: 'trumpet' },
  { front: '🪊', back: 'trombone' },
  { front: '🪕', back: 'banjo' },
  { front: '🎻', back: 'violin' },
  { front: '🪉', back: 'harp' },
  { front: '🪘', back: 'hand drum' },
  { front: '🥁', back: 'snare drum' },
  { front: '🪇', back: 'maracas' },
  { front: '🪈', back: 'flute' },
  { front: '🪗', back: 'accordion' },
  { front: '🎤', back: 'microphone' },
  { front: '🎧', back: 'headphones' },
  { front: '🎚️', back: 'audio mixer slider / fader' },
  { front: '🎛️', back: 'control knobs / mixer knobs' },
  { front: '🎙️', back: 'studio mic / broadcast microphone' },
  { front: '📼', back: 'VHS tape / videocassette' },
  { front: '📻', back: 'radio' },
  { front: '📺', back: 'TV / television' },
  { front: '📹', back: 'video camera / camcorder' },
  { front: '📽️', back: 'film projector' },
  { front: '🎥', back: 'movie camera' },
  { front: '🎞️', back: 'film strip / film frames' },
  { front: '🎬', back: 'clapperboard / slate' },
  { front: '🎭', back: 'performing arts / drama masks' },
  { front: '🎫', back: 'admission ticket' },
  { front: '🎟️', back: 'admissiontickets' },
  { front: '☎️', back: 'landline / home phone' },
  { front: '📞', back: 'handset / receiver' },
  { front: '📟', back: 'pager' },
  { front: '📠', back: 'fax machine' },
  { front: '🔌', back: 'electric plug / power cord if cable included' },
  { front: '🔋', back: 'battery' },
  { front: '🪫', back: 'low battery' },
  { front: '🖲️', back: 'trackball' },
  { front: '💽', back: 'minidisc' },
  { front: '💾', back: 'floppy disk' },
  { front: '💿', back: 'CD' },
  { front: '📀', back: 'DVD' },
  { front: '🖥️', back: 'desktop computer' },
  { front: '⌨️', back: 'computer keyboard' },
  { front: '🖨️', back: 'printer' },
  { front: '🖱️', back: 'mouse' },
  { front: '🪎', back: 'treasure chest' },
  { front: '🪙', back: 'coin' },
  { front: '💸', back: 'spending money / money flying away' },
  { front: '💵', back: 'dollar bill' },
  { front: '💴', back: 'yen bill' },
  { front: '💶', back: 'euro bill' },
  { front: '💷', back: 'banknote' },
  { front: '💳', back: 'credit card' },
  { front: '💰', back: 'money bag' },
  { front: '🧾', back: 'receipt' },
  { front: '🧮', back: 'abacus' },
  { front: '⚖️', back: 'scales' },
  { front: '🛒', back: '🇺🇸shopping cart / 🇬🇧shopping trolley' },
  { front: '🛍️', back: 'shopping bags' },
  { front: '🕯️', back: 'candle' },
  { front: '🔦', back: '🇺🇸flashlight / 🇬🇧torch' },
  { front: '🏮', back: 'lantern' },
  { front: '🧱', back: 'brick' },
  { front: '🪟', back: 'window' },
  { front: '🪞', back: 'mirror' },
  { front: '🚪', back: 'door' },
  { front: '🪑', back: 'chair' },
  { front: '🛏️', back: 'bed' },
  { front: '🛋️', back: '🇺🇸couch / 🇬🇧sofa' },
  { front: '🚿', back: 'shower head' },
  { front: '🛁', back: 'bathtub / 🇬🇧bath / tub' },
  { front: '🚽', back: 'toilet' },
  { front: '🧻', back: '🇺🇸toilet pap / 🇬🇧toilet roller' },
  { front: '🪠', back: 'plunger' },
  { front: '🪆', back: 'matryoshka / Russian doll' },
  { front: '🧷', back: 'safety pin' },
  { front: '🪢', back: 'knot' },
  { front: '🧹', back: 'broom' },
  { front: '🧴', back: 'bottle' },
  { front: '🧽', back: 'sponge' },
  { front: '🧼', back: 'soap' },
  { front: '🪥', back: 'toothbrush' },
  { front: '🪒', back: 'razor' },
  { front: '🪮', back: 'comb' },
  { front: '🧺', back: 'basket' },
  { front: '🧦', back: 'socks' },
  { front: '🧤', back: 'gloves' },
  { front: '🧣', back: 'scarf' },
  { front: '👖', back: 'jeans' },
  { front: '👕', back: 't-shirt' },
  { front: '👚', back: 'blouse' },
  { front: '👔', back: 'tie' },
  { front: '👗', back: 'dress' },
  { front: '👘', back: 'kimono' },
  { front: '🥻', back: 'sari' },
  { front: '👙', back: 'bikini' },
  { front: '🩳', back: 'shorts' },
  { front: '🩲', back: 'briefs' },
  { front: '🧥', back: 'coat' },
  { front: '🥼', back: 'lab coat' },
  { front: '🦺', back: 'safety vest' },
  { front: '⛑️', back: 'hard hat' },
  { front: '🪖', back: 'helmet' },
  { front: '🎓', back: 'graduation cap' },
  { front: '👒', back: 'sun hat' },
  { front: '🧢', back: 'cap' },
  { front: '👑', back: 'crown' },
  { front: '💄', back: 'lipstick' },
  { front: '🪭', back: 'hand fan' },
  { front: '🎒', back: 'backpack' },
  { front: '👝', back: 'clutch' },
  { front: '👛', back: 'purse' },
  { front: '👜', back: 'handbag' },
  { front: '💼', back: 'briefcase' },
  { front: '☂️', back: 'umbrella' },
  { front: '🌂', back: 'closed umbrella' },
  { front: '🥾', back: 'hiking boot' },
  { front: '👢', back: 'boot' },
  { front: '👠', back: 'high heel' },
  { front: '🩴', back: 'flip-flop' },
  { front: '👟', back: 'sneaker' },
  { front: '👞', back: 'shoe' },
  { front: '🥿', back: 'flat shoe' },
  { front: '👡', back: 'sandal' },
  { front: '🦯', back: 'cane' },
  { front: '👓', back: 'glasses' },
  { front: '🥽', back: 'goggles' },
  { front: '⚗️', back: 'alembic' },
  { front: '🧫', back: 'petri dish' },
  { front: '🧪', back: 'test tube' },
  { front: '💉', back: 'syringe' },
  { front: '💊', back: 'pill' },
  { front: '🩹', back: 'bandaid' },
  { front: '🩺', back: 'stethoscope' },
  { front: '🩻', back: 'x-ray' },
  { front: '🧬', back: 'dna' },
  { front: '🔭', back: 'telescope' },
  { front: '🔬', back: 'microscope' },
  { front: '📡', back: 'satellite dish' },
  { front: '🛰️', back: 'satellite' },
  { front: '🧯', back: 'fire extinguisher' },
  { front: '🪓', back: 'axe' },
  { front: '🪜', back: 'ladder' },
  { front: '🪣', back: 'bucket' },
  { front: '🪝', back: 'hook' },
  { front: '🧲', back: 'magnet' },
  { front: '🧰', back: 'toolbox' },
  { front: '🗜️', back: 'clamp' },
  { front: '🔩', back: 'nut and bolt' },
  { front: '🪛', back: 'screwdriver' },
  { front: '🪚', back: 'saw' },
  { front: '🔧', back: 'wrench' },
  { front: '🔨', back: 'hammer' },
  { front: '🛠️', back: 'tools' },
  { front: '⚒️', back: 'hammer and pick' },
  { front: '⛏️', back: 'pickaxe' },
  { front: '🪏', back: 'shovel' },
  { front: '⚙️', back: 'gear' },
  { front: '⛓️‍💥', back: 'broken chain' },
  { front: '🔗', back: 'link' },
  { front: '⛓️', back: 'chains' },
  { front: '📎', back: 'paperclip' },
  { front: '🖇️', back: 'paperclips' },
  { front: '✂️', back: 'scissors' },
  { front: '📏', back: 'ruler' },
  { front: '📐', back: 'triangle ruler' },
  { front: '🖊️', back: 'pen' },
  { front: '🖋️', back: 'fountain pen' },
  { front: '✒️', back: 'nib' },
  { front: '📝', back: 'memo' },
  { front: '🗒️', back: 'notepad' },
  { front: '📄', back: 'page' },
  { front: '📃', back: 'page with curl' },
  { front: '📑', back: 'bookmarks' },
  { front: '📋', back: 'clipboard' },
  { front: '🗃️', back: 'card box' },
  { front: '🗄️', back: 'filing cabinet' },
  { front: '📒', back: 'ledger' },
  { front: '📔', back: 'notebook' },
  { front: '📕', back: 'book' },
  { front: '📓', back: 'notebook' },
  { front: '📗', back: 'book' },
  { front: '📘', back: 'book' },
  { front: '📙', back: 'book' },
  { front: '📖', back: 'open book' },
  { front: '🔖', back: 'bookmark' },
  { front: '📂', back: 'open folder' },
  { front: '📁', back: 'folder' },
  { front: '🗂️', back: 'dividers' },
  { front: '📊', back: 'bar chart' },
  { front: '📈', back: 'chart up' },
  { front: '📉', back: 'chart down' },
  { front: '📇', back: 'card index' },
  { front: '🪪', back: 'id card' },
  { front: '📌', back: 'pushpin' },
  { front: '📍', back: 'pin' },
  { front: '🗑️', back: 'trash can' },
  { front: '📰', back: 'newspaper' },
  { front: '🗞️', back: 'rolled newspaper' },
  { front: '🏷️', back: 'tag' },
  { front: '📤', back: 'outbox' },
  { front: '📥', back: 'inbox' },
  { front: '📩', back: 'incoming mail' },
  { front: '📨', back: 'incoming mail' },
  { front: '✉️', back: 'envelope' },
  { front: '📧', back: 'email' },
  { front: '📫', back: 'mailbox' },
  { front: '📪', back: 'mailbox' },
  { front: '📬', back: 'mailbox' },
  { front: '📭', back: 'mailbox' },
  { front: '📦', back: 'package' },
  { front: '📯', back: 'postal horn' },
  { front: '📮', back: 'mailbox' },
  { front: '🗳️', back: 'ballot box' },
  { front: '📅', back: 'calendar' },
  { front: '📆', back: 'calendar' },
  { front: '🗓️', back: 'calendar' },
  { front: '🪧', back: 'placard' },
  { front: '🕰️', back: 'mantelpiece clock' },
  { front: '⌛', back: 'hourglass' },
  { front: '⏳', back: 'hourglass' },
  { front: '⏲️', back: 'timer' },
  { front: '⌚', back: 'watch' },
  { front: '⏱️', back: 'stopwatch' },
  { front: '🕛', back: '12:00' },
  { front: '🕧', back: '12:30' },
  { front: '🕐', back: '1:00' },
  { front: '🕜', back: '1:30' },
  { front: '🕑', back: '2:00' },
  { front: '🕝', back: '2:30' },
  { front: '🕒', back: '3:00' },
  { front: '🕞', back: '3:30' },
  { front: '🕓', back: '4:00' },
  { front: '🕟', back: '4:30' },
  { front: '🕔', back: '5:00' },
  { front: '🕠', back: '5:30' },
  { front: '🕕', back: '6:00' },
  { front: '🕡', back: '6:30' },
  { front: '🕖', back: '7:00' },
  { front: '🕢', back: '7:30' },
  { front: '🕗', back: '8:00' },
  { front: '🕣', back: '8:30' },
  { front: '🕘', back: '9:00' },
  { front: '🕤', back: '9:30' },
  { front: '🕙', back: '10:00' },
  { front: '🕥', back: '10:30' },
  { front: '🕚', back: '11:00' },
  { front: '🕦', back: '11:30' },
  { front: '🛎️', back: 'service bell' },
  { front: '🔔', back: 'bell' },
  { front: '🔈', back: 'muted speaker' },
  { front: '🔉', back: 'speaker' },
  { front: '🔊', back: 'speaker' },
  { front: '📣', back: 'megaphone' },
  { front: '🔍', back: 'magnifying glass' },
  { front: '🔎', back: 'magnifying glass' },
  { front: '🔮', back: 'crystal ball' },
  { front: '🧿', back: 'evil eye' },
  { front: '🪬', back: 'hamsa' },
  { front: '📿', back: 'prayer beads' },
  { front: '🏺', back: 'amphora' },
  { front: '⚱️', back: 'urn' },
  { front: '🚬', back: 'cigarette' },
  { front: '💣', back: 'bomb' },
  { front: '🪤', back: 'mousetrap' },
  { front: '📜', back: 'scroll' },
  { front: '⚔️', back: 'swords' },
  { front: '🔏', back: 'locked with pen' },
  { front: '🔓', back: 'unlocked' },

  // --- 職業・人物 (Professions & People) ---
  { front: '👩🏻‍🎨', back: 'artist' },
  { front: '👩🏻‍🍳', back: 'chef' },
  { front: '👩🏻‍🚒', back: 'firefighter' },
  { front: '👩🏻‍🌾', back: 'farmer' },
  { front: '👩🏻‍✈️', back: 'pilot' },
  { front: '👩🏻‍🎓', back: 'student' },
  { front: '👩🏻‍🎤', back: 'singer' },
  { front: '👩🏻‍⚖️', back: 'judge' },
  { front: '🙇🏻‍♀️', back: 'bowing' },
  { front: '🙋🏻‍♀️', back: 'raising hand' },
  { front: '💁🏻‍♀️', back: 'information desk' },
  { front: '🙆🏻‍♀️', back: 'ok gesture' },
  { front: '🙅🏻‍♀️', back: 'no gesture' },
  { front: '🤷🏻‍♀️', back: 'shrugging' },
  { front: '🤦🏻‍♀️', back: 'facepalm' },
  { front: '🙍🏻‍♀️', back: 'frowning' },
  { front: '🙎🏻‍♀️', back: 'pouting' },
  { front: '🧏🏻‍♀️', back: 'deaf' },
  { front: '💆🏻‍♀️', back: 'massage' },
  { front: '💇🏻‍♀️', back: 'haircut' },
  { front: '🧖🏻‍♀️', back: 'sauna' },
  { front: '🛀🏻', back: 'bath' },
  { front: '🛌🏻', back: 'sleeping in bed' },
  { front: '🧘🏻‍♀️', back: 'meditating' },
  { front: '🧍🏻‍♀️', back: 'standing' },
  { front: '🤸🏻‍♀️', back: 'cartwheel' },
  { front: '🧎🏻‍♀️', back: 'kneeling' },
  { front: '👩🏻‍🦼', back: 'wheelchair' },
  { front: '👩🏻‍🦽', back: 'wheelchair' },
  { front: '👩🏻‍🦯', back: 'cane' },
  { front: '🚶🏻‍♀️', back: 'walking' },
  { front: '🏃🏻‍♀️', back: 'running' },
  { front: '⛹🏻‍♀️', back: 'dribbling' },
  { front: '🤾🏻‍♀️', back: 'handball' },
  { front: '🚴🏻‍♀️', back: 'biking' },
  { front: '🚵🏻‍♀️', back: 'mountain biking' },
  { front: '🧗🏻‍♀️', back: 'climbing' },
  { front: '🏋🏻‍♀️', back: 'weightlifting' },
  { front: '🤼', back: 'wrestling' },
  { front: '🤼‍♂️', back: 'wrestling' },
  { front: '🤼‍♀️', back: 'wrestling' },
  { front: '🤹🏻‍♀️', back: 'juggling' },
  { front: '🏌🏻‍♀️', back: 'golfing' },
  { front: '🏇🏻', back: 'horse racing' },
  { front: '🤺', back: 'fencing' },
  { front: '🏂🏻', back: 'snowboarding' },
  { front: '🪂', back: 'skydiving' },
  { front: '🏄🏻‍♀️', back: 'surfing' },
  { front: '🚣🏻‍♀️', back: 'rowing' },
  { front: '🏊🏻‍♀️', back: 'swimming' },
  { front: '🤽🏻‍♀️', back: 'water polo' },
  { front: '🧜🏻‍♀️', back: 'mermaid' },
  { front: '🧚🏻‍♀️', back: 'fairy' },
  { front: '🧞‍♀️', back: 'genie' },
  { front: '🧝🏻‍♀️', back: 'elf' },
  { front: '🧙🏻‍♀️', back: 'witch' },
  { front: '🧛🏻‍♀️', back: 'vampire' },
  { front: '🧟‍♀️', back: 'zombie' },
  { front: '🧌', back: 'troll' },
  { front: '🫈', back: 'person with crown' },
  { front: '🦸🏻‍♀️', back: 'superhero' },
  { front: '🦹🏻‍♀️', back: 'supervillain' },
  { front: '🤶🏻', back: 'mrs claus' },
  { front: '🥷🏻', back: 'ninja' },
  { front: '💂🏻‍♀️', back: 'guard' },
  { front: '👸🏻', back: 'princess' },
  { front: '🤵🏻‍♀️', back: 'tuxedo' },
  { front: '👰🏻‍♀️️', back: 'bride' },
  { front: '👩🏻‍🚀', back: 'astronaut' },
  { front: '👷🏻‍♀️', back: 'construction worker' },
  { front: '👮🏻‍♀️', back: 'police officer' },
  { front: '🕵🏻‍♀️', back: 'detective' },
  { front: '👩🏻‍🔬', back: 'scientist' },
  { front: '👩🏻‍⚕️', back: 'medic' },
  { front: '👩🏻‍🔧', back: 'mechanic' },
  { front: '👩🏻‍🏭', back: 'factory worker' },
  { front: '👩🏻‍🏫', back: 'teacher' },
  { front: '👩🏻‍💼', back: 'office worker' },
  { front: '👩🏻‍💻', back: 'coder' },
  { front: '👳🏻‍♀️', back: 'turban' },
  { front: '🧕🏻', back: 'headscarf' },
  { front: '👲🏻', back: 'skullcap' },
  { front: '👼🏻', back: 'angel' },
  { front: '👶🏻', back: 'baby' },
  { front: '👧🏻', back: 'girl' },
  { front: '👩🏻', back: 'woman' },
  { front: '👵🏻', back: 'elderly woman' },
  { front: '👩🏻‍‍🦳', back: 'white hair' },
  { front: '👩🏻‍🦰', back: 'red hair' },
  { front: '👱🏻‍♀️', back: 'blonde' },
  { front: '👩🏻‍🦱', back: 'curly hair' },
  { front: '👩🏻‍‍🦲', back: 'bald' },
  { front: '🧔🏻‍♀️', back: 'beard' },
  { front: '🕴🏻', back: 'levitating' },
  { front: '🧑🏻‍🩰', back: 'ballet dancer' },
  { front: '💃🏻', back: 'dancer' },
  { front: '🕺🏻', back: 'dancer' },
  { front: '👯', back: 'bunny ears' },
  { front: '🤰🏻', back: 'pregnant' },
  { front: '🤱🏻', back: 'breastfeeding' },
  { front: '👩🏻‍‍🍼', back: 'feeding baby' },

  // --- 記号・シンボル・アイコン (Symbols & Signs & Icons) ---
  { front: '🔴', back: 'red circle' },
  { front: '🟠', back: 'orange circle' },
  { front: '🟡', back: 'yellow circle' },
  { front: '🟢', back: 'green circle' },
  { front: '🔵', back: 'blue circle' },
  { front: '🟣', back: 'purple circle' },
  { front: '🟤', back: 'brown circle' },
  { front: '⚫', back: 'black circle' },
  { front: '⚪', back: 'white circle' },
  { front: '🟥', back: 'red square' },
  { front: '🟧', back: 'orange square' },
  { front: '🟨', back: 'yellow square' },
  { front: '🟩', back: 'green square' },
  { front: '🟦', back: 'blue square' },
  { front: '🟪', back: 'purple square' },
  { front: '🟫', back: 'brown square' },
  { front: '⬛', back: 'black square' },
  { front: '⬜', back: 'white square' },
  { front: '♦️', back: 'diamonds' },
  { front: '♣️', back: 'clubs' },
  { front: '♠️', back: 'spades' },
  { front: '♈', back: 'aries' },
  { front: '♉', back: 'taurus' },
  { front: '♊', back: 'gemini' },
  { front: '♋', back: 'cancer' },
  { front: '♌', back: 'leo' },
  { front: '♍', back: 'virgo' },
  { front: '♎', back: 'libra' },
  { front: '♏', back: 'scorpio' },
  { front: '♐', back: 'sagittarius' },
  { front: '♑', back: 'capricorn' },
  { front: '♒', back: 'aquarius' },
  { front: '♓', back: 'pisces' },
  { front: '⛎', back: 'ophiuchus' },
  { front: '♀️', back: 'female' },
  { front: '♂️', back: 'male' },
  { front: '⚧️️', back: 'transgender' },
  { front: '💭', back: 'thought bubble' },
  { front: '🗯️', back: 'anger bubble' },
  { front: '💬', back: 'speech bubble' },
  { front: '🗨️', back: 'speech bubble' },
  { front: '❕', back: 'exclamation' },
  { front: '❔', back: 'question mark' },
  { front: '❗', back: 'exclamation' },
  { front: '❓', back: 'question' },
  { front: '⁉️', back: 'interrobang' },
  { front: '‼️', back: 'double exclamation' },
  { front: '❌', back: 'cross' },
  { front: '🚫', back: 'prohibited' },
  { front: '🚳', back: 'no bikes' },
  { front: '🚭', back: 'no smoking' },
  { front: '🚯', back: 'no littering' },
  { front: '🚱', back: 'non-potable water' },
  { front: '🚷', back: 'no pedestrians' },
  { front: '📵', back: 'no phones' },
  { front: '🔞', back: '18 plus' },
  { front: '🔕', back: 'notifications off' },
  { front: '🔇', back: 'muted' },
  { front: '🅰️', back: 'a button' },
  { front: '🆎', back: 'ab button' },
  { front: '🅱️', back: 'b button' },
  { front: '🅾️', back: 'o button' },
  { front: '🆑', back: 'cl button' },
  { front: '🆘', back: 'sos' },
  { front: '⛔', back: 'no entry' },
  { front: '📛', back: 'name badge' },
  { front: '♨️', back: 'hot springs' },
  { front: '🔻', back: 'red triangle down' },
  { front: '🔺', back: 'red triangle up' },
  { front: '🉐', back: 'bargain' },
  { front: '✴️', back: 'eight-pointed star' },
  { front: '🔶', back: 'orange diamond' },
  { front: '🔸', back: 'small orange diamond' },
  { front: '🔆', back: 'high brightness' },
  { front: '🔅', back: 'low brightness' },
  { front: '🆚', back: 'vs' },
  { front: '🎦', back: 'cinema' },
  { front: '📶', back: 'signal' },
  { front: '🔁', back: 'repeat' },
  { front: '🔂', back: 'repeat one' },
  { front: '🔀', back: 'shuffle' },
  { front: '▶️', back: 'play' },
  { front: '⏩', back: 'fast forward' },
  { front: '⏭️', back: 'next track' },
  { front: '⏯️', back: 'play pause' },
  { front: '◀️', back: 'reverse' },
  { front: '⏪', back: 'fast rewind' },
  { front: '⏮️', back: 'previous track' },
  { front: '🔼', back: 'up button' },
  { front: '⏫', back: 'fast up' },
  { front: '🔽', back: 'down button' },
  { front: '⏬', back: 'fast down' },
  { front: '⏸️', back: 'pause' },
  { front: '⏹️', back: 'stop' },
  { front: '⏺️', back: 'record' },
  { front: '⏏️', back: 'eject' },
  { front: '📴', back: 'phone off' },
  { front: '🛜', back: 'wifi' },
  { front: '📳', back: 'vibrate' },
  { front: '📲', back: 'phone with arrow' },
  { front: '☢️', back: 'radioactive' },
  { front: '☣️', back: 'biohazard' },
  { front: '⚠️', back: 'warning' },
  { front: '🚸', back: 'children crossing' },
  { front: '⚜️', back: 'fleur-de-lis' },
  { front: '🔱', back: 'trident' },
  { front: '〽️', back: 'part alternation' },
  { front: '🔰', back: 'beginner' },
  { front: '✳️', back: 'asterisk' },
  { front: '❇️', back: 'sparkle' },
  { front: '♻️', back: 'recycle' },
  { front: '💱', back: 'currency exchange' },
  { front: '💲', back: 'dollar sign' },
  { front: '💹', back: 'chart up yen' },
  { front: '❎', back: 'cross mark' },
  { front: '✅', back: 'check mark' },
  { front: '✔️️', back: 'check mark' },
  { front: '☑️', back: 'checkbox' },
  { front: '⬆️', back: 'up arrow' },
  { front: '↗️', back: 'up-right arrow' },
  { front: '➡️', back: 'right arrow' },
  { front: '↘️', back: 'down-right arrow' },
  { front: '⬇️', back: 'down arrow' },
  { front: '↙️', back: 'down-left arrow' },
  { front: '⬅️', back: 'left arrow' },
  { front: '↖️', back: 'up-left arrow' },
  { front: '↕️', back: 'up-down arrow' },
  { front: '↔️', back: 'left-right arrow' },
  { front: '↩️', back: 'curved arrow' },
  { front: '↪️', back: 'curved arrow' },
  { front: '⤴️', back: 'curved arrow' },
  { front: '⤵️', back: 'curved arrow' },
  { front: '🔃', back: 'clockwise arrows' },
  { front: '🔄', back: 'counterclockwise arrows' },
  { front: '🔙', back: 'back' },
  { front: '🔛', back: 'on' },
  { front: 'TOP', back: 'top' },
  { front: '🔚', back: 'end' },
  { front: '🔜', back: 'soon' },
  { front: '🆕', back: 'new' },
  { front: '🆓', back: 'free' },
  { front: '🆙', back: 'up' },
  { front: '🆗', back: 'ok' },
  { front: '🆒', back: 'cool' },
  { front: '🆖', back: 'ng' },
  { front: 'ℹ️', back: 'info' },
  { front: '🅿️', back: 'parking' },
  { front: '🔣', back: 'symbols' },
  { front: '🔤', back: 'letters' },
  { front: '🔢', back: 'numbers' },
  { front: '#️⃣', back: 'hashtag' },
  { front: '*️⃣', back: 'asterisk' },
  { front: '0️⃣', back: '0' },
  { front: '1️⃣', back: '1' },
  { front: '2️⃣', back: '2' },
  { front: '3️⃣', back: '3' },
  { front: '4️⃣', back: '4' },
  { front: '5️⃣', back: '5' },
  { front: '6️⃣', back: '6' },
  { front: '7️⃣', back: '7' },
  { front: '8️⃣', back: '8' },
  { front: '9️⃣', back: '9' },
  { front: '🔟', back: '10' },
  { front: '💠', back: 'diamond' },
  { front: '🔷', back: 'blue diamond' },
  { front: '🔹', back: 'small blue diamond' },
  { front: '🏧', back: 'atm' },
  { front: 'Ⓜ️', back: 'metro' },
  { front: '🚾', back: 'restroom' },
  { front: '🚻', back: 'restroom' },
  { front: '🚹', back: 'mens' },
  { front: '🚺', back: 'womens' },
  { front: '♿', back: 'wheelchair' },
  { front: '🚼', back: 'baby change' },
  { front: '🛗', back: 'elevator' },
  { front: '🚮', back: 'litter bin' },
  { front: '🚰', back: 'drinking water' },
  { front: '🛂', back: 'passport control' },
  { front: '🛃', back: 'customs' },
  { front: '🛄', back: 'baggage claim' },
  { front: '🛅', back: 'luggage storage' },
  { front: '⚕️', back: 'medical symbol' },
  { front: '⚛️', back: 'atom' },
  { front: '🛐', back: 'place of worship' },
  { front: '🕉️', back: 'om' },
  { front: '☸️', back: 'dharma wheel' },
  { front: '☮️', back: 'peace' },
  { front: '☯️', back: 'yin yang' },
  { front: '☪️', back: 'star and crescent' },
  { front: '🪯', back: 'khanda' },
  { front: '✝️️', back: 'cross' },
  { front: '☦️', back: 'orthodox cross' },
  { front: '✡️', back: 'star of david' },
  { front: '🔯', back: 'hexagram' },
  { front: '🕎', back: 'menorah' },
  { front: '♾️', back: 'infinity' }
];