  window.English=[
// --- 乗り物・旅行 (Vehicles & Travel) ---
  { front: '🛑', back: 'stop sign' },
  { front: '🚧', back: 'barricade / Type III barricade / road barrier' },
  { front: '🚨', back: 'emergency light / strobe light / siren / emergency vehicle light' },
  { front: '⛽', back: 'gas pump / fuel pump' },
  { front: '🛢️', back: 'oil drum / steel drum / barrel' },
  { front: '🧭', back: 'compass' },
  { front: '🛞', back: 'wheel' },
  { front: '🛟', back: 'life ring / life preserver / lifebuoy ' },
  { front: '⚓', back: 'anchor' },
  { front: '🚏', back: 'bus stop' },
  { front: '🚇', back: 'subway / metro' },
  { front: '🚥', back: 'horizontal traffic light' },
  { front: '🚦', back: 'vertical traffic light' },
  { front: '🛴', back: 'scooter' },
  { front: '🦽', back: 'wheelchair / push wheelchair' },
  { front: '🦼', back: 'electric wheelchair / power chair' },
  { front: '🩼', back: 'crutch' },
  { front: '🚲', back: 'bike' },
  { front: '🛵', back: 'moped / motor scooter' },
  { front: '🏍️️', back: 'motorcycle' },
  { front: '🚙', back: 'SUV(sport utility vehicle)' },
  { front: '🚗', back: 'car' },
  { front: '🛻', back: 'pickup truck' },
  { front: '🚐', back: 'van' },
  { front: '🚚', back: 'box truck / delivery truck' },
  { front: '🚛', back: 'artic / articulated lorry / Semi-truck / Semi / Tractor-trailer' },
  { front: '🚜', back: 'tractor' },
  { front: '🏎️', back: 'race car' },
  { front: '🚒', back: 'firetruck' },
  { front: '🚑', back: 'ambulance' },
  { front: '🚓', back: 'police car' },
  { front: '🚕', back: 'taxi' },
  { front: '🛺', back: 'tuk-tuk / auto rickshaw' },
  { front: '🚌', back: 'bus' },
  { front: '🚈', back: 'tram / light rail / streetcar' },
  { front: '🚝', back: 'monorail' },
  { front: '🚅', back: 'bullet train' },
  { front: '🚄', back: 'high speed train' },
  { front: '🚂', back: 'steam locomotive' }, { front: '🚃', back: 'train car / railway car' },
  { front: '🚋', back: 'tram / streetcar(side view)' },
  { front: '🚎', back: 'trolleybus' },
  { front: '🚞', back: 'mountain railway' },
  { front: '🚊', back: 'tram / streetcar' },
  { front: '🚉', back: 'train station' },
  { front: '🚍', back: 'bus' },
  { front: '🚔', back: 'police car' },
  { front: '🚘', back: 'car' },
  { front: '🚖', back: 'taxi' },
  { front: '🚆', back: 'train' },
  { front: '🚢', back: 'cargo ship / freighter' },
  { front: '🛳️', back: 'cruise ship / ocean liner' },
  { front: '🛥️', back: 'motorboat' },
  { front: '🚤', back: 'speedboat' },
  { front: '⛴️', back: 'ferry' },
  { front: '⛵', back: 'sailboat' },
  { front: '🛶', back: 'canoe' },
  { front: '🚟', back: 'suspended monorail' },
  { front: '🚠', back: 'gondola lift / ski lift' },
  { front: '🚡', back: 'cable car / aerial tramway' },
  { front: '🚁', back: 'helicopter' },
  { front: '🛸', back: 'UFO / flying saucer' },
  { front: '🚀', back: 'rocket' },
  { front: '✈️', back: 'airplane' },
  { front: '🛫', back: 'takeoff / departure' },
  { front: '🛬', back: 'landing / arrival' },
  { front: '🛩️', back: 'propeller plane' },
  { front: '🛝', back: 'playgroundslide' },
  { front: '🎢', back: 'roller coaster' },
  { front: '🎡', back: 'ferris wheel' },
  { front: '🎠', back: 'carousel' },
  { front: '🎪', back: 'circus tent' },
  { front: '🗼', back: 'Tokyo Tower' },
  { front: '🗽', back: 'Statue of Liberty' },
  { front: '🗿', back: 'moai' },
  { front: '🗻', back: 'Mount Fuji' },
  { front: '🏛️', back: 'museum' },
  { front: '💈', back: 'barber shop' },
  { front: '⛲', back: 'fountain' },
  { front: '⛩️', back: 'shinto Shrine' },
  { front: '🕍', back: 'synagogue' },
  { front: '🕌', back: 'mosque' },
  { front: '🕋', back: 'Kaaba' },
  { front: '🛕', back: 'Hindu temple' },
  { front: '⛪', back: 'church' },
  { front: '💒', back: 'wedding chapel' },
  { front: '🏯', back: 'Japanese castle' },
  { front: '🏰', back: 'castle' },
  { front: '🏗️', back: 'construction site' },
  { front: '🏢', back: 'office building' },
  { front: '🏭', back: 'factory' },
  { front: '🏬', back: 'department store' },
  { front: '🏪', back: 'convenience store' },
  { front: '🏟️', back: 'stadium' },
  { front: '🏦', back: 'bank' },
  { front: '🏫', back: 'school' },
  { front: '🏨', back: 'hotel' },
  { front: '🏣', back: 'Japanese post office' },
  { front: '🏤', back: 'post office' },
  { front: '🏥', back: 'hospital' },
  { front: '🏚️', back: 'abandoned house / derelict house' },
  { front: '🏠', back: 'house' },
  { front: '🏡', back: 'home / house with garden' },
  { front: '🏘️', back: 'houses' },
  { front: '🛖', back: 'hut' },
  { front: '⛺', back: 'tent' },
  { front: '🏕️', back: 'camping' },
  { front: '⛱️', back: 'beach umbrella' },
  { front: '🏙️', back: 'city skyline' },
  { front: '🌆', back: 'cityscape at dusk' },
  { front: '🌇', back: 'sunset' },
  { front: '🌃', back: 'night city' },
  { front: '🌉', back: 'bridge' },
  { front: '🌁', back: 'foggy city' },
  { front: '🛤️', back: 'train tracks / railway track' }, { front: '🛣️', back: 'highway / motorway / freeway' },
  { front: '🗾', back: 'map of japan' },
  { front: '🗺️', back: 'world map' },
  { front: '🌐', back: 'globe' },
  { front: '💺', back: 'seat' },
  { front: '🧳', back: 'suitcase / luggage / carry-on(small) / checked bag(big) / rolling suitcase/ trolley case' },

  // --- 道具・小物・その他 (Objects & Misc) ---
  { front: '🎉', back: 'party popper with confetti' },
  { front: '💍', back: 'ring' },
  { front: '🛡️', back: 'shield' },
  { front: '🗡️', back: 'dagger' },
  { front: '⚰️', back: 'coffin' },
  { front: '🪦', back: 'tombstone / headstone'
}, { front: '🗝️', back: 'antique key' },
  { front: '💻', back: 'laptop' },
  { front: '📱', back: 'cell phone / mobile phone' },
  { front: '📷', back: 'camera' },
  { front: '📚', back: 'books' },
  { front: '✏️', back: 'pencil' },
  { front: '🎨', back: 'palette / art set' },
  { front: '🎸', back: 'electric guitar' },
  { front: '⚽', back: 'soccer ball' },
  { front: '⏰', back: 'alarm clock' },
  { front: '🎁', back: 'gift' },
  { front: '🎈', back: 'balloon' },
  { front: '💡', back: 'lightbulb' },
  { front: '🔑', back: 'key' },
  { front: '🔒', back: 'padlock / lock' },
  { front: '🎀', back: 'ribbon' },
  { front: '🎇', back: 'sparkler' },
  { front: '🎆', back: 'fireworks' },
  { front: '🧨', back: 'firecracker' },
  { front: '🧧', back: 'hongbao / ang pao / lucky money ' }, { front: '🪔', back: 'diya / clay oil lamp' },
  { front: '🪅', back: 'piñata' },
  { front: '🪩', back: 'disco ball' },
  { front: '🎐', back: 'wind chime' },
  { front: '🎏', back: 'koinobori / carp flag' },
  { front: '🎎', back: 'hina dolls' },
  { front: '🎑', back: 'tsukimi / moon viewing' },
  { front: '🎍', back: 'kadomatsu' },
  { front: '🎋', back: 'tanabata tree / bamboo decoration' },
  { front: '🎄', back: 'Christmas tree' },
  { front: '🎃', back: 'jack-o'-lantern' },
  { front: '🎗️', back: 'awareness ribbon' },
  { front: '🥇', back: 'gold medal' },
  { front: '🥈', back: 'silver medal' },
  { front: '🥉', back: 'bronze medal' },
  { front: '🏅', back: 'medal' },
  { front: '🎖️', back: 'military medal' },
  { front: '🏆', back: 'trophy' },
  { front: '📢', back: 'megaphone' },
  { front: '⚾', back: 'baseball' },
  { front: '🥎', back: 'softball' },
  { front: '🏀', back: 'basketball' },
  { front: '🏐', back: 'volleyball' },
  { front: '🏈', back: '🇺🇸football / 🇬🇧American football' },
  { front: '🏉', back: 'rugby' },
  { front: '🥅', back: 'goal / net' },
  { front: '🎾', back: 'tennis' },
  { front: '🏸', back: 'badminton' },
  { front: '🥍', back: 'lacrosse' },
  { front: '🏏', back: 'cricket' },
  { front: '🏑', back: 'field hockey' },
  { front: '🏒', back: 'hockey' },
  { front: '🥌', back: 'curling stone' },
  { front: '🛷', back: '🇺🇸sled / 🇬🇧sledge' },
  { front: '🎿', back: 'skis' },
  { front: '⛸️', back: 'ice skates' },
  { front: '🛼', back: 'roller skates' },
  { front: '🩰', back: 'ballet slippers / pointe shoes' },
  { front: '🛹', back: 'skateboard' },
  { front: '⛳', back: 'golf hole' },
  { front: '🎯', back: 'target / bullseye' },
  { front: '🏹', back: 'bow and arrow' },
  { front: '🥏', back: 'frisbee' },
  { front: '🪃', back: 'boomerang' },
  { front: '🪁', back: 'kite' },
  { front: '🎣', back: 'fishing pole' },
  { front: '🤿', back: 'snorkel mask / snorkeling gear' },
  { front: '🩱', back: 'swimsuit' },
  { front: '🎽', back: '🇬🇧singlet  / 🇺🇸tank top' },
  { front: '🥋', back: 'martial arts uniform' },
  { front: '🥊', back: 'boxing gloves' },
  { front: '🎱', back: '8 ball / 🇺🇸pool / 🇬🇧billiards' },
  { front: '🏓', back: 'ping pong' },
  { front: '🎳', back: 'bowling' },
  { front: '♟️️', back: 'chess piece' },
  { front: '🪀', back: 'yo-yo' },
  { front: '🧩', back: 'puzzle piece' },
  { front: '🎮', back: 'game controller / video game' },
  { front: '🕹️', back: 'joystick' },
  { front: '🔫', back: 'water gun / water pistol' },
  { front: '🎲', back: 'dice' },
  { front: '🎰', back: 'slot machine' },
  { front: '🎴', back: 'hanafuda' },
  { front: '🀄', back: 'mahjong tile' },
  { front: '🃏', back: 'joker' },
  { front: '🪄', back: 'magic wand' },
  { front: '🎩', back: 'top hat' },
  { front: '📸', back: 'camera with flash / photo / snapshot' },
  { front: '🖼️', back: 'painting / framed picture' },
  { front: '🫟', back: 'paint tube' },
  { front: '🖌️', back: 'paintbrush' },
  { front: '🖍️', back: 'crayon' },
  { front: '🪡', back: 'sewing needle' },
  { front: '🧵', back: 'thread' },
  { front: '🧶', back: 'yarn' },
  { front: '🎹', back: 'keyboard' },
  { front: '🎷', back: 'saxophone' },
  { front: '🎺', back: 'trumpet' },
  { front: '🪊', back: 'trombone' },
  { front: '🪕', back: 'banjo' },
  { front: '🎻', back: 'violin' },
  { front: '🪉', back: 'harp' },
  { front: '🪘', back: 'hand drum' },
  { front: '🥁', back: 'snare drum' },
  { front: '🪇', back: 'maracas' },
  { front: '🪈', back: 'flute' },
  { front: '🪗', back: 'accordion' },
  { front: '🎤', back: 'microphone' },
  { front: '🎧', back: 'headphones' },
  { front: '🎚️', back: 'audio mixer slider / fader' },
  { front: '🎛️', back: 'control knobs / mixer knobs' },
  { front: '🎙️', back: 'studio mic / broadcast microphone' },
  { front: '📼', back: 'VHS tape / videocassette' },
  { front: '📻', back: 'radio' },
  { front: '📺', back: 'TV / television' },
  { front: '📹', back: 'video camera / camcorder' },
  { front: '📽️', back: 'film projector' },
  { front: '🎥', back: 'movie camera' },
  { front: '🎞️', back: 'film strip / film frames' },
  { front: '🎬', back: 'clapperboard / slate' },
  { front: '🎭', back: 'performing arts / drama masks' },
  { front: '🎫', back: 'admission ticket' },
  { front: '🎟️', back: 'admissiontickets' },
  { front: '☎️', back: 'landline / home phone' },
  { front: '📞', back: 'handset / receiver' },
  { front: '📟', back: 'pager' },
  { front: '📠', back: 'fax machine' },
  { front: '🔌', back: 'electric plug / power cord if cable included' },
  { front: '🔋', back: 'battery' },
  { front: '🪫', back: 'low battery' },
  { front: '🖲️', back: 'trackball' },
  { front: '💽', back: 'minidisc' },
  { front: '💾', back: 'floppy disk' },
  { front: '💿', back: 'CD' },
  { front: '📀', back: 'DVD' },
  { front: '🖥️', back: 'desktop computer' },
  { front: '⌨️', back: 'computer keyboard' },
  { front: '🖨️', back: 'printer' },
  { front: '🖱️', back: 'mouse' },
  { front: '🪎', back: 'treasure chest' },
  { front: '🪙', back: 'coin' },
  { front: '💸', back: 'spending money / money flying away' },
  { front: '💵', back: 'dollar bill' },
  { front: '💴', back: 'yen bill' },
  { front: '💶', back: 'euro bill' },
  { front: '💷', back: 'banknote' },
  { front: '💳', back: 'credit card' },
  { front: '💰', back: 'money bag' },
  { front: '🧾', back: 'receipt' },
  { front: '🧮', back: 'abacus' },
  { front: '⚖️', back: 'scales' },
  { front: '🛒', back: '🇺🇸shopping cart / 🇬🇧shopping trolley' },
  { front: '🛍️', back: 'shopping bags' },
  { front: '🕯️', back: 'candle' },
  { front: '🔦', back: '🇺🇸flashlight / 🇬🇧torch' },
  { front: '🏮', back: 'lantern' },
  { front: '🧱', back: 'brick' },
  { front: '🪟', back: 'window' },
  { front: '🪞', back: 'mirror' },
  { front: '🚪', back: 'door' },
  { front: '🪑', back: 'chair' },
  { front: '🛏️', back: 'bed' },
  { front: '🛋️', back: '🇺🇸couch / 🇬🇧sofa' },
  { front: '🚿', back: 'shower head' },
  { front: '🛁', back: 'bathtub / 🇬🇧bath / tub' },
  { front: '🚽', back: 'toilet' },
  { front: '🧻', back: '🇺🇸toilet pap / 🇬🇧toilet roller' },
  { front: '🪠', back: 'plunger' },
  { front: '🪆', back: 'matryoshka / Russian doll' },
  { front: '🧷', back: 'safety pin' },
  { front: '🪢', back: 'knot' },
  { front: '🧹', back: 'broom' },
  { front: '🧴', back: 'bottle' },
  { front: '🧽', back: 'sponge' },
  { front: '🧼', back: 'soap' },
  { front: '🪥', back: 'toothbrush' },
  { front: '🪒', back: 'razor' },
  { front: '🪮', back: 'comb' },
  { front: '🧺', back: 'basket' },
  { front: '🧦', back: 'socks' },
  { front: '🧤', back: 'gloves' },
  { front: '🧣', back: 'scarf' },
  { front: '👖', back: 'jeans' },
  { front: '👕', back: 't-shirt' },
  { front: '👚', back: 'blouse' },
  { front: '👔', back: 'tie' },
  { front: '👗', back: 'dress' },
  { front: '👘', back: 'kimono' },
  { front: '🥻', back: 'sari' },
  { front: '👙', back: 'bikini' },
  { front: '🩳', back: 'shorts' },
  { front: '🩲', back: 'briefs' },
  { front: '🧥', back: 'coat' },
  { front: '🥼', back: 'lab coat' },
  { front: '🦺', back: 'safety vest' },
  { front: '⛑️', back: 'hard hat' },
  { front: '🪖', back: 'helmet' },
  { front: '🎓', back: 'graduation cap' },
  { front: '👒', back: 'sun hat' },
  { front: '🧢', back: 'cap' },
  { front: '👑', back: 'crown' },
  { front: '💄', back: 'lipstick' },
  { front: '🪭', back: 'hand fan' },
  { front: '🎒', back: 'backpack' },
  { front: '👝', back: 'clutch' },
  { front: '👛', back: 'purse' },
  { front: '👜', back: 'handbag' },
  { front: '💼', back: 'briefcase' },
  { front: '☂️', back: 'umbrella' },
  { front: '🌂', back: 'closed umbrella' },
  { front: '🥾', back: 'hiking boot' },
  { front: '👢', back: 'boot' },
  { front: '👠', back: 'high heel' },
  { front: '🩴', back: 'flip-flop' },
  { front: '👟', back: 'sneaker' },
  { front: '👞', back: 'shoe' },
  { front: '🥿', back: 'flat shoe' },
  { front: '👡', back: 'sandal' },
  { front: '🦯', back: 'cane' },
  { front: '👓', back: 'glasses' },
  { front: '🥽', back: 'goggles' },
  { front: '⚗️', back: 'alembic' },
  { front: '🧫', back: 'petri dish' },
  { front: '🧪', back: 'test tube' },
  { front: '💉', back: 'syringe' },
  { front: '💊', back: 'pill' },
  { front: '🩹', back: 'bandaid' },
  { front: '🩺', back: 'stethoscope' },
  { front: '🩻', back: 'x-ray' },
  { front: '🧬', back: 'dna' },
  { front: '🔭', back: 'telescope' },
  { front: '🔬', back: 'microscope' },
  { front: '📡', back: 'satellite dish' },
  { front: '🛰️', back: 'satellite' },
  { front: '🧯', back: 'fire extinguisher' },
  { front: '🪓', back: 'axe' },
  { front: '🪜', back: 'ladder' },
  { front: '🪣', back: 'bucket' },
  { front: '🪝', back: 'hook' },
  { front: '🧲', back: 'magnet' },
  { front: '🧰', back: 'toolbox' },
  { front: '🗜️', back: 'clamp' },
  { front: '🔩', back: 'nut and bolt' },
  { front: '🪛', back: 'screwdriver' },
  { front: '🪚', back: 'saw' },
  { front: '🔧', back: 'wrench' },
  { front: '🔨', back: 'hammer' },
  { front: '🛠️', back: 'tools' },
  { front: '⚒️', back: 'hammer and pick' },
  { front: '⛏️', back: 'pickaxe' },
  { front: '🪏', back: 'shovel' },
  { front: '⚙️', back: 'gear' },
  { front: '⛓️‍💥', back: 'broken chain' },
  { front: '🔗', back: 'link' },
  { front: '⛓️', back: 'chains' },
  { front: '📎', back: 'paperclip' },
  { front: '🖇️', back: 'paperclips' },
  { front: '✂️', back: 'scissors' },
  { front: '📏', back: 'ruler' },
  { front: '📐', back: 'triangle ruler' },
  { front: '🖊️', back: 'pen' },
  { front: '🖋️', back: 'fountain pen' },
  { front: '✒️', back: 'nib' },
  { front: '📝', back: 'memo' },
  { front: '🗒️', back: 'notepad' },
  { front: '📄', back: 'page' },
  { front: '📃', back: 'page with curl' },
  { front: '📑', back: 'bookmarks' },
  { front: '📋', back: 'clipboard' },
  { front: '🗃️', back: 'card box' },
  { front: '🗄️', back: 'filing cabinet' },
  { front: '📒', back: 'ledger' },
  { front: '📔', back: 'notebook' },
  { front: '📕', back: 'book' },
  { front: '📓', back: 'notebook' },
  { front: '📗', back: 'book' },
  { front: '📘', back: 'book' },
  { front: '📙', back: 'book' },
  { front: '📖', back: 'open book' },
  { front: '🔖', back: 'bookmark' },
  { front: '📂', back: 'open folder' },
  { front: '📁', back: 'folder' },
  { front: '🗂️', back: 'dividers' },
  { front: '📊', back: 'bar chart' },
  { front: '📈', back: 'chart up' },
  { front: '📉', back: 'chart down' },
  { front: '📇', back: 'card index' },
  { front: '🪪', back: 'id card' },
  { front: '📌', back: 'pushpin' },
  { front: '📍', back: 'pin' },
  { front: '🗑️', back: 'trash can' },
  { front: '📰', back: 'newspaper' },
  { front: '🗞️', back: 'rolled newspaper' },
  { front: '🏷️', back: 'tag' },
  { front: '📤', back: 'outbox' },
  { front: '📥', back: 'inbox' },
  { front: '📩', back: 'incoming mail' },
  { front: '📨', back: 'incoming mail' },
  { front: '✉️', back: 'envelope' },
  { front: '📧', back: 'email' },
  { front: '📫', back: 'mailbox' },
  { front: '📪', back: 'mailbox' },
  { front: '📬', back: 'mailbox' },
  { front: '📭', back: 'mailbox' },
  { front: '📦', back: 'package' },
  { front: '📯', back: 'postal horn' },
  { front: '📮', back: 'mailbox' },
  { front: '🗳️', back: 'ballot box' },
  { front: '📅', back: 'calendar' },
  { front: '📆', back: 'calendar' },
  { front: '🗓️', back: 'calendar' },
  { front: '🪧', back: 'placard' },
  { front: '🕰️', back: 'mantelpiece clock' },
  { front: '⌛', back: 'hourglass' },
  { front: '⏳', back: 'hourglass' },
  { front: '⏲️', back: 'timer' },
  { front: '⌚', back: 'watch' },
  { front: '⏱️', back: 'stopwatch' },
  { front: '🕛', back: '12:00' },
  { front: '🕧', back: '12:30' },
  { front: '🕐', back: '1:00' },
  { front: '🕜', back: '1:30' },
  { front: '🕑', back: '2:00' },
  { front: '🕝', back: '2:30' },
  { front: '🕒', back: '3:00' },
  { front: '🕞', back: '3:30' },
  { front: '🕓', back: '4:00' },
  { front: '🕟', back: '4:30' },
  { front: '🕔', back: '5:00' },
  { front: '🕠', back: '5:30' },
  { front: '🕕', back: '6:00' },
  { front: '🕡', back: '6:30' },
  { front: '🕖', back: '7:00' },
  { front: '🕢', back: '7:30' },
  { front: '🕗', back: '8:00' },
  { front: '🕣', back: '8:30' },
  { front: '🕘', back: '9:00' },
  { front: '🕤', back: '9:30' },
  { front: '🕙', back: '10:00' },
  { front: '🕥', back: '10:30' },
  { front: '🕚', back: '11:00' },
  { front: '🕦', back: '11:30' },
  { front: '🛎️', back: 'service bell' },
  { front: '🔔', back: 'bell' },
  { front: '🔈', back: 'muted speaker' },
  { front: '🔉', back: 'speaker' },
  { front: '🔊', back: 'speaker' },
  { front: '📣', back: 'megaphone' },
  { front: '🔍', back: 'magnifying glass' },
  { front: '🔎', back: 'magnifying glass' },
  { front: '🔮', back: 'crystal ball' },
  { front: '🧿', back: 'evil eye' },
  { front: '🪬', back: 'hamsa' },
  { front: '📿', back: 'prayer beads' },
  { front: '🏺', back: 'amphora' },
  { front: '⚱️', back: 'urn' },
  { front: '🚬', back: 'cigarette' },
  { front: '💣', back: 'bomb' },
  { front: '🪤', back: 'mousetrap' },
  { front: '📜', back: 'scroll' },
  { front: '⚔️', back: 'swords' },
  { front: '🔏', back: 'locked with pen' },
  { front: '🔓', back: 'unlocked' },
    // --- 記号・シンボル・アイコン (Symbols & Signs & Icons) ---
  { front: '🔴', back: 'red circle' },
  { front: '🟠', back: 'orange circle' },
  { front: '🟡', back: 'yellow circle' },
  { front: '🟢', back: 'green circle' },
  { front: '🔵', back: 'blue circle' },
  { front: '🟣', back: 'purple circle' },
  { front: '🟤', back: 'brown circle' },
  { front: '⚫', back: 'black circle' },
  { front: '⚪', back: 'white circle' },
  { front: '🟥', back: 'red square' },
  { front: '🟧', back: 'orange square' },
  { front: '🟨', back: 'yellow square' },
  { front: '🟩', back: 'green square' },
  { front: '🟦', back: 'blue square' },
  { front: '🟪', back: 'purple square' },
  { front: '🟫', back: 'brown square' },
  { front: '⬛', back: 'black square' },
  { front: '⬜', back: 'white square' },
  { front: '♦️', back: 'diamonds' },
  { front: '♣️', back: 'clubs' },
  { front: '♠️', back: 'spades' },
  { front: '♈', back: 'aries' },
  { front: '♉', back: 'taurus' },
  { front: '♊', back: 'gemini' },
  { front: '♋', back: 'cancer' },
  { front: '♌', back: 'leo' },
  { front: '♍', back: 'virgo' },
  { front: '♎', back: 'libra' },
  { front: '♏', back: 'scorpio' },
  { front: '♐', back: 'sagittarius' },
  { front: '♑', back: 'capricorn' },
  { front: '♒', back: 'aquarius' },
  { front: '♓', back: 'pisces' },
  { front: '⛎', back: 'ophiuchus' },
  { front: '♀️', back: 'female' },
  { front: '♂️', back: 'male' },
  { front: '⚧️️', back: 'transgender' },
  { front: '💭', back: 'thought bubble' },
  { front: '🗯️', back: 'anger bubble' },
  { front: '💬', back: 'speech bubble' },
  { front: '🗨️', back: 'speech bubble' },
  { front: '❕', back: 'exclamation' },
  { front: '❔', back: 'question mark' },
  { front: '❗', back: 'exclamation' },
  { front: '❓', back: 'question' },
  { front: '⁉️', back: 'interrobang' },
  { front: '‼️', back: 'double exclamation' },
  { front: '❌', back: 'cross' },
  { front: '🚫', back: 'prohibited' },
  { front: '🚳', back: 'no bikes' },
  { front: '🚭', back: 'no smoking' },
  { front: '🚯', back: 'no littering' },
  { front: '🚱', back: 'non-potable water' },
  { front: '🚷', back: 'no pedestrians' },
  { front: '📵', back: 'no phones' },
  { front: '🔞', back: '18 plus' },
  { front: '🔕', back: 'notifications off' },
  { front: '🔇', back: 'muted' },
  { front: '🅰️', back: 'a button' },
  { front: '🆎', back: 'ab button' },
  { front: '🅱️', back: 'b button' },
  { front: '🅾️', back: 'o button' },
  { front: '🆑', back: 'cl button' },
  { front: '🆘', back: 'sos' },
  { front: '⛔', back: 'no entry' },
  { front: '📛', back: 'name badge' },
  { front: '♨️', back: 'hot springs' },
  { front: '🔻', back: 'red triangle down' },
  { front: '🔺', back: 'red triangle up' },
  { front: '🉐', back: 'bargain' },
  { front: '✴️', back: 'eight-pointed star' },
  { front: '🔶', back: 'orange diamond' },
  { front: '🔸', back: 'small orange diamond' },
  { front: '🔆', back: 'high brightness' },
  { front: '🔅', back: 'low brightness' },
  { front: '🆚', back: 'vs' },
  { front: '🎦', back: 'cinema' },
  { front: '📶', back: 'signal' },
  { front: '🔁', back: 'repeat' },
  { front: '🔂', back: 'repeat one' },
  { front: '🔀', back: 'shuffle' },
  { front: '▶️', back: 'play' },
  { front: '⏩', back: 'fast forward' },
  { front: '⏭️', back: 'next track' },
  { front: '⏯️', back: 'play pause' },
  { front: '◀️', back: 'reverse' },
  { front: '⏪', back: 'fast rewind' },
  { front: '⏮️', back: 'previous track' },
  { front: '🔼', back: 'up button' },
  { front: '⏫', back: 'fast up' },
  { front: '🔽', back: 'down button' },
  { front: '⏬', back: 'fast down' },
  { front: '⏸️', back: 'pause' },
  { front: '⏹️', back: 'stop' },
  { front: '⏺️', back: 'record' },
  { front: '⏏️', back: 'eject' },
  { front: '📴', back: 'phone off' },
  { front: '🛜', back: 'wifi' },
  { front: '📳', back: 'vibrate' },
  { front: '📲', back: 'phone with arrow' },
  { front: '☢️', back: 'radioactive' },
  { front: '☣️', back: 'biohazard' },
  { front: '⚠️', back: 'warning' },
  { front: '🚸', back: 'children crossing' },
  { front: '⚜️', back: 'fleur-de-lis' },
  { front: '🔱', back: 'trident' },
  { front: '〽️', back: 'part alternation' },
  { front: '🔰', back: 'beginner' },
  { front: '✳️', back: 'asterisk' },
  { front: '❇️', back: 'sparkle' },
  { front: '♻️', back: 'recycle' },
  { front: '💱', back: 'currency exchange' },
  { front: '💲', back: 'dollar sign' },
  { front: '💹', back: 'chart up yen' },
  { front: '❎', back: 'cross mark' },
  { front: '✅', back: 'check mark' },
  { front: '✔️️', back: 'check mark' },
  { front: '☑️', back: 'checkbox' },
  { front: '⬆️', back: 'up arrow' },
  { front: '↗️', back: 'up-right arrow' },
  { front: '➡️', back: 'right arrow' },
  { front: '↘️', back: 'down-right arrow' },
  { front: '⬇️', back: 'down arrow' },
  { front: '↙️', back: 'down-left arrow' },
  { front: '⬅️', back: 'left arrow' },
  { front: '↖️', back: 'up-left arrow' },
  { front: '↕️', back: 'up-down arrow' },
  { front: '↔️', back: 'left-right arrow' },
  { front: '↩️', back: 'curved arrow' },
  { front: '↪️', back: 'curved arrow' },
  { front: '⤴️', back: 'curved arrow' },
  { front: '⤵️', back: 'curved arrow' },
  { front: '🔃', back: 'clockwise arrows' },
  { front: '🔄', back: 'counterclockwise arrows' },
  { front: '🔙', back: 'back' },
  { front: '🔛', back: 'on' },
  { front: 'TOP', back: 'top' },
  { front: '🔚', back: 'end' },
  { front: '🔜', back: 'soon' },
  { front: '🆕', back: 'new' },
  { front: '🆓', back: 'free' },
  { front: '🆙', back: 'up' },
  { front: '🆗', back: 'ok' },
  { front: '🆒', back: 'cool' },
  { front: '🆖', back: 'ng' },
  { front: 'ℹ️', back: 'info' },
  { front: '🅿️', back: 'parking' },
  { front: '🔣', back: 'symbols' },
  { front: '🔤', back: 'letters' },
  { front: '🔢', back: 'numbers' },
  { front: '#️⃣', back: 'hashtag' },
  { front: '*️⃣', back: 'asterisk' },
  { front: '0️⃣', back: '0' },
  { front: '1️⃣', back: '1' },
  { front: '2️⃣', back: '2' },
  { front: '3️⃣', back: '3' },
  { front: '4️⃣', back: '4' },
  { front: '5️⃣', back: '5' },
  { front: '6️⃣', back: '6' },
  { front: '7️⃣', back: '7' },
  { front: '8️⃣', back: '8' },
  { front: '9️⃣', back: '9' },
  { front: '🔟', back: '10' },
  { front: '💠', back: 'diamond' },
  { front: '🔷', back: 'blue diamond' },
  { front: '🔹', back: 'small blue diamond' },
  { front: '🏧', back: 'atm' },
  { front: 'Ⓜ️', back: 'metro' },
  { front: '🚾', back: 'restroom' },
  { front: '🚻', back: 'restroom' },
  { front: '🚹', back: 'mens' },
  { front: '🚺', back: 'womens' },
  { front: '♿', back: 'wheelchair' },
  { front: '🚼', back: 'baby change' },
  { front: '🛗', back: 'elevator' },
  { front: '🚮', back: 'litter bin' },
  { front: '🚰', back: 'drinking water' },
  { front: '🛂', back: 'passport control' },
  { front: '🛃', back: 'customs' },
  { front: '🛄', back: 'baggage claim' },
  { front: '🛅', back: 'luggage storage' },
  { front: '⚕️', back: 'medical symbol' },
  { front: '⚛️', back: 'atom' },
  { front: '🛐', back: 'place of worship' },
  { front: '🕉️', back: 'om' },
  { front: '☸️', back: 'dharma wheel' },
  { front: '☮️', back: 'peace' },
  { front: '☯️', back: 'yin yang' },
  { front: '☪️', back: 'star and crescent' },
  { front: '🪯', back: 'khanda' },
  { front: '✝️️', back: 'cross' },
  { front: '☦️', back: 'orthodox cross' },
  { front: '✡️', back: 'star of david' },
  { front: '🔯', back: 'hexagram' },
  { front: '🕎', back: 'menorah' },
  { front: '♾️', back: 'infinity' }
  ];