window.French = [
  // --- 動物・生き物 (Animaux) ---
  { front: '🐺', back: 'le loup' },
  { front: '🦊', back: 'le renard' },
  { front: '🐯', back: 'le tigre' },
  { front: '🦁', back: 'le lion' },
  { front: '🦇', back: 'la chauve-souris' },
  { front: '🐵', back: 'le singe' },
  { front: '🦉', back: 'le hibou' },
  { front: '🐢', back: 'la tortue' },
  { front: '🐻‍❄️', back: "l'ours polaire" },
  { front: '🐨', back: 'le koala' },
  { front: '🐴', back: 'le cheval' },
  { front: '🐹', back: 'le hamster' },
  { front: '🦓', back: 'le zèbre' },
  { front: '🐑', back: 'le mouton' },
  { front: '🐖', back: 'le cochon' },
  { front: '🐄', back: 'la vache' },
  { front: '🦒', back: 'la girafe' },
  { front: '🐘', back: "l'éléphant" },
  { front: '🐫', back: 'le chameau' },
  { front: '🐣', back: 'le poussin' },
  { front: '🐓', back: 'le coq' },
  { front: '🕊️', back: 'la colombe' },
  { front: '🦚', back: 'le paon' },
  { front: '🐬', back: 'le dauphin' },
  { front: '🦈', back: 'le requin' },
  { front: '🦀', back: 'le crabe' },
  { front: '🪼', back: 'la méduse' },
  { front: '🐛', back: 'la chenille' },
  { front: '🦖', back: 'le tyrannosaure' },
  { front: '🦕', back: 'le dinosaure' },
  { front: '🦘', back: 'le kangourou' },
  { front: '🦥', back: 'le paresseux' },
  { front: '🦦', back: 'la loutre' },
  { front: '🦩', back: 'le flamant rose' },
  { front: '🐈', back: 'le chat' },
  { front: '🐕', back: 'le chien' },
  { front: '🐇', back: 'le lapin' },
  { front: '🦡', back: 'le blaireau' },
  { front: '🦨', back: 'la moufette' },
  { front: '🦝', back: 'le raton laveur' },
  { front: '🦭', back: 'le phoque' },
  { front: '🪶', back: 'la plume' },
  { front: '🥚', back: "l'œuf" },
  { front: '🦴', back: "l'os" },
  { front: '🦧', back: "l'orang-outan" },
  { front: '🐀', back: 'le rat' },
  { front: '🐁', back: 'la souris' },
  { front: '🐂', back: 'le bœuf' },
  { front: '🐋', back: 'la baleine' },
  { front: '🐌', back: "l'escargot" },
  { front: '🐃', back: 'le buffle' },
  { front: '🐆', back: 'le léopard' },
  { front: '🐉', back: 'le dragon' },
  { front: '🐊', back: 'le crocodile' },
  { front: '🐗', back: 'le sanglier' },
  { front: '🐙', back: 'la pieuvre' },
  { front: '🐚', back: 'le coquillage' },
  { front: '🐟', back: 'le poisson' },
  { front: '🐐', back: 'la chèvre' },
  { front: '🐍', back: 'le serpent' },
  { front: '🐩', back: 'le caniche' },
  { front: '🐪', back: 'le dromadaire' },
  { front: '🐭', back: 'la souris' },
  { front: '🐮', back: 'la vachotte' },
  { front: '🐳', back: 'la baleine' },
  { front: '🐻', back: 'l’ours' },
  { front: '🐼', back: 'le panda' },
  { front: '🐾', back: 'la empreinte' },
  { front: '🐿️', back: 'l’écureuil' },
  { front: '🦆', back: 'le canard' },
  { front: '🦅', back: 'l’aigle' },
  { front: '🦄', back: 'la licorne' },
  { front: '🦃', back: 'le dindon' },
  { front: '🦂', back: 'le scorpion' },
  { front: '🦌', back: 'le cerf' },
  { front: '🦍', back: 'le gorille' },
  { front: '🦎', back: 'le lézard' },
  { front: '🦏', back: 'le rhinocéros' },
  { front: '🦐', back: 'la crevette' },
  { front: '🦑', back: 'le calmar' },
  { front: '🦣', back: 'le mammouth' },
  { front: '🦛', back: 'l’hippopotame' },
  { front: '🦙', back: 'le lama' },
  { front: '🦔', back: 'le hérisson' },
  { front: '🦫', back: 'le castor' },
  { front: '🦬', back: 'le bison' },
  { front: '🫎', back: 'l’élan' },
  { front: '🫏', back: 'l’âne' },
  { front: '🙈', back: 'le singe (qui se cache les yeux)' },
  { front: '🙉', back: 'le singe (qui se bouche les oreilles)' },
  { front: '🙊', back: 'le singe (qui se bouche la bouche)' },
  { front: '🐸', back: 'la grenouille' },
  { front: '🦮', back: 'le chien guide' },
  { front: '🐕‍🦺', back: 'le chien d’assistance' },
  { front: '🐏', back: 'le bélier' },
  { front: '🐦', back: 'l’oiseau' },
  { front: '🐦‍⬛', back: 'le corbeau' },
  { front: '🦜', back: 'le perroquet' },
  { front: '🦤', back: 'le dodo' },
  { front: '🦢', back: 'le cygne' },
  { front: '🪿', back: 'l’oie' },
  { front: '🐦‍🔥', back: 'le phénix' },
  { front: '🐧', back: 'le manchot' },
  { front: '🫍', back: 'l’organisme marin' }, // もしくは微調整用のプレースホルダー等
  { front: '🐠', back: 'le poisson tropical' },
  { front: '🐡', back: 'le poisson-globe' },
  { front: '🦪', back: 'l’huître' },
  { front: '🪸', back: 'le corail' },
  { front: '🫧', back: 'les bulles' },
  { front: '🕷️', back: 'l’araignée' },
  { front: '🕸️', back: 'la toile d’araignée' },
  { front: '🐜', back: 'la fourmi' },
  { front: '🦗', back: 'le grillon' },
  { front: '🪲', back: 'le coléoptère' },
  { front: '🦟', back: 'le moustique' },
  { front: '🪳', back: 'la cafard' },
  { front: '🪰', back: 'la mouche' },
  { front: '🐝', back: 'l’abeille' },
  { front: '🐞', back: 'la coccinelle' },
  { front: '🦋', back: 'le papillon' },
  { front: '🪱', back: 'le ver' },
  { front: '🦠', back: 'le microbe' },



  // --- 食べ物・飲み物 (Nourriture & Boissons) ---
  
  { front: '🍎', back: 'la pomme' },
  { front: '🍓', back: 'la fraise' },
  { front: '🍉', back: 'la pastèque' },
  { front: '🍒', back: 'la cerise' },
  { front: '🍍', back: "l'ananas" },
  { front: '🍊', back: "l'orange" },
  { front: '🍑', back: 'la pêche' },
  { front: '🥕', back: 'la carotte' },
  { front: '🥦', back: 'le brocoli' },
  { front: '🥑', back: "l'avocat" },
  { front: '🫑', back: 'le poivron' },
  { front: '🍆', back: "l'aubergine" },
  { front: '🍇', back: 'le raisin' },
  { front: '🥒', back: 'le concombre' },
  { front: '🍄‍🟫', back: 'le champignon' },
  { front: '🧄', back: "l'ail" },
  { front: '🥬', back: 'la salade' },
  { front: '🧅', back: "l'oignon" },
  { front: '🥔', back: 'la pomme de terre' },
  { front: '🌽', back: 'le maïs' },
  { front: '🍅', back: 'la tomate' },
  { front: '🍋', back: 'le citron' },
  { front: '🍌', back: 'la banane' },
  { front: '🍐', back: 'la poire' },
  { front: '🥝', back: 'le kiwi' },
  { front: '🥭', back: 'la mangue' },
  { front: '🥥', back: 'la noix de coco' },
  { front: '🥐', back: 'le croissant' },
  { front: '🥖', back: 'la baguettes' },
  { front: '🍞', back: 'le pain' },
  { front: '🧀', back: 'le fromage' },
  { front: '🥩', back: 'la viande' },
  { front: '🍗', back: 'le poulet' },
  { front: '🍔', back: 'le hamburger' },
  { front: '🍕', back: 'la pizza' },
  { front: '🍜', back: 'les nouilles' },
  { front: '🍣', back: 'les sushis' },
  { front: '🍩', back: 'le donut' },
  { front: '🍰', back: 'le gâteau' },
  { front: '🍫', back: 'le chocolat' },
  { front: '☕', back: 'le café' },
  { front: '🍵', back: 'le thé' },
  { front: '🍺', back: 'la bière' },
  { front: '🍷', back: 'le vin' },
  { front: '🌶️', back: 'le piment' },
  { front: '🍋‍🟩', back: 'le citron vert' },
  { front: '🍈', back: 'le melon' },
  { front: '🫛', back: 'les pois' },
  { front: '🍏', back: 'la pomme verte' },
  { front: '🫒', back: "l'olive" },
  { front: '🫐', back: 'les myrtilles' },
  { front: '🍠', back: 'la patate douce' },
  { front: '🫜', back: 'le navet' },
  { front: '🫚', back: 'le gingembre' },
  { front: '🫘', back: 'les haricots' },
  { front: '🌰', back: 'la chataigne' },
  { front: '🥜', back: 'les cacahuètes' },
  { front: '🫓', back: 'le pain plat' },
  { front: '🥯', back: 'le bagel' },
  { front: '🧇', back: 'la gaufre' },
  { front: '🥞', back: 'les crêpes' },
  { front: '🍳', back: 'l’œuf au plat' },
  { front: '🥓', back: 'le bacon' },
  { front: '🍖', back: 'la viande avec os' },
  { front: '🌭', back: 'le hot-dog' },
  { front: '🥪', back: 'le sandwich' },
  { front: '🥨', back: 'le bretzel' },
  { front: '🍟', back: 'les frites' },
  { front: '🫔', back: 'le tamal' },
  { front: '🌮', back: 'le taco' },
  { front: '🌯', back: 'le burrito' },
  { front: '🥙', back: 'le pita farci' },
  { front: '🧆', back: 'les falafels' },
  { front: '🥘', back: 'la paella' },
  { front: '🍝', back: 'les spaghettis' },
  { front: '🥫', back: 'la conserve' },
  { front: '🫕', back: 'la fondue' },
  { front: '🥣', back: 'le bol de céréales' },
  { front: '🥗', back: 'la salade composée' },
  { front: '🍲', back: 'la potée' },
  { front: '🍛', back: 'le riz au curry' },
  { front: '🦪', back: "l'huître" },
  { front: '🦞', back: 'le homard' },
  { front: '🍤', back: 'la crevette' },
  { front: '🥡', back: 'la boîte à emporter' },
  { front: '🍚', back: 'le riz' },
  { front: '🍱', back: 'le bento' },
  { front: '🥟', back: 'le ravioli' },
  { front: '🍢', back: 'l’oden' },
  { front: '🍙', back: 'la boulette de riz' },
  { front: '🍘', back: 'le cracker de riz' },
  { front: '🍥', back: 'le gâteau de poisson' },
  { front: '🍡', back: 'le dango' },
  { front: '🥠', back: 'le biscuit de la fortune' },
  { front: '🥮', back: 'le gâteau de lune' },
  { front: '🍧', back: 'la glace pilée' },
  { front: '🍨', back: 'la crème glacée' },
  { front: '🍦', back: 'la glace à l’italienne' },
  { front: '🥧', back: 'la tarte' },
  { front: '🍮', back: 'le flan' },
  { front: '🎂', back: 'le gâteau d’anniversaire' },
  { front: '🧁', back: 'lecupcake' },
  { front: '🍭', back: 'la sucette' },
  { front: '🍬', back: 'le bonbon' },
  { front: '🍪', back: 'le biscuit' },
  { front: '🍯', back: 'le miel' },
  { front: '🧂', back: 'le sel' },
  { front: '🧈', back: 'le beurre' },
  { front: '🍿', back: 'le pop-corn' },
  { front: '🧊', back: 'le glaçon' },
  { front: '🫙', back: 'le bocal' },
  { front: '🥤', back: 'la boisson' },
  { front: '🧋', back: 'le thé aux perles' },
  { front: '🧃', back: 'la brique de jus' },
  { front: '🥛', back: 'le lait' },
  { front: '🍼', back: 'le biberon' },
  { front: '🫖', back: 'la théière' },
  { front: '🧉', back: 'le maté' },
  { front: '🍻', back: 'les chopes de bière' },
  { front: '🥂', back: 'les flûtes de champagne' },
  { front: '🍾', back: 'la bouteille de champagne' },
  { front: '🥃', back: 'le verre de whisky' },
  { front: '🫗', back: 'le liquide versé' },
  { front: '🍸', back: 'le verre de cocktail' },
  { front: '🍹', back: 'le cocktail tropical' },
  { front: '🍶', back: 'le saké' },
  { front: '🥢', back: 'les baguettes' },
  { front: '🍴', back: 'la fourchette et le couteau' },
  { front: '🥄', back: 'la cuillère' },
  { front: '🔪', back: 'le couteau' },
  { front: '🍽️', back: 'l’assiette et couverts' },

  // --- 植物・自然・天気 (Nature & Météo) ---
  { front: '💎', back: 'le diamant' },
  { front: '🌸', back: 'la fleur de cerisier' },
  { front: '🪻', back: 'la jacinthe' },
  { front: '🌷', back: 'la tulipe' },
  { front: '🌹', back: 'la rose' },
  { front: '🌻', back: 'le tournesol' },
  { front: '🌼', back: 'la marguerite' },
  { front: '🌵', back: 'le cactus' },
  { front: '🌲', back: 'le conifère' },
  { front: '🌳', back: "l'arbre" },
  { front: '🍀', back: 'le trèfle à quatre feuilles' },
  { front: '🍁', back: 'la feuille d’érable' },
  { front: '☔', back: 'le parapluie' },
  { front: '☀️', back: 'le soleil' },
  { front: '🌙', back: 'la lune' },
  { front: '🌏', back: 'la terre' },
  { front: '🌕', back: 'la pleine lune' },
  { front: '⚡', back: "l'éclair" },
  { front: '🌈', back: 'l’arc-en-ciel' },
  { front: '🔥', back: 'le feu' },
  { front: '💧', back: 'la goutte d’eau' },
  { front: '🌊', back: 'la vague' },
  { front: '❄️', back: 'le flocon de neige' },
  { front: '⭐', back: 'l’étoile' },
  { front: '💐', back: 'le bouquet' },
  { front: '🥀', back: 'la fleur fanée' },
  { front: '🌺', back: 'l’hibiscus' },
  { front: '🪷', back: 'le lotus' },
  { front: '💮', back: 'la fleur blanche' },
  { front: '🏵️', back: 'la rosette' },
  { front: '🍂', back: 'les feuilles mortes' },
  { front: '🍄', back: 'le champignon' },
  { front: '🌾', back: 'l’épis de riz' },
  { front: '🌿', back: 'la herbe' },
  { front: '🌱', back: 'la jeune pousse' },
  { front: '🍃', back: 'les feuilles au vent' },
  { front: '☘️', back: 'le trèfle' },
  { front: '🪴', back: 'la plante en pot' },
  { front: '🌴', back: 'le palmier' },
  { front: '🪾', back: 'l’arbre sans feuilles' },
  { front: '🪵', back: 'le bois' },
  { front: '🪹', back: 'le nid vide' },
  { front: '🪺', back: 'le nid avec des œufs' },
  { front: '🪨', back: 'le rocher' },
  { front: '🛘', back: 'le chariot de bagages' },
  { front: '⛰️', back: 'la montagne' },
  { front: '🏔️', back: 'la montagne enneigée' },
  { front: '☃️', back: 'le bonhomme de neige' },
  { front: '⛄', back: 'le bonhomme de neige sans neige' },
  { front: '🌡️', back: 'le thermomètre' },
  { front: '🌋', back: 'le volcan' },
  { front: '🏜️', back: 'le désert' },
  { front: '🏞️', back: 'le paysage' },
  { front: '🌅', back: 'le lever du soleil' },
  { front: '🌄', back: 'le lever du soleil sur les montagnes' },
  { front: '🏝️', back: 'l’île déserte' },
  { front: '🏖️', back: 'la plage et parasol' },
  { front: '🌬️', back: 'le visage de vent' },
  { front: '🌀', back: 'le cyclone' },
  { front: '🌪️', back: 'la tornade' },
  { front: '☁️', back: 'le nuage' },
  { front: '🌨️', back: 'le nuage et neige' },
  { front: '🌧️', back: 'le nuage et pluie' },
  { front: '🌩️', back: 'le nuage et éclair' },
  { front: '⛈️', back: 'l’orage' },
  { front: '🌦️', back: 'le soleil derrière un nuage' },
  { front: '🌥️', back: 'le grand nuage' },
  { front: '⛅', back: 'le soleil derrière un nuage' },
  { front: '🌤️', back: 'le petit soleil derrière un nuage' },
  { front: '🌞', back: 'le soleil avec visage' },
  { front: '🌝', back: 'la pleine lune avec visage' },
  { front: '🌚', back: 'la nouvelle lune avec visage' },
  { front: '🌜', back: 'le premier quartier de lune avec visage' },
  { front: '🌛', back: 'le dernier quartier de lune avec visage' },
  { front: '🌟', back: 'l’étoile scintillante' },
  { front: '✨', back: 'les étincelles' },
  { front: '🕳️', back: 'le trou' },
  { front: '🪐', back: 'la planète aux anneaux' },
  { front: '🌍', back: 'la terre (Europe-Afrique)' },
  { front: '🌎', back: 'la terre (Amériques)' },
  { front: '🌫️', back: 'le brouillard' },
  { front: '🌠', back: 'l’étoile filante' },
  { front: '🌌', back: 'la voie lactée' },
  { front: '☄️', back: 'la comète' },
  { front: '🌑', back: 'la nouvelle lune' },
  { front: '🌒', back: 'le premier croissant de lune' },
  { front: '🌓', back: 'le premier quartier de lune' },
  { front: '🌔', back: 'la lune gibbeuse croissante' },
  { front: '🌖', back: 'la lune gibbeuse décroissante' },
  { front: '🌗', back: 'le dernier quartier de lune' },
  { front: '🌘', back: 'le dernier croissant de lune' },


  // --- 感情・顔 (Émotions & Visages) ---
  { front: '😄', back: 'le sourire' },
  { front: '🥲', back: 'le rire avec une larme' },
  { front: '🤤', back: 'la bave' },
  { front: '🥹', back: 'les yeux suppliants' },
  { front: '😱', back: 'la peur' },
  { front: '👻', back: 'le fantôme' },
  { front: '💀', back: 'le crâne' },
  { front: '😍', back: 'les yeux en cœur' },
  { front: '😎', back: 'le lunettes de soleil' },
  { front: '😢', back: 'la tristesse' },
  { front: '😡', back: 'la colère' },
  { front: '🥳', back: 'la fête' },
  { front: '😴', back: 'le sommeil' },
  { front: '🤖', back: 'le robot' },
  { front: '👽', back: 'l’extraterrestre' },
  { front: '💩', back: 'le caca' },
  { front: '😀', back: 'le visage souriant' },
  { front: '😃', back: 'le visage souriant avec les grands yeux' },
  { front: '😁', back: 'le visage souriant avec les dents serrées' },
  { front: '😆', back: 'le visage souriant avec les yeux plissés' },
  { front: '😅', back: 'le visage souriant avec une sueur froide' },
  { front: '😂', back: 'le visage pleurant de joie' },
  { front: '🤣', back: 'le visage roulant par terre de rire' },
  { front: '😭', back: 'le visage en pleurs' },
  { front: '😉', back: 'le clin d’œil' },
  { front: '😗', back: 'le visage faisant un bisou' },
  { front: '😙', back: 'le visage faisant un bisou avec les yeux souriants' },
  { front: '😚', back: 'le visage faisant un bisou avec les yeux fermés' },
  { front: '😘', back: 'le visage envoyant un baiser' },
  { front: '🥰', back: 'le visage souriant avec des cœurs' },
  { front: '🤩', back: 'le visage avec des étoiles dans les yeux' },
  { front: '🫠', back: 'le visage fondants' },
  { front: '🙃', back: 'le visage à l’envers' },
  { front: '🙂', back: 'le visage légèrement souriant' },
  { front: '😊', back: 'le visage souriant avec les yeux souriants' },
  { front: '☺️', back: 'le visage souriant classique' },
  { front: '😌', back: 'le visage soulagé' },
  { front: '🙂‍↕️', back: 'le visage qui fait OUI de la tête' },
  { front: '🙂‍↔️', back: 'le visage qui fait NON de la tête' },
  { front: '😏', back: 'le sourire en coin' },
  { front: '😋', back: 'le visage savourant un délicieux repas' },
  { front: '😛', back: 'tirer la langue' },
  { front: '😝', back: 'tirer la langue avec les yeux plissés' },
  { front: '😜', back: 'tirer la langue avec un clin d’œil' },
  { front: '🤪', back: 'le visage fou' },
  { front: '🫪', back: 'le visage avec des cheveux en bataille' },
  { front: '😔', back: 'le visage pensif' },
  { front: '🥺', back: 'le visage implorant' },
  { front: '😬', back: 'la grimace' },
  { front: '😑', back: 'le visage sans expression' },
  { front: '😐', back: 'le visage neutre' },
  { front: '😶', back: 'le visage sans bouche' },
  { front: '😶‍🌫️', back: 'le visage dans le brouillard' },
  { front: '🫥', back: 'le visage en pointillés' },
  { front: '🤐', back: 'la bouche cousue' },
  { front: '🫡', back: 'le salut militaire' },
  { front: '🤔', back: 'le visage pensif' },
  { front: '🤫', back: 'chut' },
  { front: '🫢', back: 'la main sur la bouche' },
  { front: '🤭', back: 'le visage avec la main sur la bouche' },
  { front: '🥱', back: 'le bâillement' },
  { front: '🤗', back: 'les mains câlines' },
  { front: '🫣', back: 'le visage qui regarde à travers les doigts' },
  { front: '🤨', back: 'le sourcil levé' },
  { front: '🧐', back: 'le visage avec un monocle' },
  { front: '😒', back: 'le visage boudeur' },
  { front: '🙄', back: 'les yeux au ciel' },
  { front: '😮‍💨', back: 'le souffle' },
  { front: '😤', back: 'le visage avec de la vapeur sortant du nez' },
  { front: '🤬', back: 'le visage avec des symboles sur la bouche' },
  { front: '😞', back: 'le visage déçu' },
  { front: '😓', back: 'le visage abattu avec une sueur froide' },
  { front: '😟', back: 'le visage inquiet' },
  { front: '😥', back: 'le visage triste mais soulagé' },
  { front: '☹️', back: 'le visage froncé' },
  { front: '🙁', back: 'le visage légèrement fronçé' },
  { front: '🫤', back: 'le visage avec une bouche diagonale' },
  { front: '😕', back: 'le visage confus' },
  { front: '😰', back: 'le visage inquiet avec une sueur froide' },
  { front: '😨', back: 'le visage effrayé' },
  { front: '😧', back: 'le visage angoissé' },
  { front: '😦', back: 'le visage ébahi' },
  { front: '😮', back: 'le visage avec la bouche ouverte' },
  { front: '😯', back: 'le visage surpris' },
  { front: '😲', back: 'le visage estomaqué' },
  { front: '😳', back: 'le visage rougi' },
  { front: '🤯', back: 'la tête qui explose' },
  { front: '😖', back: 'le visage crispé' },
  { front: '😣', back: 'le visage persévérant' },
  { front: '😩', back: 'le visage fatigué' },
  { front: '😫', back: 'le visage the fatigue' },
  { front: '😵', back: 'le visage étourdi' },
  { front: '😵‍💫', back: 'le visage avec des yeux en spirale' },
  { front: '🫨', back: 'le visage qui tremble' },
  { front: '🥴', back: 'le visage étourdi et éméché' },
  { front: '🥵', back: 'le visage chaud' },
  { front: '🥶', back: 'le visage froid' },
  { front: '🤢', back: 'le visage nauséeux' },
  { front: '🤮', back: 'le visage vomissant' },
  { front: '🫩', back: 'le visage retenant ses larmes' },
  { front: '😪', back: 'le visage endormi' },
  { front: '🤧', back: 'le visage éternuant' },
  { front: '🤒', back: 'le visage avec un thermomètre' },
  { front: '🤕', back: 'le visage avec un bandage' },
  { front: '😷', back: 'le visage avec un masque médical' },
  { front: '🤥', back: 'le visage menteur' },
  { front: '😇', back: 'le visage angélique' },
  { front: '🤠', back: 'le visage avec un chapeau de cowboy' },
  { front: '🤑', back: 'le visage avec des signes dollar' },
  { front: '🤓', back: 'le visage intello' },
  { front: '🥸', back: 'le visage déguisé' },
  { front: '🤡', back: 'le clown' },
  { front: '😈', back: 'le visage souriant avec des cornes' },
  { front: '👿', back: 'le diablotin' },
  { front: '☠️', back: 'le crâne et os' },
  { front: '👹', back: 'l’ogre japonais' },
  { front: '👺', back: 'le gobelin japonais' },
  { front: '👾', back: 'le monstre extraterrestre' },
  { front: '☃️', back: 'le bonhomme de neige' },
  { front: '⛄', back: 'le bonhomme de neige sans neige' },
  { front: '🌚', back: 'la nouvelle lune avec visage' },
  { front: '🌝', back: 'la pleine lune avec visage' },
  { front: '🌞', back: 'le soleil avec visage' },
  { front: '🌛', back: 'le dernier quartier de lune avec visage' },
  { front: '🌜', back: 'le premier quartier de lune avec visage' },
{ front: '😺', back: 'le chat souriant' },
  { front: '😸', back: 'le chat souriant avec les yeux plissés' },
  { front: '😹', back: 'le chat pleurant de joie' },
  { front: '😻', back: 'le chat avec des yeux en cœur' },
  { front: '😼', back: 'le chat souriant en coin' },
  { front: '😽', back: 'le chat faisant un bisou' },
  { front: '🙀', back: 'le chat fatigué' },
  { front: '😿', back: 'le chat pleurant' },
  { front: '😾', back: 'le chat boudeur' },
  { front: '💫', back: 'les vertiges' },
  { front: '💥', back: 'la collision' },
  { front: '🫯', back: 'les empreintes digitales' },
  { front: '💢', back: 'la colère' },
  { front: '💨', back: 'le coup de vent' },
  { front: '💤', back: 'le sommeil' },
  { front: '💯', back: 'les cent points' },
  { front: '🎊', back: 'la confiture de fête' },
  { front: '❤️', back: 'le cœur rouge' },
  { front: '🧡', back: 'le cœur orange' },
  { front: '💛', back: 'le cœur jaune' },
  { front: '💚', back: 'le cœur vert' },
  { front: '🩵', back: 'le cœur bleu clair' },
  { front: '💙', back: 'le cœur bleu' },
  { front: '💜', back: 'le cœur violet' },
  { front: '🤎', back: 'le cœur marron' },
  { front: '🖤', back: 'le cœur noir' },
  { front: '🩶', back: 'le cœur gris' },
  { front: '🤍', back: 'le cœur blanc' },
  { front: '🩷', back: 'le cœur rose' },
  { front: '💘', back: 'le cœur fléché' },
  { front: '💝', back: 'le cœur avec un ruban' },
  { front: '💖', back: 'le cœur étincelant' },
  { front: '💗', back: 'le cœur battant' },
  { front: '💓', back: 'le cœur qui palpite' },
  { front: '💞', back: 'les cœurs tournants' },
  { front: '💕', back: 'les deux cœurs' },
  { front: '💌', back: 'la lettre d’amour' },
  { front: '💟', back: 'la décoration de cœur' },
  { front: '♥️', back: 'l’enseigne cœur' },
  { front: '❣️', back: 'le point d’exclamation en cœur' },
  { front: '❤️‍🩹', back: 'le cœur panse' },
  { front: '💔', back: 'le cœur brisé' },
  { front: '❤️‍🔥', back: 'le cœur en feu' },
  { front: '💋', back: 'la marque de baiser' },
  { front: '🫂', back: 'les personnes qui se câlinent' },
  { front: '👥', back: 'les silhouettes de profil' },
  { front: '👤', back: 'la silhouette' },
  { front: '🗣️', back: 'la tête qui parle' },
  { front: '👣', back: 'les empreintes de pas' },
  { front: '🫆', back: 'l’empreinte de pouce' },
  { front: '💦', back: 'les éclaboussures de sueur' },
  { front: '🧠', back: 'le cerveau' },
  { front: '🫀', back: 'le cœur anatomique' },
  { front: '🫁', back: 'les poumons' },
  { front: '🩸', back: 'la goutte de sang' },
  { front: '🦠', back: 'le microbe' },
  { front: '🦷', back: 'la dent' },
  { front: '🦴', back: 'l’os' },
  { front: '👀', back: 'les yeux' },
  { front: '👁️', back: 'l’œil' },
  { front: '👄', back: 'la bouche' },
  { front: '🫦', back: 'les lèvres mordues' },
  { front: '👅', back: 'la langue' },
  { front: '👃🏻', back: 'le nez' },
  { front: '👂🏻', back: 'l’oreille' },
  { front: '🦻🏻', back: 'l’oreille avec un appareil auditif' },
  { front: '🦶🏻', back: 'le pied' },
  { front: '🦵🏻', back: 'la jambe' },
  { front: '🦿', back: 'la jambe mécanique' },
  { front: '🦾', back: 'le bras mécanique' },
  { front: '💪🏻', back: 'le biceps fléchi' },
  { front: '👏🏻', back: 'les mains qui applaudissent' },
  { front: '👍🏻', back: 'le pouce levé' },
  { front: '👎🏻', back: 'le pouce baissé' },
  { front: '🫶🏻', back: 'les mains en forme de cœur' },
  { front: '🙌🏻', back: 'les mains levées' },
  { front: '👐🏻', back: 'les mains ouvertes' },
  { front: '🤲🏻', back: 'les mains jointes vers le haut' },
  { front: '🤜🏻', back: 'le poing vers la droite' },
  { front: '🤛🏻', back: 'le poing vers la gauche' },
  { front: '✊🏻', back: 'le poing levé' },
  { front: '👊🏻', back: 'le coup de poing' },
  { front: '🫳🏻', back: 'la main paume vers le bas' },
  { front: '🫴🏻', back: 'la main paume vers le haut' },
  { front: '🫱🏻', back: 'la main tendue vers la droite' },
  { front: '🫲🏻', back: 'la main tendue vers la gauche' },
  { front: '🫸🏻', back: 'la main poussant vers la droite' },
  { front: '🫷🏻', back: 'la main poussant vers la gauche' },
  { front: '👋🏻', back: 'la main qui fait coucou' },
  { front: '🤚🏻', back: 'le dos de la main' },
  { front: '🖐🏻', back: 'la main écartée' },
  { front: '✋🏻', back: 'la main levée' },
  { front: '🖖🏻', back: 'le salut vulcain' },
  { front: '🤟🏻', back: 'le signe je t’aime' },
  { front: '🤘🏻', back: 'le signe des cornes' },
  { front: '✌🏻', back: 'le signe de la victoire' },
  { front: '🤞🏻', back: 'les doigts croisés' },
  { front: '🫰🏻', back: 'le cœur avec les doigts' },
  { front: '🤙🏻', back: 'le signe du combiné téléphonique' },
  { front: '🤌🏻', back: 'les doigts pincés' },
  { front: '🤏🏻', back: 'la main pinçant' },
  { front: '👌🏻', back: 'le signe OK' },
  { front: '🫵🏻', back: 'l’index pointé vers l’utilisateur' },
  { front: '👉🏻', back: 'l’index pointé vers la droite' },
  { front: '👈🏻', back: 'l’index pointé vers la gauche' },
  { front: '☝🏻', back: 'l’index pointé vers le haut' },
  { front: '👆🏻', back: 'le doigt pointé vers le haut' },
  { front: '👇🏻', back: 'le doigt pointé vers le bas' },
  { front: '✍🏻', back: 'la main en train d’écrire' },
  { front: '🤳🏻', back: 'le selfie' },
  { front: '🙏🏻', back: 'les mains en prière' },
  { front: '💅🏻', back: 'le vernis à ongles' },
  { front: '🤝🏻', back: 'la poignée de main' },


  // --- 道具・小物・その他 (Objets & Divers) ---
  { front: '🎉', back: 'les confettis' },
  { front: '🧭', back: 'la boussole' },
  { front: '🎡', back: 'la grande roue' },
  { front: '💍', back: 'la bague' },
  { front: '🛡️', back: 'le bouclier' },
  { front: '🗡️', back: "l'épée" },
  { front: '⚰️', back: 'le cercueil' },
  { front: '🪦', back: 'la tombe' },
  { front: '🗝️', back: 'la vieille clé' },
  { front: '💻', back: 'l’ordinateur' },
  { front: '📱', back: 'le téléphone' },
  { front: '📷', back: 'l’appareil photo' },
  { front: '📚', back: 'les livres' },
  { front: '✏️', back: 'le crayon' },
  { front: '🎨', back: 'la palette de peinture' },
  { front: '🎸', back: 'la guitare' },
  { front: '⚽', back: 'le ballon de football' },
  { front: '🚗', back: 'la voiture' },
  { front: '✈️', back: 'l’avion' },
  { front: '🚀', back: 'la fusée' },
  { front: '⏰', back: 'le réveil' },
  { front: '🎁', back: 'le cadeau' },
  { front: '🎈', back: 'le ballon' },
  { front: '💡', back: 'l’ampoule' },
  { front: '🔑', back: 'la clé' },
  { front: '🔒', back: 'le cadenas' },
  { front: '🎊', back: 'les confettis' },
  { front: '🎀', back: 'le ruban' },
  { front: '🎇', back: 'les feux d’artifice' },
  { front: '🎆', back: 'le feu d’artifice' },
  { front: '🧨', back: 'le pétard' },
  { front: '🧧', back: 'l’enveloppe rouge' },
  { front: '🪔', back: 'la lampe à huile' },
  { front: '🪅', back: 'la piñata' },
  { front: '🪩', back: 'la boule à facettes' },
  { front: '🎐', back: 'le carillon éolien' },
  { front: '🎏', back: 'les manchons de carpe' },
  { front: '🎎', back: 'les poupées japonaises' },
  { front: '🎑', back: 'la cérémonie de la lune' },
  { front: '🎍', back: 'la décoration de pin' },
  { front: '🎋', back: 'l’arbre à vœux' },
  { front: '🎄', back: 'l’arbre de Noël' },
  { front: '🎃', back: 'la citrouille d’Halloween' },
  { front: '🎗️', back: 'le ruban de sensibilisation' },
  { front: '🥇', back: 'la médaille d’or' },
  { front: '🥈', back: 'la médaille d’argent' },
  { front: '🥉', back: 'la médaille de bronze' },
  { front: '🏅', back: 'la médaille sportive' },
  { front: '🎖️', back: 'la médaille militaire' },
  { front: '🏆', back: 'le trophée' },
  { front: '📢', back: 'le haut-parleur' },
  { front: '⚾', back: 'la balle de baseball' },
  { front: '🥎', back: 'la balle de softball' },
  { front: '🏀', back: 'le ballon de basketball' },
  { front: '🏐', back: 'le ballon de volleyball' },
  { front: '🏈', back: 'le ballon de football américain' },
  { front: '🏉', back: 'le ballon de rugby' },
  { front: '🥅', back: 'le filet de but' },
  { front: '🎾', back: 'la balle de tennis' },
  { front: '🏸', back: 'le badminton' },
  { front: '🥍', back: 'la crosse' },
  { front: '🏏', back: 'le cricket' },
  { front: '🏑', back: 'le hockey sur gazon' },
  { front: '🏒', back: 'le hockey sur glace' },
  { front: '🥌', back: 'la pierre de curling' },
  { front: '🛷', back: 'le luge' },
  { front: '🎿', back: 'les skis' },
  { front: '⛸️', back: 'le patin à glace' },
  { front: '🛼', back: 'le patin à roulettes' },
  { front: '🩰', back: 'les chaussons de danse' },
  { front: '🛹', back: 'le skateboard' },
  { front: '⛳', back: 'le drapeau dans le trou' },
  { front: '🎯', back: 'la cible' },
  { front: '🏹', back: 'l’arc et la flèche' },
  { front: '🥏', back: 'le freesbee' },
  { front: '🪃', back: 'le boomerang' },
  { front: '🪁', back: 'le cerf-volant' },
  { front: '🎣', back: 'la canne à pêche' },
  { front: '🤿', back: 'le masque de plongée' },
  { front: '🩱', back: 'le maillot de bain une pièce' },
  { front: '🎽', back: 'le maillot de corps' },
  { front: '🥋', back: 'l’uniforme d’arts martiaux' },
  { front: '🥊', back: 'le gant de boxe' },
  { front: '🎱', back: 'la boule de billard' },
  { front: '🏓', back: 'le tennis de table' },
  { front: '🎳', back: 'le bowling' },
  { front: '♟️', back: 'le pion d’échecs' },
  { front: '🪀', back: 'le yoyo' },
  { front: '🧩', back: 'la pièce de puzzle' },
  { front: '🎮', back: 'la manette de jeu' },
  { front: '🕹️', back: 'le joystick' },
  { front: '👾', back: 'le monstre de jeu vidéo' },
  { front: '🔫', back: 'le pistolet à eau' },
  { front: '🎲', back: 'le dé' },
  { front: '🎰', back: 'la machine à sous' },
  { front: '🎴', back: 'les cartes hanafuda' },
  { front: '🀄', back: 'le mahjong' },
  { front: '🃏', back: 'le joker' },
  { front: '🪄', back: 'la baguette magique' },
  { front: '🎩', back: 'le chapeau haut de forme' },
  { front: '📸', back: 'l’appareil photo avec flash' },
  { front: '🖼️', back: 'le tableau encadré' },
  { front: '🫟', back: 'le pinceau et la palette' },
  { front: '🖌️', back: 'le pinceau' },
  { front: '🖍️', back: 'le crayon cire' },
  { front: '🪡', back: 'l’aiguille à coudre' },
  { front: '🧵', back: 'le fil à coudre' },
  { front: '🧶', back: 'la pelote de laine' },
  { front: '🎹', back: 'le piano' },
  { front: '🎷', back: 'le saxophone' },
  { front: '🎺', back: 'la trompette' },
  { front: '🪊', back: 'le maracas' },
  { front: '🪕', back: 'le banjo' },
  { front: '🎻', back: 'le violon' },
  { front: '🪉', back: 'la harpe' },
  { front: '🪘', back: 'le tambour long' },
  { front: '🥁', back: 'la batterie' },
  { front: '🪇', back: 'les maracas' },
  { front: '🪈', back: 'la flûte' },
  { front: '🪗', back: 'l’accordéon' },
  { front: '🎤', back: 'le microphone' },
  { front: '🎧', back: 'le casque audio' },
  { front: '🎚️', back: 'le curseur de volume' },
  { front: '🎛️', back: 'les boutons de réglage' },
  { front: '🎙️', back: 'le microphone de studio' },
  { front: '📼', back: 'la cassette vidéo' },
  { front: '📻', back: 'la radio' },
  { front: '📺', back: 'la télévision' },
  { front: '📹', back: 'la caméra vidéo' },
  { front: '📽️', back: 'le projecteur de cinéma' },
  { front: '🎥', back: 'la caméra de cinéma' },
  { front: '🎞️', back: 'la pellicule' },
  { front: '🎬', back: 'le clap de cinéma' },
  { front: '🎭', back: 'les masques de théâtre' },
  { front: '🎫', back: 'le billet' },
  { front: '🎟️', back: 'les tickets d’entrée' },
  { front: '☎️', back: 'le téléphone fixe' },
  { front: '📞', back: 'le combiné téléphonique' },
  { front: '📟', back: 'le bip' },
  { front: '📠', back: 'le fax' },
  { front: '🔌', back: 'la prise électrique' },
  { front: '🔋', back: 'la pile' },
  { front: '🪫', back: 'la batterie faible' },
  { front: '🖲️', back: 'le trackball' },
  { front: '💽', back: 'le mini-disque' },
  { front: '💾', back: 'la disquette' },
  { front: '💿', back: 'le disque optique' },
  { front: '📀', back: 'le DVD' },
  { front: '🖥️', back: 'l’ordinateur de bureau' },
  { front: '⌨️', back: 'le clavier' },
  { front: '🖨️', back: 'l’imprimante' },
  { front: '🖱️', back: 'la souris d’ordinateur' },
  { front: '🪎', back: 'le boulier' },
  { front: '🪙', back: 'la pièce de monnaie' },
  { front: '💸', back: 'l’argent qui s’envole' },
  { front: '💵', back: 'le billet de banque' },
  { front: '💴', back: 'le yen' },
  { front: '💶', back: 'l’euro' },
  { front: '💷', back: 'la livre sterling' },
  { front: '💳', back: 'la carte bancaire' },
  { front: '💰', back: 'le sac d’argent' },
  { front: '🧾', back: 'le reçu' },
  { front: '🧮', back: 'le boulier' },
  { front: '⚖️', back: 'la balance' },
  { front: '🛒', back: 'le chariot de courses' },
  { front: '🛍️', back: 'les sacs d’achats' },
  { front: '🕯️', back: 'la bougie' },
  { front: '🔦', back: 'la lampe de poche' },
  { front: '🏮', back: 'la lanterne rouge' },
  { front: '🧱', back: 'la brique' },
  { front: '🪟', back: 'la fenêtre' },
  { front: '🪞', back: 'le miroir' },
  { front: '🚪', back: 'la porte' },
  { front: '🪑', back: 'la chaise' },
  { front: '🛏️', back: 'le lit' },
  { front: '🛋️', back: 'le canapé' },
  { front: '🚿', back: 'la douche' },
  { front: '🛁', back: 'la baignoire' },
  { front: '🚽', back: 'les toilettes' },
  { front: '🧻', back: 'le papier toilette' },
  { front: '🪠', back: 'la ventouse' },
  { front: '🪆', back: 'les poupées russes' },
  { front: '🧷', back: 'l’épingle à nourrice' },
  { front: '🪢', back: 'le nœud' },
  { front: '🧹', back: 'le balai' },
  { front: '🧴', back: 'le flacon' },
  { front: '🧽', back: 'l’éponge' },
  { front: '🧼', back: 'le savon' },
  { front: '🪥', back: 'la brosse à dents' },
  { front: '🪒', back: 'le rasoir' },
  { front: '🪮', back: 'le peigne' },
  { front: '🧺', back: 'le panier' },
  { front: '🧦', back: 'les chaussettes' },
  { front: '🧤', back: 'les gants' },
  { front: '🧣', back: 'l’écharpe' },
  { front: '👖', back: 'le jean' },
  { front: '👕', back: 'le t-shirt' },
  { front: '🎽', back: 'le maillot de corps' },
  { front: '👚', back: 'le haut pour femme' },
  { front: '👔', back: 'la cravate' },
  { front: '👗', back: 'la robe' },
  { front: '👘', back: 'le kimono' },
  { front: '🥻', back: 'le sari' },
  { front: '🩱', back: 'le maillot de bain' },
  { front: '👙', back: 'le bikini' },
  { front: '🩳', back: 'le short' },
  { front: '🩲', back: 'le slip' },
  { front: '🧥', back: 'le manteau' },
  { front: '🥼', back: 'la blouse de laboratoire' },
  { front: '🦺', back: 'le gilet de sécurité' },
  { front: '⛑️', back: 'le casque de secours' },
  { front: '🪖', back: 'le casque militaire' },
  { front: '🎓', back: 'le mortier (chapeau de diplômé)' },
  { front: '🎩', back: 'le chapeau haut de forme' },
  { front: '👒', back: 'le chapeau de femme' },
  { front: '🧢', back: 'la casquette' },
  { front: '👑', back: 'la couronne' },
  { front: '💄', back: 'le rouge à lèvres' },
  { front: '🪭', back: 'l’éventail' },
  { front: '🎒', back: 'le sac à dos' },
  { front: '👝', back: 'la pochette' },
  { front: '👛', back: 'le porte-monnaie' },
  { front: '👜', back: 'le sac à main' },
  { front: '💼', back: 'la mallette' },
  { front: '🧳', back: 'la valise' },
  { front: '☂️', back: 'le parapluie ouvert' },
  { front: '🌂', back: 'le parapluie fermé' },
  { front: '🥾', back: 'la chaussure de randonnée' },
  { front: '👢', back: 'la botte' },
  { front: '👠', back: 'l’escarpin' },
  { front: '🩴', back: 'la tong' },
  { front: '👟', back: 'la sneaker' },
  { front: '👞', back: 'la chaussure de ville' },
  { front: '🥿', back: 'la chaussure plate' },
  { front: '👡', back: 'la sandale' },
  { front: '🦯', back: 'la canne blanche' },
  { front: '🕶️', back: 'les lunettes de soleil' },
  { front: '👓', back: 'les lunettes' },
  { front: '🥽', back: 'les lunettes de protection' },
  { front: '⚗️', back: 'l’alambic' },
  { front: '🧫', back: 'la boîte de Petri' },
  { front: '🧪', back: 'le tube à essai' },
  { front: '🌡️', back: 'le thermomètre' },
  { front: '💉', back: 'la seringue' },
  { front: '💊', back: 'la pilule' },
  { front: '🩹', back: 'le pansement' },
  { front: '🩺', back: 'le stéthoscope' },
  { front: '🩻', back: 'la radiographie' },
  { front: '🧬', back: 'l’ADN' },
  { front: '🔭', back: 'le télescope' },
  { front: '🔬', back: 'le microscope' },
  { front: '📡', back: 'l’antenne parabolique' },
  { front: '🛰️', back: 'le satellite' },
  { front: '🧯', back: 'l’extincteur' },
  { front: '🪓', back: 'la hache' },
  { front: '🪜', back: 'l’echelle' },
  { front: '🪣', back: 'le seau' },
  { front: '🪝', back: 'le crochet' },
  { front: '🧲', back: 'l’aimant' },
  { front: '🧰', back: 'la boîte à outils' },
  { front: '🗜️', back: 'l’étau' },
  { front: '🔩', back: 'le boulon et l’écrou' },
  { front: '🪛', back: 'le tournevis' },
  { front: '🪚', back: 'la scie' },
  { front: '🔧', back: 'la clé anglaise' },
  { front: '🔨', back: 'le marteau' },
  { front: '🛠️', back: 'les outils' },
  { front: '⚒️', back: 'le marteau et la pioche' },
  { front: '⛏️', back: 'la pioche' },
  { front: '🪏', back: 'la pelle' },
  { front: '⚙️', back: 'l’engrenage' },
  { front: '⛓️‍💥', back: 'la chaîne cassée' },
  { front: '🔗', back: 'les maillons' },
  { front: '⛓️', back: 'la chaîne' },
  { front: '📎', back: 'le trombone' },
  { front: '🖇️', back: 'les trombones liés' },
  { front: '✂️', back: 'les ciseaux' },
  { front: '📏', back: 'la règle' },
  { front: '📐', back: 'l’équerre' },
  { front: '🖌️', back: 'le pinceau' },
  { front: '🖍️', back: 'le crayon de cire' },
  { front: '🖊️', back: 'le stylo à bille' },
  { front: '🖋️', back: 'le stylo plume' },
  { front: '✒️', back: 'la plume d’écriture' },
  { front: '📝', back: 'le mémo' },
  { front: '🗒️', back: 'le bloc-notes spirale' },
  { front: '📄', back: 'la page' },
  { front: '📃', back: 'la page courbée' },
  { front: '📑', back: 'les signets' },
  { front: '📋', back: 'le presse-papiers' },
  { front: '🗃️', back: 'la boîte à fiches' },
  { front: '🗄️', back: 'le meuble classeur' },
  { front: '📒', back: 'le grand cahier' },
  { front: '📔', back: 'le carnet' },
  { front: '📕', back: 'le livre fermé rouge' },
  { front: '📓', back: 'le cahier' },
  { front: '📗', back: 'le livre vert' },
  { front: '📘', back: 'le livre bleu' },
  { front: '📙', back: 'le livre orange' },
  { front: '📖', back: 'le livre ouvert' },
  { front: '🔖', back: 'le signet' },
  { front: '📂', back: 'le dossier ouvert' },
  { front: '📁', back: 'le dossier fermé' },
  { front: '🗂️', back: 'les onglets de classement' },
  { front: '📊', back: 'le graphique en barres' },
  { front: '📈', back: 'la courbe ascendante' },
  { front: '📉', back: 'la courbe descendante' },
  { front: '📇', back: 'le fichier rotatif' },
  { front: '🪪', back: 'la carte d’identité' },
  { front: '📌', back: 'la punaise' },
  { front: '📍', back: 'la punaise ronde' },
  { front: '🗑️', back: 'la corbeille à papier' },
  { front: '📰', back: 'le journal' },
  { front: '🗞️', back: 'le journal roulé' },
  { front: '🏷️', back: 'l’étiquette' },
  { front: '📤', back: 'la boîte d’envoi' },
  { front: '📥', back: 'la boîte de réception' },
  { front: '📩', back: 'l’enveloppe avec une flèche' },
  { front: '📨', back: 'l’enveloppe entrante' },
  { front: '✉️', back: 'l’enveloppe' },
  { front: '💌', back: 'la lettre d’amour' },
  { front: '📧', back: 'l’e-mail' },
  { front: '📫', back: 'la boîte aux lettres ouverte (drapeau levé)' },
  { front: '📪', back: 'la boîte aux lettres fermée (drapeau baissé)' },
  { front: '📬', back: 'la boîte aux lettres ouverte (drapeau baissé)' },
  { front: '📭', back: 'la boîte aux lettres fermée (drapeau levé)' },
  { front: '📦', back: 'le colis' },
  { front: '📯', back: 'le cor postal' },
  { front: '📮', back: 'la boîte aux lettres publique' },
  { front: '🗳️', back: 'l’urne' },
  { front: '📅', back: 'le calendrier' },
  { front: '📆', back: 'le calendrier détachable' },
  { front: '🗓️', back: 'le bloc-calendrier' },
  { front: '🪧', back: 'la pancarte' },
  { front: '⏰', back: 'le réveil' },
  { front: '🕰️', back: 'la pendule' },
  { front: '⌛', back: 'le sablier' },
  { front: '⏳', back: 'le sablier qui s’écoule' },
  { front: '⏲️', back: 'la minuterie' },
  { front: '⌚', back: 'la montre' },
  { front: '⏱️', back: 'le chronomètre' },
  { front: '🕛', back: 'midi / minuit' },
  { front: '🕧', back: 'midi et demi' },
  { front: '🕐', back: 'une heure' },
  { front: '🕜', back: 'une heure et demie' },
  { front: '🕑', back: 'deux heures' },
  { front: '🕝', back: 'deux heures et demie' },
  { front: '🕒', back: 'trois heures' },
  { front: '🕞', back: 'trois heures et demie' },
  { front: '🕓', back: 'quatre heures' },
  { front: '🕟', back: 'quatre heures et demie' },
  { front: '🕔', back: 'cinq heures' },
  { front: '🕠', back: 'cinq heures et demie' },
  { front: '🕕', back: 'six heures' },
  { front: '🕡', back: 'six heures et demie' },
  { front: '🕖', back: 'sept heures' },
  { front: '🕢', back: 'sept heures et demie' },
  { front: '🕗', back: 'huit heures' },
  { front: '🕣', back: 'huit heures et demie' },
  { front: '🕘', back: 'neuf heures' },
  { front: '🕤', back: 'neuf heures et demie' },
  { front: '🕙', back: 'dix heures' },
  { front: '🕥', back: 'dix heures et demie' },
  { front: '🕚', back: 'onze heures' },
  { front: '🕦', back: 'onze heures et demie' },
  { front: '🛎️', back: 'la cloche d’appel' },
  { front: '🔔', back: 'la cloche' },
  { front: '🔈', back: 'le haut-parleur silencieux' },
  { front: '🔉', back: 'le haut-parleur moyen' },
  { front: '🔊', back: 'le haut-parleur fort' },
  { front: '📢', back: 'le porte-voix' },
  { front: '📣', back: 'le méga-aphone' },
  { front: '🔍', back: 'la loupe orientée vers la gauche' },
  { front: '🔎', back: 'la loupe orientée vers la droite' },
  { front: '🔮', back: 'la boule de cristal' },
  { front: '🧿', back: 'l’œil turc' },
  { front: '🪬', back: 'la hamsa' },
  { front: '📿', back: 'le chapelet' },
  { front: '🏺', back: 'la jarre' },
  { front: '⚱️', back: 'l’urne funéraire' },
  { front: '🚬', back: 'la cigarette' },
  { front: '💣', back: 'la bombe' },
  { front: '🪤', back: 'la souricière' },
  { front: '📜', back: 'le parchemin' },
  { front: '⚔️', back: 'les épées croisées' },
  { front: '🛡️', back: 'le bouclier' },
  { front: '🔏', back: 'le cadenas avec un stylo' },
  { front: '🔓', back: 'le cadenas ouvert' },

  // --- 職業・人物 (Métiers & Personnes) ---
  { front: '👩🏻‍🎨', back: "l'artiste" },
  { front: '👩🏻‍🍳', back: 'la cuisinière' },
  { front: '👩🏻‍🚒', back: 'la pompière' },
  { front: '👩🏻‍🌾', back: "l'agricultrice" },
  { front: '👩🏻‍✈️', back: 'la pilote' },
  { front: '👩🏻‍🎓', back: "l'étudiante" },
  { front: '👩🏻‍🎤', back: 'la chanteuse' },
  { front: '👩🏻‍⚖️', back: 'la juge' },
  { front: '🙇🏻‍♀️', back: 'la femme qui s’incline' },
  { front: '🙋🏻‍♀️', back: 'la femme qui lève la main' },
  { front: '💁🏻‍♀️', back: 'la femme qui fait un geste d’information' },
  { front: '🙆🏻‍♀️', back: 'la femme faisant le signe OK' },
  { front: '🙅🏻‍♀️', back: 'la femme faisant le signe NON' },
  { front: '🤷🏻‍♀️', back: 'la femme qui haussa les épaules' },
  { front: '🤦🏻‍♀️', back: 'la femme se prenant la tête' },
  { front: '🙍🏻‍♀️', back: 'la femme froncée' },
  { front: '🙎🏻‍♀️', back: 'la femme boudeuse' },
  { front: '🧏🏻‍♀️', back: 'la femme sourde' },
  { front: '💆🏻‍♀️', back: 'la femme se faisant masser' },
  { front: '💇🏻‍♀️', back: 'la femme chez le coiffeur' },
  { front: '🧖🏻‍♀️', back: 'la femme au sauna' },
  { front: '🛀🏻', back: 'la femme dans son bain' },
  { front: '🛌🏻', back: 'la femme au lit' },
  { front: '🧘🏻‍♀️', back: 'la femme en méditation' },
  { front: '🧍🏻‍♀️', back: 'la femme debout' },
  { front: '🤸🏻‍♀️', back: 'la femme faisant la roue' },
  { front: '🧎🏻‍♀️', back: 'la femme à genoux' },
  { front: '👩🏻‍🦼', back: 'la femme en fauteuil roulant électrique' },
  { front: '👩🏻‍🦽', back: 'la femme en fauteuil roulant manuel' },
  { front: '👩🏻‍🦯', back: 'la femme avec une canne blanche' },
  { front: '🚶🏻‍♀️', back: 'la femme qui marche' },
  { front: '🏃🏻‍♀️', back: 'la femme qui court' },
  { front: '⛹🏻‍♀️', back: 'la femme jouant au ballon' },
  { front: '🤾🏻‍♀️', back: 'la femme jouant au handball' },
  { front: '🚴🏻‍♀️', back: 'la femme à vélo' },
  { front: '🚵🏻‍♀️', back: 'la femme faisant du VTT' },
  { front: '🧗🏻‍♀️', back: 'la femme qui escalade' },
  { front: '🏋🏻‍♀️', back: 'la femme soulevant des poids' },
  { front: '🤼', back: 'la lutte' },
  { front: '🤼‍♂️', back: 'les lutteurs' },
  { front: '🤼‍♀️', back: 'les lutteuses' },
  { front: '🤹🏻‍♀️', back: 'la femme jonglant' },
  { front: '🏌🏻‍♀️', back: 'la femme jouant au golf' },
  { front: '🏇🏻', back: 'la course de chevaux' },
  { front: '🤺', back: 'l’escrime' },
  { front: '⛷️', back: 'le skieur' },
  { front: '🏂🏻', back: 'la femme faisant du snowboard' },
  { front: '🪂', back: 'le parachute' },
  { front: '🏄🏻‍♀️', back: 'la femme faisant du surf' },
  { front: '🚣🏻‍♀️', back: 'la femme ramant' },
  { front: '🏊🏻‍♀️', back: 'la femme nageant' },
  { front: '🤽🏻‍♀️', back: 'la femme jouant au water-polo' },
  { front: '🧜🏻‍♀️', back: 'la sirène' },
  { front: '🧚🏻‍♀️', back: 'la fée' },
  { front: '🧞‍♀️', back: 'le génie féminin' },
  { front: '🧝🏻‍♀️', back: 'l’elfe féminin' },
  { front: '🧙🏻‍♀️', back: 'la sorcière' },
  { front: '🧛🏻‍♀️', back: 'la vampire' },
  { front: '🧟‍♀️', back: 'le zombie féminin' },
  { front: '🧌', back: 'le troll' },
  { front: '🫈', back: 'la personne neutre avec une couronne' },
  { front: '🦸🏻‍♀️', back: 'la super-héroïne' },
  { front: '🦹🏻‍♀️', back: 'la super-vilaine' },
  { front: '🤶🏻', back: 'la mère Noël' },
  { front: '🥷🏻', back: 'le ninja' },
  { front: '💂🏻‍♀️', back: 'la garde féminine' },
  { front: '👸🏻', back: 'la princesse' },
  { front: '🤵🏻‍♀️', back: 'la femme en smoking' },
  { front: '👰🏻‍♀️', back: 'la mariée' },
  { front: '👩🏻‍🚀', back: 'l’astronaut féminin' },
  { front: '👷🏻‍♀️', back: 'la femme de chantier' },
  { front: '👮🏻‍♀️', back: 'la policière' },
  { front: '🕵🏻‍♀️', back: 'la détective' },
  { front: '👩🏻‍🔬', back: 'la scientifique' },
  { front: '👩🏻‍⚕️', back: 'la femme médecin' },
  { front: '👩🏻‍🔧', back: 'la mécanicienne' },
  { front: '👩🏻‍🏭', back: 'la ouvrière d’usine' },
  { front: '👩🏻‍🏫', back: 'la professeure' },
  { front: '👩🏻‍💼', back: 'la femme cadre' },
  { front: '👩🏻‍💻', back: 'la développeuse' },
  { front: '👳🏻‍♀️', back: 'la femme avec un turban' },
  { front: '🧕🏻', back: 'la femme avec un foulard' },
  { front: '👲🏻', back: 'la personne avec un bonnet chinois' },
  { front: '👼🏻', back: 'le petit ange' },
  { front: '👶🏻', back: 'le bébé' },
  { front: '👧🏻', back: 'la fillette' },
  { front: '👩🏻', back: 'la femme' },
  { front: '👵🏻', back: 'la femme âgée' },
  { front: '👩🏻‍🦳', back: 'la femme aux cheveux blancs' },
  { front: '👩🏻‍🦰', back: 'la femme aux cheveux roux' },
  { front: '👱🏻‍♀️', back: 'la femme blonde' },
  { front: '👩🏻‍🦱', back: 'la femme aux cheveux bouclés' },
  { front: '👩🏻‍🦲', back: 'la femme chauve' },
  { front: '🧔🏻‍♀️', back: 'la femme avec une barbe' },
  { front: '🕴🏻', back: 'l’homme en costume en train de léviter' },
  { front: '🧑🏻‍🩰', back: 'la personne qui danse le ballet' },
  { front: '💃🏻', back: 'la danseuse' },
  { front: '🕺🏻', back: 'le danseur' },
  { front: '👯', back: 'les personnes avec des oreilles de lapin' },
  { front: '🤰🏻', back: 'la femme enceinte' },
  { front: '🤱🏻', back: 'l’allaitement' },
  { front: '👩🏻‍🍼', back: 'la femme nourrissant un bébé' }
];
