window.French = [
  // --- 動物・生き物 (Animaux) ---
  { front: '🐺', back: 'le loup' },
  { front: '🦊', back: 'le renard' },
  { front: '🐯', back: 'le tigre' },
  { front: '🦁', back: 'le lion' },
  { front: '🦇', back: 'la chauve-souris' },
  { front: '🐵', back: 'le singe' },
  { front: '🦉', back: 'le hibou' },
  { front: '🐢', back: 'la tortue' },
  { front: '🐻‍❄️', back: "l'ours polaire" },
  { front: '🐨', back: 'le koala' },
  { front: '🐴', back: 'le cheval' },
  { front: '🐹', back: 'le hamster' },
  { front: '🦓', back: 'le zèbre' },
  { front: '🐑', back: 'le mouton' },
  { front: '🐖', back: 'le cochon' },
  { front: '🐄', back: 'la vache' },
  { front: '🦒', back: 'la girafe' },
  { front: '🐘', back: "l'éléphant" },
  { front: '🐫', back: 'le chameau' },
  { front: '🐣', back: 'le poussin' },
  { front: '🐓', back: 'le coq' },
  { front: '🕊️', back: 'la colombe' },
  { front: '🦚', back: 'le paon' },
  { front: '🐬', back: 'le dauphin' },
  { front: '🦈', back: 'le requin' },
  { front: '🦀', back: 'le crabe' },
  { front: '🪼', back: 'la méduse' },
  { front: '🐛', back: 'la chenille' },
  { front: '🦖', back: 'le tyrannosaure' },
  { front: '🦕', back: 'le dinosaure' },
  { front: '🦘', back: 'le kangourou' },
  { front: '🦥', back: 'le paresseux' },
  { front: '🦦', back: 'la loutre' },
  { front: '🦩', back: 'le flamant rose' },
  { front: '🐈', back: 'le chat' },
  { front: '🐕', back: 'le chien' },
  { front: '🐇', back: 'le lapin' },
  { front: '🦡', back: 'le blaireau' },
  { front: '🦨', back: 'la moufette' },
  { front: '🦝', back: 'le raton laveur' },
  { front: '🦭', back: 'le phoque' },
  { front: '🪶', back: 'la plume' },
  { front: '🥚', back: "l'œuf" },
  { front: '🦴', back: "l'os" },

  // --- 食べ物・飲み物 (Nourriture & Boissons) ---
  { front: '🍎', back: 'la pomme' },
  { front: '🍓', back: 'la fraise' },
  { front: '🍉', back: 'la pastèque' },
  { front: '🍒', back: 'la cerise' },
  { front: '🍍', back: "l'ananas" },
  { front: '🍊', back: "l'orange" },
  { front: '🍑', back: 'la pêche' },
  { front: '🥕', back: 'la carotte' },
  { front: '🥦', back: 'le brocoli' },
  { front: '🥑', back: "l'avocat" },
  { front: '🫑', back: 'le poivron' },
  { front: '🍆', back: "l'aubergine" },
  { front: '🍇', back: 'le raisin' },
  { front: '🥒', back: 'le concombre' },
  { front: '🍄‍🟫', back: 'le champignon' },
  { front: '🧄', back: "l'ail" },
  { front: '🥬', back: 'la salade' },
  { front: '🧅', back: "l'oignon" },
  { front: '🥔', back: 'la pomme de terre' },
  { front: '🌽', back: 'le maïs' },
  { front: '🍅', back: 'la tomate' },
  { front: '🍋', back: 'le citron' },
  { front: '🍌', back: 'la banane' },
  { front: '🍐', back: 'la poire' },
  { front: '🥝', back: 'le kiwi' },
  { front: '🥭', back: 'la mangue' },
  { front: '🥥', back: 'la noix de coco' },
  { front: '🥐', back: 'le croissant' },
  { front: '🥖', back: 'la baguettes' },
  { front: '🍞', back: 'le pain' },
  { front: '🧀', back: 'le fromage' },
  { front: '🥩', back: 'la viande' },
  { front: '🍗', back: 'le poulet' },
  { front: '🍔', back: 'le hamburger' },
  { front: '🍕', back: 'la pizza' },
  { front: '🍜', back: 'les nouilles' },
  { front: '🍣', back: 'les sushis' },
  { front: '🍩', back: 'le donut' },
  { front: '🍰', back: 'le gâteau' },
  { front: '🍫', back: 'le chocolat' },
  { front: '☕', back: 'le café' },
  { front: '🍵', back: 'le thé' },
  { front: '🍺', back: 'la bière' },
  { front: '🍷', back: 'le vin' },

  // --- 植物・自然・天気 (Nature & Météo) ---
  { front: '💎', back: 'le diamant' },
  { front: '🌸', back: 'la fleur de cerisier' },
  { front: '🪻', back: 'la jacinthe' },
  { front: '🌷', back: 'la tulipe' },
  { front: '🌹', back: 'la rose' },
  { front: '🌻', back: 'le tournesol' },
  { front: '🌼', back: 'la marguerite' },
  { front: '🌵', back: 'le cactus' },
  { front: '🌲', back: 'le conifère' },
  { front: '🌳', back: "l'arbre" },
  { front: '🍀', back: 'le trèfle à quatre feuilles' },
  { front: '🍁', back: 'la feuille d’érable' },
  { front: '☔', back: 'le parapluie' },
  { front: '☀️', back: 'le soleil' },
  { front: '🌙', back: 'la lune' },
  { front: '🌏', back: 'la terre' },
  { front: '🌕', back: 'la pleine lune' },
  { front: '⚡', back: "l'éclair" },
  { front: '🌈', back: 'l’arc-en-ciel' },
  { front: '🔥', back: 'le feu' },
  { front: '💧', back: 'la goutte d’eau' },
  { front: '🌊', back: 'la vague' },
  { front: '❄️', back: 'le flocon de neige' },
  { front: '⭐', back: 'l’étoile' },

  // --- 感情・顔 (Émotions & Visages) ---
  { front: '😄', back: 'le sourire' },
  { front: '🥲', back: 'le rire avec une larme' },
  { front: '🤤', back: 'la bave' },
  { front: '🥹', back: 'les yeux suppliants' },
  { front: '😱', back: 'la peur' },
  { front: '👻', back: 'le fantôme' },
  { front: '💀', back: 'le crâne' },
  { front: '😍', back: 'les yeux en cœur' },
  { front: '😎', back: 'le lunettes de soleil' },
  { front: '😢', back: 'la tristesse' },
  { front: '😡', back: 'la colère' },
  { front: '🥳', back: 'la fête' },
  { front: '😴', back: 'le sommeil' },
  { front: '🤖', back: 'le robot' },
  { front: '👽', back: 'l’extraterrestre' },
  { front: '💩', back: 'le caca' },

  // --- 道具・小物・その他 (Objets & Divers) ---
  { front: '🎉', back: 'les confettis' },
  { front: '🧭', back: 'la boussole' },
  { front: '🎡', back: 'la grande roue' },
  { front: '💍', back: 'la bague' },
  { front: '🛡️', back: 'le bouclier' },
  { front: '🗡️', back: "l'épée" },
  { front: '⚰️', back: 'le cercueil' },
  { front: '🪦', back: 'la tombe' },
  { front: '🗝️', back: 'la vieille clé' },
  { front: '💻', back: 'l’ordinateur' },
  { front: '📱', back: 'le téléphone' },
  { front: '📷', back: 'l’appareil photo' },
  { front: '📚', back: 'les livres' },
  { front: '✏️', back: 'le crayon' },
  { front: '🎨', back: 'la palette de peinture' },
  { front: '🎸', back: 'la guitare' },
  { front: '⚽', back: 'le ballon de football' },
  { front: '🚗', back: 'la voiture' },
  { front: '✈️', back: 'l’avion' },
  { front: '🚀', back: 'la fusée' },
  { front: '⏰', back: 'le réveil' },
  { front: '🎁', back: 'le cadeau' },
  { front: '🎈', back: 'le ballon' },
  { front: '💡', back: 'l’ampoule' },
  { front: '🔑', back: 'la clé' },
  { front: '🔒', back: 'le cadenas' },

  // --- 職業・人物 (Métiers & Personnes) ---
  { front: '👩🏻‍🎨', back: "l'artiste" },
  { front: '👩🏻‍🍳', back: 'la cuisinière' },
  { front: '👩🏻‍🚒', back: 'la pompière' },
  { front: '👩🏻‍🌾', back: "l'agricultrice" },
  { front: '👩🏻‍✈️', back: 'la pilote' },
  { front: '👩🏻‍🎓', back: "l'étudiante" },
  { front: '👩🏻‍🎤', back: 'la chanteuse' },
  { front: '👩🏻‍⚖️', back: 'la juge' },
  { front: '🐱', back: 'le chat' } // 🐾 おまけの猫ちゃん！
];
