window.French = [
  // --- 動物・生き物 (Animaux) ---
  { front: '🐺', back: 'le loup' },
  { front: '🦊', back: 'le renard' },
  { front: '🐯', back: 'le tigre' },
  { front: '🦁', back: 'le lion' },
  { front: '🦇', back: 'la chauve-souris' },
  { front: '🐵', back: 'le singe' },
  { front: '🦉', back: 'le hibou' },
  { front: '🐢', back: 'la tortue' },
  { front: '🐻‍❄️', back: "l'ours polaire" },
  { front: '🐨', back: 'le koala' },
  { front: '🐴', back: 'le cheval' },
  { front: '🐹', back: 'le hamster' },
  { front: '🦓', back: 'le zèbre' },
  { front: '🐑', back: 'le mouton' },
  { front: '🐖', back: 'le cochon' },
  { front: '🐄', back: 'la vache' },
  { front: '🦒', back: 'la girafe' },
  { front: '🐘', back: "l'éléphant" },
  { front: '🐫', back: 'le chameau' },
  { front: '🐣', back: 'le poussin' },
  { front: '🐓', back: 'le coq' },
  { front: '🕊️', back: 'la colombe' },
  { front: '🦚', back: 'le paon' },
  { front: '🐬', back: 'le dauphin' },
  { front: '🦈', back: 'le requin' },
  { front: '🦀', back: 'le crabe' },
  { front: '🪼', back: 'la méduse' },
  { front: '🐛', back: 'la chenille' },
  { front: '🦖', back: 'le tyrannosaure' },
  { front: '🦕', back: 'le dinosaure' },
  { front: '🦘', back: 'le kangourou' },
  { front: '🦥', back: 'le paresseux' },
  { front: '🦦', back: 'la loutre' },
  { front: '🦩', back: 'le flamant rose' },
  { front: '🐈', back: 'le chat' },
  { front: '🐕', back: 'le chien' },
  { front: '🐇', back: 'le lapin' },
  { front: '🦡', back: 'le blaireau' },
  { front: '🦨', back: 'la moufette' },
  { front: '🦝', back: 'le raton laveur' },
  { front: '🦭', back: 'le phoque' },
  { front: '🪶', back: 'la plume' },
  { front: '🥚', back: "l'œuf" },
  { front: '🦴', back: "l'os" },
  { front: '🦧', back: "l'orang-outan" },
  { front: '🐀', back: 'le rat' },
  { front: '🐁', back: 'la souris' },
  { front: '🐂', back: 'le bœuf' },
  { front: '🐋', back: 'la baleine' },
  { front: '🐌', back: "l'escargot" },
  { front: '🐃', back: 'le buffle' },
  { front: '🐆', back: 'le léopard' },
  { front: '🐉', back: 'le dragon' },
  { front: '🐊', back: 'le crocodile' },
  { front: '🐗', back: 'le sanglier' },
  { front: '🐙', back: 'la pieuvre' },
  { front: '🐚', back: 'le coquillage' },
  { front: '🐟', back: 'le poisson' },
  { front: '🐐', back: 'la chèvre' },
  { front: '🐍', back: 'le serpent' },
  { front: '🐩', back: 'le caniche' },
  { front: '🐪', back: 'le dromadaire' },
  { front: '🐭', back: 'la souris' },
  { front: '🐮', back: 'la vachotte' },
  { front: '🐳', back: 'la baleine' },
  { front: '🐻', back: 'l’ours' },
  { front: '🐼', back: 'le panda' },
  { front: '🐾', back: 'la empreinte' },
  { front: '🐿️', back: 'l’écureuil' },
  { front: '🦆', back: 'le canard' },
  { front: '🦅', back: 'l’aigle' },
  { front: '🦄', back: 'la licorne' },
  { front: '🦃', back: 'le dindon' },
  { front: '🦂', back: 'le scorpion' },
  { front: '🦌', back: 'le cerf' },
  { front: '🦍', back: 'le gorille' },
  { front: '🦎', back: 'le lézard' },
  { front: '🦏', back: 'le rhinocéros' },
  { front: '🦐', back: 'la crevette' },
  { front: '🦑', back: 'le calmar' },
  { front: '🦣', back: 'le mammouth' },
  { front: '🦛', back: 'l’hippopotame' },
  { front: '🦙', back: 'le lama' },
  { front: '🦔', back: 'le hérisson' },
  { front: '🦫', back: 'le castor' },
  { front: '🦬', back: 'le bison' },
  { front: '🫎', back: 'l’élan' },
  { front: '🫏', back: 'l’âne' },
  { front: '🙈', back: 'le singe (qui se cache les yeux)' },
  { front: '🙉', back: 'le singe (qui se bouche les oreilles)' },
  { front: '🙊', back: 'le singe (qui se bouche la bouche)' },
  { front: '🐸', back: 'la grenouille' },
  { front: '🦮', back: 'le chien guide' },
  { front: '🐕‍🦺', back: 'le chien d’assistance' },
  { front: '🐏', back: 'le bélier' },
  { front: '🐦', back: 'l’oiseau' },
  { front: '🐦‍⬛', back: 'le corbeau' },
  { front: '🦜', back: 'le perroquet' },
  { front: '🦤', back: 'le dodo' },
  { front: '🦢', back: 'le cygne' },
  { front: '🪿', back: 'l’oie' },
  { front: '🐦‍🔥', back: 'le phénix' },
  { front: '🐧', back: 'le manchot' },
  { front: '🫍', back: 'l’organisme marin' }, // もしくは微調整用のプレースホルダー等
  { front: '🐠', back: 'le poisson tropical' },
  { front: '🐡', back: 'le poisson-globe' },
  { front: '🦪', back: 'l’huître' },
  { front: '🪸', back: 'le corail' },
  { front: '🫧', back: 'les bulles' },
  { front: '🕷️', back: 'l’araignée' },
  { front: '🕸️', back: 'la toile d’araignée' },
  { front: '🐜', back: 'la fourmi' },
  { front: '🦗', back: 'le grillon' },
  { front: '🪲', back: 'le coléoptère' },
  { front: '🦟', back: 'le moustique' },
  { front: '🪳', back: 'la cafard' },
  { front: '🪰', back: 'la mouche' },
  { front: '🐝', back: 'l’abeille' },
  { front: '🐞', back: 'la coccinelle' },
  { front: '🦋', back: 'le papillon' },
  { front: '🪱', back: 'le ver' },
  { front: '🦠', back: 'le microbe' },



  // --- 食べ物・飲み物 (Nourriture & Boissons) ---
  
  { front: '🍎', back: 'la pomme' },
  { front: '🍓', back: 'la fraise' },
  { front: '🍉', back: 'la pastèque' },
  { front: '🍒', back: 'la cerise' },
  { front: '🍍', back: "l'ananas" },
  { front: '🍊', back: "l'orange" },
  { front: '🍑', back: 'la pêche' },
  { front: '🥕', back: 'la carotte' },
  { front: '🥦', back: 'le brocoli' },
  { front: '🥑', back: "l'avocat" },
  { front: '🫑', back: 'le poivron' },
  { front: '🍆', back: "l'aubergine" },
  { front: '🍇', back: 'le raisin' },
  { front: '🥒', back: 'le concombre' },
  { front: '🍄‍🟫', back: 'le champignon' },
  { front: '🧄', back: "l'ail" },
  { front: '🥬', back: 'la salade' },
  { front: '🧅', back: "l'oignon" },
  { front: '🥔', back: 'la pomme de terre' },
  { front: '🌽', back: 'le maïs' },
  { front: '🍅', back: 'la tomate' },
  { front: '🍋', back: 'le citron' },
  { front: '🍌', back: 'la banane' },
  { front: '🍐', back: 'la poire' },
  { front: '🥝', back: 'le kiwi' },
  { front: '🥭', back: 'la mangue' },
  { front: '🥥', back: 'la noix de coco' },
  { front: '🥐', back: 'le croissant' },
  { front: '🥖', back: 'la baguettes' },
  { front: '🍞', back: 'le pain' },
  { front: '🧀', back: 'le fromage' },
  { front: '🥩', back: 'la viande' },
  { front: '🍗', back: 'le poulet' },
  { front: '🍔', back: 'le hamburger' },
  { front: '🍕', back: 'la pizza' },
  { front: '🍜', back: 'les nouilles' },
  { front: '🍣', back: 'les sushis' },
  { front: '🍩', back: 'le donut' },
  { front: '🍰', back: 'le gâteau' },
  { front: '🍫', back: 'le chocolat' },
  { front: '☕', back: 'le café' },
  { front: '🍵', back: 'le thé' },
  { front: '🍺', back: 'la bière' },
  { front: '🍷', back: 'le vin' },
  { front: '🌶️', back: 'le piment' },
  { front: '🍋‍🟩', back: 'le citron vert' },
  { front: '🍈', back: 'le melon' },
  { front: '🫛', back: 'les pois' },
  { front: '🍏', back: 'la pomme verte' },
  { front: '🫒', back: "l'olive" },
  { front: '🫐', back: 'les myrtilles' },
  { front: '🍠', back: 'la patate douce' },
  { front: '🫜', back: 'le navet' },
  { front: '🫚', back: 'le gingembre' },
  { front: '🫘', back: 'les haricots' },
  { front: '🌰', back: 'la chataigne' },
  { front: '🥜', back: 'les cacahuètes' },
  { front: '🫓', back: 'le pain plat' },
  { front: '🥯', back: 'le bagel' },
  { front: '🧇', back: 'la gaufre' },
  { front: '🥞', back: 'les crêpes' },
  { front: '🍳', back: 'l’œuf au plat' },
  { front: '🥓', back: 'le bacon' },
  { front: '🍖', back: 'la viande avec os' },
  { front: '🌭', back: 'le hot-dog' },
  { front: '🥪', back: 'le sandwich' },
  { front: '🥨', back: 'le bretzel' },
  { front: '🍟', back: 'les frites' },
  { front: '🫔', back: 'le tamal' },
  { front: '🌮', back: 'le taco' },
  { front: '🌯', back: 'le burrito' },
  { front: '🥙', back: 'le pita farci' },
  { front: '🧆', back: 'les falafels' },
  { front: '🥘', back: 'la paella' },
  { front: '🍝', back: 'les spaghettis' },
  { front: '🥫', back: 'la conserve' },
  { front: '🫕', back: 'la fondue' },
  { front: '🥣', back: 'le bol de céréales' },
  { front: '🥗', back: 'la salade composée' },
  { front: '🍲', back: 'la potée' },
  { front: '🍛', back: 'le riz au curry' },
  { front: '🦪', back: "l'huître" },
  { front: '🦞', back: 'le homard' },
  { front: '🍤', back: 'la crevette' },
  { front: '🥡', back: 'la boîte à emporter' },
  { front: '🍚', back: 'le riz' },
  { front: '🍱', back: 'le bento' },
  { front: '🥟', back: 'le ravioli' },
  { front: '🍢', back: 'l’oden' },
  { front: '🍙', back: 'la boulette de riz' },
  { front: '🍘', back: 'le cracker de riz' },
  { front: '🍥', back: 'le gâteau de poisson' },
  { front: '🍡', back: 'le dango' },
  { front: '🥠', back: 'le biscuit de la fortune' },
  { front: '🥮', back: 'le gâteau de lune' },
  { front: '🍧', back: 'la glace pilée' },
  { front: '🍨', back: 'la crème glacée' },
  { front: '🍦', back: 'la glace à l’italienne' },
  { front: '🥧', back: 'la tarte' },
  { front: '🍮', back: 'le flan' },
  { front: '🎂', back: 'le gâteau d’anniversaire' },
  { front: '🧁', back: 'lecupcake' },
  { front: '🍭', back: 'la sucette' },
  { front: '🍬', back: 'le bonbon' },
  { front: '🍪', back: 'le biscuit' },
  { front: '🍯', back: 'le miel' },
  { front: '🧂', back: 'le sel' },
  { front: '🧈', back: 'le beurre' },
  { front: '🍿', back: 'le pop-corn' },
  { front: '🧊', back: 'le glaçon' },
  { front: '🫙', back: 'le bocal' },
  { front: '🥤', back: 'la boisson' },
  { front: '🧋', back: 'le thé aux perles' },
  { front: '🧃', back: 'la brique de jus' },
  { front: '🥛', back: 'le lait' },
  { front: '🍼', back: 'le biberon' },
  { front: '🫖', back: 'la théière' },
  { front: '🧉', back: 'le maté' },
  { front: '🍻', back: 'les chopes de bière' },
  { front: '🥂', back: 'les flûtes de champagne' },
  { front: '🍾', back: 'la bouteille de champagne' },
  { front: '🥃', back: 'le verre de whisky' },
  { front: '🫗', back: 'le liquide versé' },
  { front: '🍸', back: 'le verre de cocktail' },
  { front: '🍹', back: 'le cocktail tropical' },
  { front: '🍶', back: 'le saké' },
  { front: '🥢', back: 'les baguettes' },
  { front: '🍴', back: 'la fourchette et le couteau' },
  { front: '🥄', back: 'la cuillère' },
  { front: '🔪', back: 'le couteau' },
  { front: '🍽️', back: 'l’assiette et couverts' },

  // --- 植物・自然・天気 (Nature & Météo) ---
  { front: '💎', back: 'le diamant' },
  { front: '🌸', back: 'la fleur de cerisier' },
  { front: '🪻', back: 'la jacinthe' },
  { front: '🌷', back: 'la tulipe' },
  { front: '🌹', back: 'la rose' },
  { front: '🌻', back: 'le tournesol' },
  { front: '🌼', back: 'la marguerite' },
  { front: '🌵', back: 'le cactus' },
  { front: '🌲', back: 'le conifère' },
  { front: '🌳', back: "l'arbre" },
  { front: '🍀', back: 'le trèfle à quatre feuilles' },
  { front: '🍁', back: 'la feuille d’érable' },
  { front: '☔', back: 'le parapluie' },
  { front: '☀️', back: 'le soleil' },
  { front: '🌙', back: 'la lune' },
  { front: '🌏', back: 'la terre' },
  { front: '🌕', back: 'la pleine lune' },
  { front: '⚡', back: "l'éclair" },
  { front: '🌈', back: 'l’arc-en-ciel' },
  { front: '🔥', back: 'le feu' },
  { front: '💧', back: 'la goutte d’eau' },
  { front: '🌊', back: 'la vague' },
  { front: '❄️', back: 'le flocon de neige' },
  { front: '⭐', back: 'l’étoile' },
  { front: '💐', back: 'le bouquet' },
  { front: '🥀', back: 'la fleur fanée' },
  { front: '🌺', back: 'l’hibiscus' },
  { front: '🪷', back: 'le lotus' },
  { front: '💮', back: 'la fleur blanche' },
  { front: '🏵️', back: 'la rosette' },
  { front: '🍂', back: 'les feuilles mortes' },
  { front: '🍄', back: 'le champignon' },
  { front: '🌾', back: 'l’épis de riz' },
  { front: '🌿', back: 'la herbe' },
  { front: '🌱', back: 'la jeune pousse' },
  { front: '🍃', back: 'les feuilles au vent' },
  { front: '☘️', back: 'le trèfle' },
  { front: '🪴', back: 'la plante en pot' },
  { front: '🌴', back: 'le palmier' },
  { front: '🪾', back: 'l’arbre sans feuilles' },
  { front: '🪵', back: 'le bois' },
  { front: '🪹', back: 'le nid vide' },
  { front: '🪺', back: 'le nid avec des œufs' },
  { front: '🪨', back: 'le rocher' },
  { front: '🛘', back: 'le chariot de bagages' },
  { front: '⛰️', back: 'la montagne' },
  { front: '🏔️', back: 'la montagne enneigée' },
  { front: '☃️', back: 'le bonhomme de neige' },
  { front: '⛄', back: 'le bonhomme de neige sans neige' },
  { front: '🌡️', back: 'le thermomètre' },
  { front: '🌋', back: 'le volcan' },
  { front: '🏜️', back: 'le désert' },
  { front: '🏞️', back: 'le paysage' },
  { front: '🌅', back: 'le lever du soleil' },
  { front: '🌄', back: 'le lever du soleil sur les montagnes' },
  { front: '🏝️', back: 'l’île déserte' },
  { front: '🏖️', back: 'la plage et parasol' },
  { front: '🌬️', back: 'le visage de vent' },
  { front: '🌀', back: 'le cyclone' },
  { front: '🌪️', back: 'la tornade' },
  { front: '☁️', back: 'le nuage' },
  { front: '🌨️', back: 'le nuage et neige' },
  { front: '🌧️', back: 'le nuage et pluie' },
  { front: '🌩️', back: 'le nuage et éclair' },
  { front: '⛈️', back: 'l’orage' },
  { front: '🌦️', back: 'le soleil derrière un nuage' },
  { front: '🌥️', back: 'le grand nuage' },
  { front: '⛅', back: 'le soleil derrière un nuage' },
  { front: '🌤️', back: 'le petit soleil derrière un nuage' },
  { front: '🌞', back: 'le soleil avec visage' },
  { front: '🌝', back: 'la pleine lune avec visage' },
  { front: '🌚', back: 'la nouvelle lune avec visage' },
  { front: '🌜', back: 'le premier quartier de lune avec visage' },
  { front: '🌛', back: 'le dernier quartier de lune avec visage' },
  { front: '🌟', back: 'l’étoile scintillante' },
  { front: '✨', back: 'les étincelles' },
  { front: '🕳️', back: 'le trou' },
  { front: '🪐', back: 'la planète aux anneaux' },
  { front: '🌍', back: 'la terre (Europe-Afrique)' },
  { front: '🌎', back: 'la terre (Amériques)' },
  { front: '🌫️', back: 'le brouillard' },
  { front: '🌠', back: 'l’étoile filante' },
  { front: '🌌', back: 'la voie lactée' },
  { front: '☄️', back: 'la comète' },
  { front: '🌑', back: 'la nouvelle lune' },
  { front: '🌒', back: 'le premier croissant de lune' },
  { front: '🌓', back: 'le premier quartier de lune' },
  { front: '🌔', back: 'la lune gibbeuse croissante' },
  { front: '🌖', back: 'la lune gibbeuse décroissante' },
  { front: '🌗', back: 'le dernier quartier de lune' },
  { front: '🌘', back: 'le dernier croissant de lune' },


  // --- 感情・顔 (Émotions & Visages) ---
  { front: '😄', back: 'le sourire' },
  { front: '🥲', back: 'le rire avec une larme' },
  { front: '🤤', back: 'la bave' },
  { front: '🥹', back: 'les yeux suppliants' },
  { front: '😱', back: 'la peur' },
  { front: '👻', back: 'le fantôme' },
  { front: '💀', back: 'le crâne' },
  { front: '😍', back: 'les yeux en cœur' },
  { front: '😎', back: 'le lunettes de soleil' },
  { front: '😢', back: 'la tristesse' },
  { front: '😡', back: 'la colère' },
  { front: '🥳', back: 'la fête' },
  { front: '😴', back: 'le sommeil' },
  { front: '🤖', back: 'le robot' },
  { front: '👽', back: 'l’extraterrestre' },
  { front: '💩', back: 'le caca' },

  // --- 道具・小物・その他 (Objets & Divers) ---
  { front: '🎉', back: 'les confettis' },
  { front: '🧭', back: 'la boussole' },
  { front: '🎡', back: 'la grande roue' },
  { front: '💍', back: 'la bague' },
  { front: '🛡️', back: 'le bouclier' },
  { front: '🗡️', back: "l'épée" },
  { front: '⚰️', back: 'le cercueil' },
  { front: '🪦', back: 'la tombe' },
  { front: '🗝️', back: 'la vieille clé' },
  { front: '💻', back: 'l’ordinateur' },
  { front: '📱', back: 'le téléphone' },
  { front: '📷', back: 'l’appareil photo' },
  { front: '📚', back: 'les livres' },
  { front: '✏️', back: 'le crayon' },
  { front: '🎨', back: 'la palette de peinture' },
  { front: '🎸', back: 'la guitare' },
  { front: '⚽', back: 'le ballon de football' },
  { front: '🚗', back: 'la voiture' },
  { front: '✈️', back: 'l’avion' },
  { front: '🚀', back: 'la fusée' },
  { front: '⏰', back: 'le réveil' },
  { front: '🎁', back: 'le cadeau' },
  { front: '🎈', back: 'le ballon' },
  { front: '💡', back: 'l’ampoule' },
  { front: '🔑', back: 'la clé' },
  { front: '🔒', back: 'le cadenas' },

  // --- 職業・人物 (Métiers & Personnes) ---
  { front: '👩🏻‍🎨', back: "l'artiste" },
  { front: '👩🏻‍🍳', back: 'la cuisinière' },
  { front: '👩🏻‍🚒', back: 'la pompière' },
  { front: '👩🏻‍🌾', back: "l'agricultrice" },
  { front: '👩🏻‍✈️', back: 'la pilote' },
  { front: '👩🏻‍🎓', back: "l'étudiante" },
  { front: '👩🏻‍🎤', back: 'la chanteuse' },
  { front: '👩🏻‍⚖️', back: 'la juge' },
  { front: '🐱', back: 'le chat' } // 🐾 おまけの猫ちゃん！
];
