window.Italian = [
  // --- 動物・生き物 ---
  { front: '🐺', back: 'lupo' },
  { front: '🦊', back: 'volpe' },
  { front: '🐱', back: 'gatto' },
  { front: '🐯', back: 'tigre' },
  { front: '🦁', back: 'leone' },
  { front: '🦇', back: 'pipistrello' },
  { front: '🐵', back: 'scimmia' },
  { front: '🦉', back: 'gufo' },
  { front: '🐢', back: 'tartaruga' },
  { front: '🐻‍❄️', back: 'orso polare' },
  { front: '🐨', back: 'koala' },
  { front: '🐴', back: 'cavallo' },
  { front: '🐹', back: 'criceto' },
  { front: '🦓', back: 'zebra' },
  { front: '🐑', back: 'pecora' },
  { front: '🐖', back: 'maiale' },
  { front: '🐄', back: 'mucca' },
  { front: '🦒', back: 'giraffa' },
  { front: '🐘', back: 'elefante' },
  { front: '🐫', back: 'cammello' },
  { front: '🐣', back: 'pulcino' },
  { front: '🐓', back: 'gallo' },
  { front: '🕊️', back: 'colomba' },
  { front: '🦚', back: 'pavone' },
  { front: '🐬', back: 'delfino' },
  { front: '🦈', back: 'squalo' },
  { front: '🦀', back: 'granchio' },
  { front: '🪼', back: 'medusa' },
  { front: '🐛', back: 'bruco' },
  
  // --- 食べ物 ---
  { front: '🍎', back: 'mela' },
  { front: '🍓', back: 'fragola' },
  { front: '🍉', back: 'anguria' },
  { front: '🍒', back: 'ciliegia' },
  { front: '🍍', back: 'ananas' },
  { front: '🍊', back: 'arancia' },
  { front: '🍑', back: 'pesca' },
  { front: '🥕', back: 'carota' },
  { front: '🥦', back: 'broccoli' },
  { front: '🥑', back: 'avocado' },
  { front: '🫑', back: 'peperone' },
  { front: '🍆', back: 'melanzana' },
  { front: '🍇', back: 'uva' },
  { front: '🥒', back: 'cetriolo' },
  { front: '🍄‍🟫', back: 'fungo' },
  { front: '🧄', back: 'aglio' },
  { front: '🍺', back: 'birra' },
  
  // --- 自然・天気・その他 ---
  { front: '💎', back: 'diamante' },
  { front: '🌸', back: 'fiore di ciliegio' },
  { front: '☔', back: 'ombrello' },
  { front: '☀️', back: 'sole' },
  { front: '🌙', back: 'luna' },
  { front: '🌏', back: 'terra' },
  { front: '🌕', back: 'luna piena' },
  { front: '⚡', back: 'fulmine' },
  { front: '🎉', back: 'coriandoli' },
  { front: '🧭', back: 'bussola' },
  { front: '🎡', back: 'ruota panoramica' },
  { front: '💍', back: 'anello' },
  { front: '🛡️', back: 'scudo' },
  { front: '🗡️', back: 'spada' },
  { front: '⚰️', back: 'bara' },
  { front: '🪦', back: 'lapide' },
  { front: '🗝️', back: 'chiave vecchia' },
  
  // --- 感情・顔 ---
  { front: '😄', back: 'sorriso' },
  { front: '🥲', back: 'sorriso con lacrima' },
  { front: '😱', back: 'paura' },
  { front: '👻', back: 'fantasma' },
  { front: '💀', back: 'teschio' },
  
  // --- 職業 (女性) ---
  { front: '👩🏻‍🎨', back: 'artista' },
  { front: '👩🏻‍🍳', back: 'cuoca' },
  { front: '👩🏻‍🚒', back: 'vigile del fuoco' },
  { front: '👩🏻‍🌾', back: 'contadina' },
  { front: '👩🏻‍✈️', back: 'pilota' },
  { front: '👩🏻‍🎓', back: 'studentessa' },
  { front: '👩🏻‍🎤', back: 'cantante' },
  { front: '👩🏻‍⚖️', back: 'giudice' }
];
