window.German = [
  // --- 動物・生き物 ---
  { front: '🐺', back: 'Wolf' },
  { front: '🦊', back: 'Fuchs' },
  { front: '🐱', back: 'Katze' },
  { front: '🐯', back: 'Tiger' },
  { front: '🦁', back: 'Löwe' },
  { front: '🦇', back: 'Fledermaus' },
  { front: '🐵', back: 'Affe' },
  { front: '🦉', back: 'Eule' },
  { front: '🐢', back: 'Schildkröte' },
  { front: '🐻‍❄️', back: 'Eisbär' },
  { front: '🐨', back: 'Koala' },
  { front: '🐴', back: 'Pferd' },
  { front: '🐹', back: 'Hamster' },
  { front: '🦓', back: 'Zebra' },
  { front: '🐑', back: 'Schaf' },
  { front: '🐖', back: 'Schwein' },
  { front: '🐄', back: 'Kuh' },
  { front: '🦒', back: 'Giraffe' },
  { front: '🐘', back: 'Elefant' },
  { front: '🐫', back: 'Kamel' },
  { front: '🐣', back: 'Küken' },
  { front: '🐓', back: 'Hahn' },
  { front: '🕊️', back: 'Taube' },
  { front: '🦚', back: 'Pfau' },
  { front: '🐬', back: 'Delfin' },
  { front: '🦈', back: 'Hai' },
  { front: '🦀', back: 'Krabbe' },
  { front: '🪼', back: 'Qualle' },
  { front: '🐛', back: 'Raupe' },
  
  // --- 食べ物 ---
  { front: '🍎', back: 'Apfel' },
  { front: '🍓', back: 'Erdbeere' },
  { front: '🍉', back: 'Wassermelone' },
  { front: '🍒', back: 'Kirsche' },
  { front: '🍍', back: 'Ananas' },
  { front: '🍊', back: 'Orange' },
  { front: '🍑', back: 'Pfirsich' },
  { front: '🥕', back: 'Karotte' },
  { front: '🥦', back: 'Brokkoli' },
  { front: '🥑', back: 'Avocado' },
  { front: '🫑', back: 'Paprika' },
  { front: '🍆', back: 'Aubergine' },
  { front: '🍇', back: 'Traube' },
  { front: '🥒', back: 'Gurke' },
  { front: '🍄‍🟫', back: 'Pilz' },
  { front: '🧄', back: 'Knoblauch' },
  { front: '🍺', back: 'Bier' },
  
  // --- 自然・天気・その他 ---
  { front: '💎', back: 'Diamant' },
  { front: '🌸', back: 'Kirschblüte' },
  { front: '☔', back: 'Regenschirm' },
  { front: '☀️', back: 'Sonne' },
  { front: '🌙', back: 'Mond' },
  { front: '🌏', back: 'Erde' },
  { front: '🌕', back: 'Vollmond' },
  { front: '⚡', back: 'Blitz' },
  { front: '🎉', back: 'Konfetti' },
  { front: '🧭', back: 'Kompass' },
  { front: '🎡', back: 'Riesenrad' },
  { front: '💍', back: 'Ring' },
  { front: '🛡️', back: 'Schild' },
  { front: '🗡️', back: 'Schwert' },
  { front: '⚰️', back: 'Sarg' },
  { front: '🪦', back: 'Grabstein' },
  { front: '🗝️', back: 'alter Schlüssel' },
  
  // --- 感情・顔 ---
  { front: '😄', back: 'Lächeln' },
  { front: '🥲', back: 'Lächeln mit Träne' },
  { front: '😱', back: 'Angst' },
  { front: '👻', back: 'Geist' },
  { front: '💀', back: 'Totenkopf' },
  
  // --- 職業 (女性) ---
  { front: '👩🏻‍🎨', back: 'Künstlerin' },
  { front: '👩🏻‍🍳', back: 'Köchin' },
  { front: '👩🏻‍🚒', back: 'Feuerwehrfrau' },
  { front: '👩🏻‍🌾', back: 'Bäuerin' },
  { front: '👩🏻‍✈️', back: 'Pilotin' },
  { front: '👩🏻‍🎓', back: 'Studentin' },
  { front: '👩🏻‍🎤', back: 'Sängerin' },
  { front: '👩🏻‍⚖️', back: 'Richterin' }
];